'use client'

import {useEffect,useMemo,useState} from 'react'
import {BadgeCheck, KeyRound, Power, ShieldCheck, UserPlus, UsersRound} from 'lucide-react'
import {supabase} from '@/lib/supabase'

type Staff={profile_id:string;franchise_id:string;staff_role:string;permissions:Record<string,boolean>;active:boolean;profile?:{full_name:string;email:string;active:boolean}}
type Temp={email:string;password:string}
const roleLabels:Record<string,string>={manager:'Gestor',operator:'Operador / Despachante',financial:'Financeiro',support:'Suporte',marketing:'Marketing'}
const permissionLabels:Record<string,string>={operation:'Operação e corridas',drivers:'Motoristas e documentos',users:'Passageiros e cadastros',pricing:'Tarifas e categorias',finance:'Financeiro e pagamentos',support:'Suporte e chamados',marketing:'Promoções e anúncios',reports:'Relatórios',settings:'Configurações e equipe'}
const defaults:Record<string,Record<string,boolean>>={manager:{operation:true,drivers:true,users:true,pricing:true,finance:true,support:true,marketing:true,reports:true,settings:true},operator:{operation:true,drivers:true,users:true,pricing:false,finance:false,support:false,marketing:false,reports:false,settings:false},financial:{operation:false,drivers:false,users:false,pricing:false,finance:true,support:false,marketing:false,reports:true,settings:false},support:{operation:true,drivers:false,users:true,pricing:false,finance:false,support:true,marketing:false,reports:false,settings:false},marketing:{operation:false,drivers:false,users:false,pricing:false,finance:false,support:false,marketing:true,reports:true,settings:false}}

export default function FranchiseTeamPage(){
 const[franchiseId,setFranchiseId]=useState('');const[rows,setRows]=useState<Staff[]>([]);const[callerRole,setCallerRole]=useState('');const[callerStaffRole,setCallerStaffRole]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[temp,setTemp]=useState<Temp|null>(null)
 const[name,setName]=useState('');const[email,setEmail]=useState('');const[role,setRole]=useState('operator');const[permissions,setPermissions]=useState<Record<string,boolean>>(defaults.operator)
 async function load(){
  const{data:{user}}=await supabase.auth.getUser();if(!user)return
  let r=String(user.app_metadata?.role||'');const{data:profile}=await supabase.from('profiles').select('role,franchise_id').eq('id',user.id).maybeSingle();r=r||String(profile?.role||'');const fid=String(profile?.franchise_id||user.app_metadata?.franchise_id||'');setCallerRole(r);setFranchiseId(fid)
  let sr='';if(r==='operator'){const{data:self}=await supabase.from('franchise_staff_permissions').select('staff_role').eq('profile_id',user.id).maybeSingle();sr=String(self?.staff_role||'');setCallerStaffRole(sr)}
  if(!fid)return
  const{data:staff,error}=await supabase.from('franchise_staff_permissions').select('profile_id,franchise_id,staff_role,permissions,active').eq('franchise_id',fid).order('created_at')
  if(error){setMsg(error.message);return}const list=(staff||[]) as Staff[];const ids=list.map(x=>x.profile_id);let map=new Map<string,any>();if(ids.length){const{data:profiles}=await supabase.from('profiles').select('id,full_name,email,active').in('id',ids);map=new Map((profiles||[]).map(p=>[p.id,p]))}setRows(list.map(x=>({...x,profile:map.get(x.profile_id)})))
 }
 useEffect(()=>{void load()},[])
 const canManage=callerRole==='franchise_admin'||(callerRole==='operator'&&callerStaffRole==='manager')
 const roles=useMemo(()=>callerRole==='operator'?Object.keys(roleLabels).filter(x=>x!=='manager'):Object.keys(roleLabels),[callerRole])
 function changeRole(next:string){setRole(next);setPermissions({...defaults[next]})}
 async function create(){if(!canManage){setMsg('Seu perfil não pode administrar a equipe.');return}if(!name.trim()||!email.trim()){setMsg('Informe nome e e-mail.');return}setBusy(true);setTemp(null);const{data,error}=await supabase.functions.invoke('franchise-staff-access',{body:{action:'create_or_reset',franchise_id:franchiseId,full_name:name.trim(),email:email.trim(),staff_role:role,permissions}});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Falha ao criar acesso.');return}setTemp({email:data.email,password:data.temporary_password});setMsg(data.created?'Funcionário cadastrado. A senha abaixo é temporária.':'Acesso atualizado e nova senha temporária gerada.');setName('');setEmail('');void load()}
 async function toggle(s:Staff){if(!canManage)return;setBusy(true);const{data,error}=await supabase.functions.invoke('franchise-staff-access',{body:{action:'set_active',franchise_id:franchiseId,profile_id:s.profile_id,active:!s.active}});setBusy(false);setMsg(error||data?.error?(data?.error||error?.message):(!s.active?'Acesso reativado.':'Acesso desativado.'));if(!error&&!data?.error)void load()}
 async function reset(s:Staff){if(!canManage)return;if(!confirm(`Gerar uma nova senha temporária para ${s.profile?.full_name||s.profile?.email}?`))return;setBusy(true);setTemp(null);const{data,error}=await supabase.functions.invoke('franchise-staff-access',{body:{action:'create_or_reset',franchise_id:franchiseId,full_name:s.profile?.full_name||'Equipe CLICK-GO',email:s.profile?.email,staff_role:s.staff_role,permissions:s.permissions}});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Falha ao redefinir acesso.');return}setTemp({email:data.email,password:data.temporary_password});setMsg('Nova senha temporária gerada.');void load()}
 return <div className="regional-home"><div className="regional-heading"><div><div className="eyebrow">CLICK-GO Gestão · Regional</div><h1>Equipe e permissões</h1><p>Contas individuais para gestor, operação, financeiro, suporte e marketing.</p></div><span className="regional-sync-badge"><ShieldCheck size={14}/> Acesso protegido por função</span></div>{msg&&<div className="regional-alert">{msg}</div>}
  <div className="staff-grid"><div className="card"><div className="card-head-row"><div><div className="eyebrow">Novo acesso</div><h2>Adicionar funcionário</h2></div><UserPlus size={20}/></div>{!canManage?<p className="empty">Somente o administrador da franquia ou um gestor pode administrar a equipe.</p>:<><div className="field" style={{marginTop:14}}><label>Nome completo</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field" style={{marginTop:10}}><label>E-mail de acesso</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field" style={{marginTop:10}}><label>Função</label><select className="input" value={role} onChange={e=>changeRole(e.target.value)}>{roles.map(r=><option value={r} key={r}>{roleLabels[r]}</option>)}</select></div><div className="permission-grid">{Object.entries(permissionLabels).map(([key,label])=><label key={key} className={permissions[key]?'enabled':''}><input type="checkbox" checked={permissions[key]===true} disabled={role==='manager'} onChange={e=>setPermissions({...permissions,[key]:e.target.checked})}/><BadgeCheck size={13}/>{label}</label>)}</div><button className="button" style={{marginTop:14,width:'100%'}} disabled={busy} onClick={()=>void create()}><UserPlus size={15}/>{busy?'Salvando...':'Criar conta da equipe'}</button></>}</div>
   <div className="card staff-table-card"><div style={{padding:16}}><div className="card-head-row"><div><div className="eyebrow">Contas regionais</div><h2>Equipe cadastrada</h2></div><UsersRound size={21}/></div></div><div className="table-wrap" style={{border:0,borderRadius:0}}><table className="table"><thead><tr><th>Funcionário</th><th>Função</th><th>Permissões</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Nenhum funcionário cadastrado.</td></tr>:rows.map(s=><tr key={s.profile_id}><td><strong>{s.profile?.full_name||'Funcionário'}</strong><br/><small className="empty">{s.profile?.email||'—'}</small></td><td><span className="pill staff-role-pill">{roleLabels[s.staff_role]||s.staff_role}</span></td><td><div className="module-strip">{Object.entries(s.permissions||{}).filter(([,v])=>v).slice(0,4).map(([k])=><span className="on" key={k}>{permissionLabels[k]||k}</span>)}</div></td><td><span className={'pill '+(s.active?'green':'red')}>{s.active?'Ativo':'Inativo'}</span></td><td>{canManage&&<div className="toolbar"><button className="button secondary" disabled={busy} onClick={()=>void reset(s)}><KeyRound size={14}/>Senha</button><button className={s.active?'button danger':'button secondary'} disabled={busy} onClick={()=>void toggle(s)}><Power size={14}/>{s.active?'Desativar':'Ativar'}</button></div>}</td></tr>)}</tbody></table></div></div>
  </div>
  {temp&&<div className="card temp-access" style={{marginTop:12}}><div><span className="eyebrow">Credencial temporária</span><h3>Mostrar ao funcionário uma única vez</h3></div><div><label>E-mail</label><strong>{temp.email}</strong></div><div><label>Senha</label><strong>{temp.password}</strong></div><button className="button secondary" onClick={()=>setTemp(null)}>Ocultar</button></div>}
 </div>
}
