'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { supabase } from '@/lib/supabase'

type Driver={id:string;online:boolean;status:string;city_id:string|null}
type Location={driver_id:string;lat:number;lng:number;heading:number|null;speed_kmh:number|null;updated_at:string}
type Place={id:string;name:string;address:string;phone:string;lat:number;lng:number;type:string;googleMapsUri:string}
type Center={lat:number;lng:number;label:string}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',borderRadius:10,padding:'10px 14px',fontWeight:800,textDecoration:'none'}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:18}

declare global { interface Window { google:any } }

export default function MapaPage(){
 const ref=useRef<HTMLDivElement|null>(null);const placeCache=useRef({key:'',at:0});
 const [drivers,setDrivers]=useState<Driver[]>([]),[locs,setLocs]=useState<Location[]>([]),[places,setPlaces]=useState<Place[]>([]),[centerHint,setCenterHint]=useState<Center|null>(null),[msg,setMsg]=useState(''),[loaded,setLoaded]=useState(false)
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[])
 useEffect(()=>{renderMap()},[drivers,locs,places,centerHint,loaded])
 async function loadPlaces(lat:number,lng:number){
  const key=`${lat.toFixed(2)}:${lng.toFixed(2)}`;const now=Date.now();if(placeCache.current.key===key&&now-placeCache.current.at<300000)return
  placeCache.current={key,at:now}
  try{const r=await fetch(`/api/google-places?lat=${encodeURIComponent(lat)}&lng=${encodeURIComponent(lng)}&radius=2500`,{cache:'no-store'});const j=await r.json();if(r.ok&&Array.isArray(j.places))setPlaces(j.places)}catch{/* O mapa continua funcionando mesmo se o Places estiver indisponível. */}
 }
 async function load(){try{
  const {data:{user}}=await supabase.auth.getUser();if(!user)return setMsg('Faça login.')
  const {data:p}=await supabase.from('profiles').select('role,franchise_id').eq('id',user.id).single();if(!p||p.role!=='franchise_admin'||!p.franchise_id)return setMsg('Acesso exclusivo do franqueado.')
  const [{data:d},{data:fc}]=await Promise.all([
   supabase.from('drivers').select('id,online,status,city_id').eq('franchise_id',p.franchise_id),
   supabase.from('franchise_cities').select('cities(name,state,center_lat,center_lng)').eq('franchise_id',p.franchise_id).limit(1)
  ])
  const city:any=(fc||[])[0]?.cities;if(city&&Number.isFinite(Number(city.center_lat))&&Number.isFinite(Number(city.center_lng))){const c={lat:Number(city.center_lat),lng:Number(city.center_lng),label:`${city.name}/${city.state}`};setCenterHint(c)}
  const ids=(d||[]).map((x:any)=>x.id);setDrivers((d||[]) as Driver[])
  if(ids.length){const {data:l}=await supabase.from('driver_locations').select('*').in('driver_id',ids).order('updated_at',{ascending:false});const rows=(l||[]) as Location[];setLocs(rows);if(rows[0])loadPlaces(rows[0].lat,rows[0].lng);else if(city?.center_lat&&city?.center_lng)loadPlaces(Number(city.center_lat),Number(city.center_lng))}
  else{setLocs([]);if(city?.center_lat&&city?.center_lng)loadPlaces(Number(city.center_lat),Number(city.center_lng))}
 }catch(e:any){setMsg(e.message)}}
 useEffect(()=>{const key=process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;if(!key){setMsg('Mapa preparado. Falta configurar NEXT_PUBLIC_GOOGLE_MAPS_API_KEY na Vercel.');return}if(window.google?.maps){setLoaded(true);return}const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${key}&language=pt-BR&region=BR`;s.async=true;s.onload=()=>setLoaded(true);s.onerror=()=>setMsg('Não foi possível carregar o Google Maps.');document.head.appendChild(s);return()=>{s.onload=null}},[])
 function placeInfo(p:Place){const root=document.createElement('div');root.style.maxWidth='260px';const title=document.createElement('strong');title.textContent=p.name;root.appendChild(title);if(p.type){const t=document.createElement('div');t.textContent=p.type;t.style.fontSize='12px';t.style.color='#555';root.appendChild(t)}if(p.address){const a=document.createElement('div');a.textContent=p.address;a.style.marginTop='6px';root.appendChild(a)}const phone=document.createElement('div');phone.style.marginTop='8px';if(p.phone){const link=document.createElement('a');link.href=`tel:${p.phone.replace(/[^+\d]/g,'')}`;link.textContent=`📞 ${p.phone}`;link.style.fontWeight='700';phone.appendChild(link)}else phone.textContent='Telefone não informado no Google';root.appendChild(phone);if(p.googleMapsUri){const maps=document.createElement('a');maps.href=p.googleMapsUri;maps.target='_blank';maps.rel='noopener noreferrer';maps.textContent='Abrir no Google Maps';maps.style.display='block';maps.style.marginTop='8px';root.appendChild(maps)}return root}
 function renderMap(){if(!loaded||!ref.current||!window.google?.maps)return;const valid=locs.filter(l=>drivers.some(d=>d.id===l.driver_id));const center=valid[0]?{lat:valid[0].lat,lng:valid[0].lng}:centerHint?{lat:centerHint.lat,lng:centerHint.lng}:{lat:-15.7801,lng:-47.9292};const g=window.google.maps;const map=new g.Map(ref.current,{center,zoom:valid.length||centerHint?13:5,mapTypeId:'roadmap',mapTypeControl:true,mapTypeControlOptions:{style:g.MapTypeControlStyle.HORIZONTAL_BAR,position:g.ControlPosition.TOP_RIGHT,mapTypeIds:['roadmap','hybrid','satellite']},streetViewControl:false,fullscreenControl:true});valid.forEach(l=>{const d=drivers.find(x=>x.id===l.driver_id);new g.Marker({position:{lat:l.lat,lng:l.lng},map,title:`Motorista ${l.driver_id.slice(0,8)} · ${d?.online?'online':'offline'}`})});places.forEach(p=>{const marker=new g.Marker({position:{lat:Number(p.lat),lng:Number(p.lng)},map,title:p.phone?`${p.name} · ${p.phone}`:p.name,icon:{path:g.SymbolPath.CIRCLE,scale:7,fillColor:'#ffd400',fillOpacity:1,strokeColor:'#111',strokeWeight:2}});const info=new g.InfoWindow({content:placeInfo(p)});marker.addListener('click',()=>info.open({map,anchor:marker}))});map.addListener('idle',()=>{const c=map.getCenter();if(c)loadPlaces(c.lat(),c.lng())})}
 const active=drivers.filter(d=>d.online&&d.status==='approved').length
 return <main style={{minHeight:'100vh',background:'#080808',color:'#fff',padding:24}}><div style={{maxWidth:1400,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'}}><div><div style={{color:'#ffd400',fontWeight:900}}>CLICK-GO</div><h1>Mapa operacional</h1><div style={{color:'#9ca3af'}}>Atualização de motoristas a cada 15 segundos · empresas do Google com telefone · Rua, Satélite e Híbrido</div><div style={{color:'#fde68a',fontSize:12,marginTop:5}}>Para ver satélite mantendo nomes de cidades, bairros e vias, escolha <b>Híbrido</b> no controle do mapa.</div></div><Link href="/franqueado/operacao" style={btn}>Central operacional</Link></div>{msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b',margin:'15px 0'}}>{msg}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 350px',gap:16,marginTop:16}}><div ref={ref} style={{height:650,borderRadius:16,background:'#1a1a1a',border:'1px solid #292929'}}/><aside style={{...box,maxHeight:650,overflow:'auto'}}><h2>Motoristas</h2><div style={{fontSize:28,fontWeight:900,color:'#ffd400'}}>{active} online</div><div style={{display:'grid',gap:8,marginTop:15}}>{locs.filter(l=>drivers.some(d=>d.id===l.driver_id)).map(l=>{const d=drivers.find(x=>x.id===l.driver_id);return <div key={l.driver_id} style={{...box,padding:11}}><b>{l.driver_id.slice(0,8)}</b><div style={{color:d?.online?'#86efac':'#9ca3af'}}>{d?.online?'● Online':'● Offline'}</div><div style={{fontSize:12,color:'#9ca3af'}}>{l.lat.toFixed(5)}, {l.lng.toFixed(5)} · {Number(l.speed_kmh||0).toFixed(0)} km/h</div><a href={`https://www.google.com/maps?q=${l.lat},${l.lng}`} target="_blank" rel="noreferrer" style={{color:'#ffd400',fontSize:12}}>Abrir localização</a></div>})}</div><h2 style={{marginTop:22}}>Empresas próximas</h2><div style={{color:'#9ca3af',fontSize:12,marginBottom:10}}>Dados cadastrados no Google. Clique no ponto amarelo do mapa para detalhes.</div><div style={{display:'grid',gap:8}}>{places.map(p=><div key={p.id} style={{...box,padding:11}}><b>{p.name}</b>{p.type&&<div style={{fontSize:12,color:'#9ca3af'}}>{p.type}</div>}<div style={{fontSize:12,color:'#d1d5db',marginTop:4}}>{p.address}</div>{p.phone?<a href={`tel:${p.phone.replace(/[^+\d]/g,'')}`} style={{color:'#ffd400',fontWeight:800,display:'block',marginTop:6}}>📞 {p.phone}</a>:<div style={{fontSize:12,color:'#6b7280',marginTop:6}}>Telefone não informado no Google</div>}</div>)}{!places.length&&<div style={{color:'#9ca3af'}}>Nenhuma empresa carregada nesta área.</div>}</div></aside></div></div></main>
}
