import { NextRequest, NextResponse } from 'next/server'
import { getMapboxAccessToken } from '@/lib/map-provider-config'

export const dynamic='force-dynamic'

type Pt={lat:number;lng:number}
type RouteResult={provider:string;coordinates:[number,number][];distance_m:number;duration_s:number;degraded?:boolean}
function num(v:string|null,min:number,max:number){const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function haversine(a:Pt,b:Pt){const r=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function decodePolyline(encoded:string):[number,number][]{const coords:[number,number][]=[];let index=0,lat=0,lng=0;while(index<encoded.length){let result=0,shift=0,b:number;do{b=encoded.charCodeAt(index++)-63;result|=(b&0x1f)<<shift;shift+=5}while(b>=0x20);lat+=(result&1)?~(result>>1):(result>>1);result=0;shift=0;do{b=encoded.charCodeAt(index++)-63;result|=(b&0x1f)<<shift;shift+=5}while(b>=0x20);lng+=(result&1)?~(result>>1):(result>>1);coords.push([lat/1e5,lng/1e5])}return coords}
async function mapboxRoute(a:Pt,b:Pt):Promise<RouteResult|null>{const token=await getMapboxAccessToken();if(!token)return null;const url=new URL(`https://api.mapbox.com/directions/v5/mapbox/driving/${a.lng},${a.lat};${b.lng},${b.lat}`);url.searchParams.set('access_token',token);url.searchParams.set('geometries','geojson');url.searchParams.set('overview','full');url.searchParams.set('steps','false');const res=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(7000)});if(!res.ok)return null;const json=await res.json() as any;const r=json?.routes?.[0];const c=r?.geometry?.coordinates;if(!Array.isArray(c)||c.length<2)return null;return{provider:'mapbox',coordinates:c.map((p:any)=>[Number(p[1]),Number(p[0])] as [number,number]),distance_m:Number(r.distance||0),duration_s:Number(r.duration||0)}}
async function googleRoute(a:Pt,b:Pt):Promise<RouteResult|null>{const key=process.env.GOOGLE_MAPS_SERVER_API_KEY||process.env.GOOGLE_PLACES_API_KEY;if(!key)return null;const res=await fetch('https://routes.googleapis.com/directions/v2:computeRoutes',{method:'POST',cache:'no-store',signal:AbortSignal.timeout(7000),headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,'X-Goog-FieldMask':'routes.distanceMeters,routes.duration,routes.polyline.encodedPolyline'},body:JSON.stringify({origin:{location:{latLng:{latitude:a.lat,longitude:a.lng}}},destination:{location:{latLng:{latitude:b.lat,longitude:b.lng}}},travelMode:'DRIVE',routingPreference:'TRAFFIC_UNAWARE',languageCode:'pt-BR',units:'METRIC'})});if(!res.ok)return null;const json=await res.json() as any;const r=json?.routes?.[0];const enc=r?.polyline?.encodedPolyline;if(!enc)return null;const duration=String(r.duration||'0s').replace('s','');return{provider:'google',coordinates:decodePolyline(enc),distance_m:Number(r.distanceMeters||0),duration_s:Number(duration||0)}}
export async function GET(req:NextRequest){const a={lat:num(req.nextUrl.searchParams.get('origin_lat'),-90,90),lng:num(req.nextUrl.searchParams.get('origin_lng'),-180,180)};const b={lat:num(req.nextUrl.searchParams.get('destination_lat'),-90,90),lng:num(req.nextUrl.searchParams.get('destination_lng'),-180,180)};if(a.lat===null||a.lng===null||b.lat===null||b.lng===null)return NextResponse.json({error:'Coordenadas inválidas.'},{status:400});const origin={lat:a.lat,lng:a.lng},destination={lat:b.lat,lng:b.lng};const preferred=(req.nextUrl.searchParams.get('provider')||'auto').toLowerCase();try{const order=preferred==='google'?['google','mapbox']:['mapbox','google'];for(const provider of order){try{const result=provider==='mapbox'?await mapboxRoute(origin,destination):await googleRoute(origin,destination);if(result)return NextResponse.json(result)}catch{}}const distance=haversine(origin,destination);return NextResponse.json({provider:'fallback',coordinates:[[origin.lat,origin.lng],[destination.lat,destination.lng]],distance_m:distance,duration_s:Math.max(120,distance/8.5),degraded:true} satisfies RouteResult)}catch{return NextResponse.json({error:'Não foi possível calcular a rota.'},{status:502})}}
