'use client'

import Link from 'next/link'
import {useEffect,useState} from 'react'
import {ArrowDownLeft,ArrowLeft,ArrowUpRight,Banknote,CheckCircle2,CreditCard,Home,Navigation,QrCode,RefreshCw,UserRound,WalletCards} from 'lucide-react'
import {supabase} from '@/lib/supabase'

type Summary={operational_balance:number|string;earnings_balance:number|string;minimum_balance:number|string;low_balance_threshold:number|string;ride_fee:number|string;ride_fee_mode?:'fixed'|'percentage';ride_fee_percentage?:number|string;operational_enabled:boolean;billing_mode:'wallet_per_ride'|'monthly';monthly_fee:number|string;monthly_due_day:number;monthly_paid_until:string|null}
type Tx={id:string;transaction_type:string;source:string;amount:number|string;reason:string|null;created_at:string}
type Pix={txid:string;qrcode:string|null;qrcode_image:string|null;amount:number|string;expires_at:string|null;status:string;purpose?:string}
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export default function DriverWalletPage(){
 const[summary,setSummary]=useState<Summary|null>(null),[txs,setTxs]=useState<Tx[]>([]),[amount,setAmount]=useState('30'),[pix,setPix]=useState<Pix|null>(null),[machine,setMachine]=useState(false),[machineApproved,setMachineApproved]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{load()},[])
 async function load(){setBusy(true);setMsg('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Faça login como motorista.');const[{data:s,error:se},{data:t,error:te},{data:d,error:de}]=await Promise.all([supabase.rpc('get_my_driver_wallet_summary'),supabase.from('driver_operational_transactions').select('id,transaction_type,source,amount,reason,created_at').eq('driver_id',user.id).order('created_at',{ascending:false}).limit(50),supabase.from('drivers').select('has_card_machine,card_machine_approved').eq('id',user.id).single()]);if(se)throw se;if(te)throw te;if(de)throw de;setSummary((s?.[0]||null) as Summary|null);setTxs((t||[]) as Tx[]);setMachine(!!d?.has_card_machine);setMachineApproved(!!d?.card_machine_approved)}catch(e:any){setMsg(e.message||'Erro ao carregar carteira.')}finally{setBusy(false)}}
 async function createPix(){setBusy(true);setMsg('Gerando PIX...');const body=summary?.billing_mode==='monthly'?{action:'create_driver_monthly_fee'}:{action:'create_driver_recharge',amount:Number(amount.replace(',','.'))};if(summary?.billing_mode!=='monthly'&&(!Number.isFinite((body as any).amount)||(body as any).amount<5)){setBusy(false);setMsg('Informe uma recarga a partir de R$ 5,00.');return}const{data,error}=await supabase.functions.invoke('efi-pix',{body});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Erro ao gerar PIX.');return}setPix(data as Pix);setMsg(summary?.billing_mode==='monthly'?'PIX da mensalidade gerado.':'PIX de recarga gerado. Após pagar, confirme o pagamento.')}
 async function checkPix(){if(!pix)return;setBusy(true);const{data,error}=await supabase.functions.invoke('efi-pix',{body:{action:'status',txid:pix.txid}});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Erro ao consultar PIX.');return}setPix(data as Pix);if(data?.status==='paid'){setMsg(summary?.billing_mode==='monthly'?'Mensalidade confirmada.':'Pagamento confirmado. Saldo operacional atualizado.');await load()}else setMsg('Pagamento ainda não confirmado pela Efí.')}
 async function saveMachine(next:boolean){setBusy(true);const{error}=await supabase.rpc('set_my_card_machine',{p_has_machine:next});setBusy(false);if(error){setMsg(error.message);return}setMachine(next);if(!next)setMachineApproved(false);setMsg(next?'Informação salva. O franqueado precisa autorizar sua maquininha.':'Maquininha removida do seu cadastro.')}
 const isMonthly=summary?.billing_mode==='monthly',low=!isMonthly&&summary?.operational_enabled&&Number(summary.operational_balance)<=Number(summary.low_balance_threshold),monthlyOk=!!(isMonthly&&summary?.monthly_paid_until&&new Date(summary.monthly_paid_until+'T12:00:00')>=new Date())
 const feeLabel=summary?.ride_fee_mode==='percentage'?`${Number(summary?.ride_fee_percentage||0).toLocaleString('pt-BR')}% por corrida`:`${money(summary?.ride_fee)} por corrida`

 return <main className="mobile-app"><div className="mobile-app-frame" style={{maxWidth:900}}>
  <header className="mobile-app-top"><Link className="mobile-round" href="/motorista-app" aria-label="Voltar"><ArrowLeft size={19}/></Link><div className="mobile-brand"><div className="mobile-logo">CG</div><div><strong>Ganhos e carteira</strong><span>CLICK-GO Motorista</span></div></div><button className="mobile-round" onClick={load} disabled={busy} aria-label="Atualizar"><RefreshCw size={18}/></button></header>
  <div className="mobile-body">
   <section className="mobile-hero"><div className="overline">Financeiro</div><h1>{isMonthly?'Seu plano mensal':'Seu saldo de operação'}</h1><p>{isMonthly?'Mantenha a mensalidade em dia para continuar recebendo chamadas.':'Este saldo libera chamadas e cobre a taxa configurada por corrida.'}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:16,position:'relative',zIndex:1}}><div><div style={{fontSize:11,color:'#aaa'}}>Saldo operacional</div><div style={{fontSize:25,fontWeight:900,marginTop:3}}>{money(summary?.operational_balance)}</div></div><div><div style={{fontSize:11,color:'#aaa'}}>Meus ganhos</div><div style={{fontSize:25,fontWeight:900,marginTop:3}}>{money(summary?.earnings_balance)}</div></div></div></section>

   <section className="mobile-section"><div className="mobile-section-head"><h2>Como sua cobrança funciona</h2><span>Definido pela franquia</span></div><div className="mobile-card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:12}}><div><span className={`mobile-status ${isMonthly?(monthlyOk?'good':'warn'):(low?'warn':'good')}`}>{isMonthly?(monthlyOk?'Mensalidade em dia':'Mensalidade pendente'):(low?'Saldo baixo':'Liberado para chamadas')}</span><div style={{fontSize:21,fontWeight:900,marginTop:12}}>{isMonthly?money(summary?.monthly_fee):feeLabel}</div><div className="caption" style={{marginTop:5}}>{isMonthly?`Vencimento dia ${summary?.monthly_due_day}${summary?.monthly_paid_until?` · pago até ${new Date(summary.monthly_paid_until+'T12:00:00').toLocaleDateString('pt-BR')}`:''}`:`Saldo mínimo para receber chamadas: ${money(summary?.minimum_balance)}`}</div></div><WalletCards size={26}/></div></div></section>

   <section className="mobile-section"><div className="mobile-section-head"><h2>{isMonthly?'Pagar mensalidade':'Recarregar saldo'}</h2><span>PIX Efí</span></div><div className="mobile-content-panel"><div style={{display:'flex',gap:12,alignItems:'center'}}><div style={{width:46,height:46,borderRadius:14,background:'#111',color:'#ffd400',display:'grid',placeItems:'center'}}><QrCode size={23}/></div><div><b>{isMonthly?'Mensalidade via PIX':'Recarga automática via PIX'}</b><div className="mobile-muted">{isMonthly?'O valor é definido pela sua franquia.':'O saldo entra após a confirmação do pagamento.'}</div></div></div>{!isMonthly&&<div style={{marginTop:14}}><label style={{display:'block',fontSize:11,fontWeight:800,color:'#777',marginBottom:6}}>VALOR DA RECARGA</label><input className="mobile-input" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Ex.: 30,00"/></div>}<button className="mobile-primary" style={{width:'100%',marginTop:12}} disabled={busy} onClick={createPix}>{isMonthly?`Gerar PIX de ${money(summary?.monthly_fee)}`:'Gerar PIX da recarga'}</button>{pix&&<div className="mobile-card" style={{marginTop:14,background:'#f8f8fa'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b>{money(pix.amount)}</b><span className={`mobile-status ${pix.status==='paid'?'good':'warn'}`}>{pix.status==='paid'?'Pago':'Aguardando pagamento'}</span></div>{pix.qrcode_image&&<img src={pix.qrcode_image} alt="QR Code PIX" style={{maxWidth:230,width:'100%',display:'block',margin:'14px auto 0',background:'#fff',padding:8,borderRadius:14}}/>}{pix.qrcode&&<><textarea readOnly value={pix.qrcode} className="mobile-input" style={{height:88,paddingTop:12,marginTop:10,resize:'none'}}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:8}}><button className="mobile-secondary" onClick={()=>navigator.clipboard?.writeText(pix.qrcode||'')}>Copiar código</button><button className="mobile-primary" disabled={busy} onClick={checkPix}>Confirmar pagamento</button></div></>}</div>}</div></section>

   <section className="mobile-section"><div className="mobile-section-head"><h2>Maquininha</h2><span>Recebimento direto</span></div><div className="mobile-card"><div style={{display:'flex',gap:12,alignItems:'center'}}><CreditCard size={23}/><div style={{flex:1}}><b>Maquininha própria</b><div className="caption">Você só recebe chamadas nessa modalidade após autorização do franqueado.</div></div><label style={{display:'flex',alignItems:'center',gap:7,fontSize:12,fontWeight:800}}><input type="checkbox" checked={machine} onChange={e=>saveMachine(e.target.checked)} disabled={busy}/> Possuo</label></div>{machine&&<div style={{marginTop:11}}><span className={`mobile-status ${machineApproved?'good':'warn'}`}>{machineApproved?<><CheckCircle2 size={13}/>Autorizada</>:<>Aguardando autorização</>}</span></div>}</div></section>

   {!isMonthly&&<section className="mobile-section"><div className="mobile-section-head"><h2>Extrato operacional</h2><span>{txs.length} movimentações</span></div><div style={{display:'grid',gap:8}}>{txs.map(t=><div className="mobile-card" key={t.id} style={{display:'flex',alignItems:'center',gap:11}}><div style={{width:38,height:38,borderRadius:12,display:'grid',placeItems:'center',background:t.transaction_type==='credit'?'#ecfdf3':'#fff0f0',color:t.transaction_type==='credit'?'#16743a':'#a62d2d'}}>{t.transaction_type==='credit'?<ArrowDownLeft size={19}/>:<ArrowUpRight size={19}/>}</div><div style={{flex:1,minWidth:0}}><b style={{display:'block',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{t.reason||t.source}</b><div className="caption">{new Date(t.created_at).toLocaleString('pt-BR')} · {t.source}</div></div><b style={{color:t.transaction_type==='credit'?'#16743a':'#a62d2d'}}>{t.transaction_type==='credit'?'+':'-'} {money(t.amount)}</b></div>)}{!txs.length&&<div className="mobile-content-panel"><Banknote size={23}/><p className="mobile-muted" style={{marginBottom:0}}>Nenhuma movimentação operacional ainda.</p></div>}</div></section>}
   {msg&&<div className="mobile-alert">{msg}</div>}
  </div>
  <nav className="mobile-bottom-nav"><Link className="mobile-nav-item" href="/motorista-app"><Home size={20}/><span>Início</span><i className="nav-dot"/></Link><Link className="mobile-nav-item" href="/motorista-app/operacao"><Navigation size={20}/><span>Corridas</span><i className="nav-dot"/></Link><Link className="mobile-nav-item active" href="/motorista-app/carteira"><WalletCards size={20}/><span>Ganhos</span><i className="nav-dot"/></Link><Link className="mobile-nav-item" href="/motorista-app"><UserRound size={20}/><span>Perfil</span><i className="nav-dot"/></Link></nav>
 </div></main>
}
