'use client'

import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Summary={operational_balance:number|string;earnings_balance:number|string;minimum_balance:number|string;low_balance_threshold:number|string;ride_fee:number|string;operational_enabled:boolean}
type Tx={id:string;transaction_type:string;source:string;amount:number|string;reason:string|null;created_at:string}
type Pix={txid:string;qrcode:string|null;qrcode_image:string|null;amount:number|string;expires_at:string|null;status:string}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:18}
const input:React.CSSProperties={width:'100%',background:'#0d0d0d',color:'#fff',border:'1px solid #333',borderRadius:10,padding:'11px 12px'}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',border:0,borderRadius:10,padding:'11px 14px',fontWeight:800,cursor:'pointer'}
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export default function DriverWalletPage(){
 const[summary,setSummary]=useState<Summary|null>(null),[txs,setTxs]=useState<Tx[]>([]),[amount,setAmount]=useState('30'),[pix,setPix]=useState<Pix|null>(null),[machine,setMachine]=useState(false),[machineApproved,setMachineApproved]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{load()},[])
 async function load(){setBusy(true);setMsg('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Faça login como motorista.');const[{data:s,error:se},{data:t,error:te},{data:d,error:de}]=await Promise.all([supabase.rpc('get_my_driver_wallet_summary'),supabase.from('driver_operational_transactions').select('id,transaction_type,source,amount,reason,created_at').eq('driver_id',user.id).order('created_at',{ascending:false}).limit(50),supabase.from('drivers').select('has_card_machine,card_machine_approved').eq('id',user.id).single()]);if(se)throw se;if(te)throw te;if(de)throw de;setSummary((s?.[0]||null) as Summary|null);setTxs((t||[]) as Tx[]);setMachine(!!d?.has_card_machine);setMachineApproved(!!d?.card_machine_approved)}catch(e:any){setMsg(e.message||'Erro ao carregar carteira.')}finally{setBusy(false)}}
 async function createPix(){const n=Number(amount.replace(',','.'));if(!Number.isFinite(n)||n<5){setMsg('Informe uma recarga a partir de R$ 5,00.');return}setBusy(true);setMsg('Gerando PIX...');const{data,error}=await supabase.functions.invoke('efi-pix',{body:{action:'create_driver_recharge',amount:n}});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Erro ao gerar PIX.');return}setPix(data as Pix);setMsg('PIX gerado. Após o pagamento, clique em Verificar pagamento.')}
 async function checkPix(){if(!pix)return;setBusy(true);const{data,error}=await supabase.functions.invoke('efi-pix',{body:{action:'status',txid:pix.txid}});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Erro ao consultar PIX.');return}setPix(data as Pix);if(data?.status==='paid'){setMsg('Pagamento confirmado. Saldo operacional atualizado.');await load()}else setMsg('Pagamento ainda não confirmado pela Efí.')}
 async function saveMachine(next:boolean){setBusy(true);const{error}=await supabase.rpc('set_my_card_machine',{p_has_machine:next});setBusy(false);if(error){setMsg(error.message);return}setMachine(next);if(!next)setMachineApproved(false);setMsg(next?'Informação salva. O franqueado precisa autorizar sua maquininha.':'Maquininha removida do seu cadastro.')}
 const low=summary&&summary.operational_enabled&&Number(summary.operational_balance)<=Number(summary.low_balance_threshold)
 return <main style={{minHeight:'calc(100vh - 60px)',background:'#080808',color:'#fff',padding:20}}><div style={{maxWidth:1100,margin:'0 auto',display:'grid',gap:14}}>
  <div><div className="eyebrow">Carteira do motorista</div><h1>Créditos e ganhos separados</h1><p className="subtitle">O saldo operacional libera chamadas; os ganhos são valores de corridas pagas digitalmente.</p></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}><div style={{...box,borderColor:low?'#a16207':'#292929'}}><div className="label">Saldo operacional</div><div className="metric">{money(summary?.operational_balance)}</div><div style={{color:'#9ca3af',marginTop:8}}>Mínimo para receber: {money(summary?.minimum_balance)} · alerta: {money(summary?.low_balance_threshold)}</div>{summary?.operational_enabled&&<div style={{marginTop:6,color:low?'#fde68a':'#86efac'}}>{low?'Saldo baixo: faça uma recarga para evitar bloqueio de chamadas.':'Saldo suficiente para operar.'}</div>}</div><div style={box}><div className="label">Meus ganhos</div><div className="metric">{money(summary?.earnings_balance)}</div><div style={{color:'#9ca3af',marginTop:8}}>Taxa operacional por corrida: {money(summary?.ride_fee)}</div></div></div>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><section style={box}><h2>Recarregar via PIX</h2><p className="subtitle">O crédito entra automaticamente após confirmação da Efí.</p><div style={{display:'flex',gap:8}}><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" style={input} placeholder="Valor da recarga"/><button disabled={busy} style={btn} onClick={createPix}>Gerar PIX</button></div>{pix&&<div style={{marginTop:14,display:'grid',gap:10}}><div><b>{money(pix.amount)}</b> · status {pix.status}</div>{pix.qrcode_image&&<img src={pix.qrcode_image} alt="QR Code PIX" style={{maxWidth:260,width:'100%',background:'#fff',padding:8,borderRadius:12}}/>}{pix.qrcode&&<><textarea readOnly value={pix.qrcode} style={{...input,minHeight:90}}/><div style={{display:'flex',gap:8}}><button style={{...btn,background:'#222',color:'#fff'}} onClick={()=>navigator.clipboard?.writeText(pix.qrcode||'')}>Copiar PIX</button><button style={btn} disabled={busy} onClick={checkPix}>Verificar pagamento</button></div></>}</div>}</section><section style={box}><h2>Maquininha</h2><p className="subtitle">Informe se você possui maquininha própria. O franqueado precisa autorizar antes de receber corridas com essa forma de pagamento.</p><label style={{display:'flex',gap:10,alignItems:'center',marginTop:16}}><input type="checkbox" checked={machine} onChange={e=>saveMachine(e.target.checked)} disabled={busy}/><b>Eu possuo maquininha de cartão</b></label><div style={{marginTop:12,color:machineApproved?'#86efac':'#fbbf24'}}>Autorização do franqueado: <b>{machineApproved?'APROVADA':'PENDENTE / NÃO AUTORIZADA'}</b></div></section></div>
  <section style={box}><h2>Extrato operacional</h2><div style={{display:'grid',gap:8}}>{txs.map(t=><div key={t.id} style={{display:'grid',gridTemplateColumns:'100px 1fr 130px',gap:12,padding:'11px 0',borderBottom:'1px solid #262626'}}><b style={{color:t.transaction_type==='credit'?'#86efac':'#fca5a5'}}>{t.transaction_type==='credit'?'+':'-'} {money(t.amount)}</b><div>{t.reason||t.source}<div style={{fontSize:12,color:'#6b7280'}}>{t.source}</div></div><div style={{textAlign:'right',color:'#9ca3af',fontSize:13}}>{new Date(t.created_at).toLocaleString('pt-BR')}</div></div>)}{!txs.length&&<div style={{color:'#9ca3af'}}>Nenhuma movimentação ainda.</div>}</div></section>
  {msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b'}}>{msg}</div>}
 </div></main>
}
