'use client'

import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Summary={operational_balance:number|string;earnings_balance:number|string;minimum_balance:number|string;low_balance_threshold:number|string;ride_fee:number|string;operational_enabled:boolean;billing_mode:'wallet_per_ride'|'monthly';monthly_fee:number|string;monthly_due_day:number;monthly_paid_until:string|null}
type Tx={id:string;transaction_type:string;source:string;amount:number|string;reason:string|null;created_at:string}
type Pix={txid:string;qrcode:string|null;qrcode_image:string|null;amount:number|string;expires_at:string|null;status:string;purpose?:string}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:18}
const input:React.CSSProperties={width:'100%',background:'#0d0d0d',color:'#fff',border:'1px solid #333',borderRadius:10,padding:'11px 12px'}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',border:0,borderRadius:10,padding:'11px 14px',fontWeight:800,cursor:'pointer'}
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export default function DriverWalletPage(){
 const[summary,setSummary]=useState<Summary|null>(null),[txs,setTxs]=useState<Tx[]>([]),[amount,setAmount]=useState('30'),[pix,setPix]=useState<Pix|null>(null),[machine,setMachine]=useState(false),[machineApproved,setMachineApproved]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{load()},[])
 async function load(){setBusy(true);setMsg('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Faça login como motorista.');const[{data:s,error:se},{data:t,error:te},{data:d,error:de}]=await Promise.all([supabase.rpc('get_my_driver_wallet_summary'),supabase.from('driver_operational_transactions').select('id,transaction_type,source,amount,reason,created_at').eq('driver_id',user.id).order('created_at',{ascending:false}).limit(50),supabase.from('drivers').select('has_card_machine,card_machine_approved').eq('id',user.id).single()]);if(se)throw se;if(te)throw te;if(de)throw de;setSummary((s?.[0]||null) as Summary|null);setTxs((t||[]) as Tx[]);setMachine(!!d?.has_card_machine);setMachineApproved(!!d?.card_machine_approved)}catch(e:any){setMsg(e.message||'Erro ao carregar carteira.')}finally{setBusy(false)}}
 async function createPix(){setBusy(true);setMsg('Gerando PIX...');const body=summary?.billing_mode==='monthly'?{action:'create_driver_monthly_fee'}:{action:'create_driver_recharge',amount:Number(amount.replace(',','.'))};if(summary?.billing_mode!=='monthly'&&(!Number.isFinite((body as any).amount)||(body as any).amount<5)){setBusy(false);setMsg('Informe uma recarga a partir de R$ 5,00.');return}const{data,error}=await supabase.functions.invoke('efi-pix',{body});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Erro ao gerar PIX.');return}setPix(data as Pix);setMsg(summary?.billing_mode==='monthly'?'PIX da mensalidade gerado. O valor foi definido pelo franqueado.':'PIX de recarga gerado. Após pagar, clique em Verificar pagamento.')}
 async function checkPix(){if(!pix)return;setBusy(true);const{data,error}=await supabase.functions.invoke('efi-pix',{body:{action:'status',txid:pix.txid}});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Erro ao consultar PIX.');return}setPix(data as Pix);if(data?.status==='paid'){setMsg(summary?.billing_mode==='monthly'?'Mensalidade confirmada. Seu plano foi atualizado.':'Pagamento confirmado. Saldo operacional atualizado.');await load()}else setMsg('Pagamento ainda não confirmado pela Efí.')}
 async function saveMachine(next:boolean){setBusy(true);const{error}=await supabase.rpc('set_my_card_machine',{p_has_machine:next});setBusy(false);if(error){setMsg(error.message);return}setMachine(next);if(!next)setMachineApproved(false);setMsg(next?'Informação salva. O franqueado precisa autorizar sua maquininha.':'Maquininha removida do seu cadastro.')}
 const isMonthly=summary?.billing_mode==='monthly';const low=!isMonthly&&summary?.operational_enabled&&Number(summary.operational_balance)<=Number(summary.low_balance_threshold);const monthlyOk=isMonthly&&summary?.monthly_paid_until&&new Date(summary.monthly_paid_until+'T12:00:00')>=new Date()
 return <main style={{minHeight:'calc(100vh - 60px)',background:'#080808',color:'#fff',padding:20}}><div style={{maxWidth:1100,margin:'0 auto',display:'grid',gap:14}}>
  <div><div className="eyebrow">Financeiro do motorista</div><h1>{isMonthly?'Plano mensal':'Carteira por corrida'} + Meus Ganhos</h1><p className="subtitle">O franqueado define individualmente se você trabalha por mensalidade ou com desconto por corrida.</p></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}><div style={{...box,borderColor:isMonthly?(monthlyOk?'#166534':'#a16207'):(low?'#a16207':'#292929')}}>{isMonthly?<><div className="label">Mensalidade</div><div className="metric">{money(summary?.monthly_fee)}</div><div style={{color:'#9ca3af',marginTop:8}}>Vencimento configurado: dia {summary?.monthly_due_day}</div><div style={{marginTop:6,color:monthlyOk?'#86efac':'#fbbf24'}}>{summary?.monthly_paid_until?`Pago até ${new Date(summary.monthly_paid_until+'T12:00:00').toLocaleDateString('pt-BR')}`:'Mensalidade ainda não registrada como paga'}</div></>:<><div className="label">Saldo operacional</div><div className="metric">{money(summary?.operational_balance)}</div><div style={{color:'#9ca3af',marginTop:8}}>Desconto por corrida: {money(summary?.ride_fee)} · mínimo: {money(summary?.minimum_balance)}</div>{summary?.operational_enabled&&<div style={{marginTop:6,color:low?'#fde68a':'#86efac'}}>{low?'Saldo baixo: faça uma recarga para continuar recebendo chamadas.':'Saldo suficiente para operar.'}</div>}</>}</div><div style={box}><div className="label">Meus ganhos</div><div className="metric">{money(summary?.earnings_balance)}</div><div style={{color:'#9ca3af',marginTop:8}}>Valores de corridas pagas digitalmente, separados da cobrança do seu plano.</div></div></div>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><section style={box}><h2>{isMonthly?'Pagar mensalidade via PIX':'Recarregar carteira via PIX'}</h2><p className="subtitle">{isMonthly?'O valor da mensalidade é definido pelo franqueado e não pode ser alterado no app.':'O crédito entra automaticamente após confirmação da Efí.'}</p>{!isMonthly&&<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" style={input} placeholder="Valor da recarga"/>}<button disabled={busy} style={{...btn,marginTop:isMonthly?0:10}} onClick={createPix}>{isMonthly?`Gerar PIX de ${money(summary?.monthly_fee)}`:'Gerar PIX da recarga'}</button>{pix&&<div style={{marginTop:14,display:'grid',gap:10}}><div><b>{money(pix.amount)}</b> · status {pix.status}</div>{pix.qrcode_image&&<img src={pix.qrcode_image} alt="QR Code PIX" style={{maxWidth:260,width:'100%',background:'#fff',padding:8,borderRadius:12}}/>}{pix.qrcode&&<><textarea readOnly value={pix.qrcode} style={{...input,minHeight:90}}/><div style={{display:'flex',gap:8}}><button style={{...btn,background:'#222',color:'#fff'}} onClick={()=>navigator.clipboard?.writeText(pix.qrcode||'')}>Copiar PIX</button><button style={btn} disabled={busy} onClick={checkPix}>Verificar pagamento</button></div></>}</div>}</section><section style={box}><h2>Maquininha</h2><p className="subtitle">Informe se você possui maquininha própria. O franqueado precisa autorizar antes de receber chamadas com cartão na máquina.</p><label style={{display:'flex',gap:10,alignItems:'center',marginTop:16}}><input type="checkbox" checked={machine} onChange={e=>saveMachine(e.target.checked)} disabled={busy}/><b>Eu possuo maquininha de cartão</b></label><div style={{marginTop:12,color:machineApproved?'#86efac':'#fbbf24'}}>Autorização do franqueado: <b>{machineApproved?'APROVADA':'PENDENTE / NÃO AUTORIZADA'}</b></div></section></div>
  {!isMonthly&&<section style={box}><h2>Extrato operacional</h2><div style={{display:'grid',gap:8}}>{txs.map(t=><div key={t.id} style={{display:'grid',gridTemplateColumns:'100px 1fr 130px',gap:12,padding:'11px 0',borderBottom:'1px solid #262626'}}><b style={{color:t.transaction_type==='credit'?'#86efac':'#fca5a5'}}>{t.transaction_type==='credit'?'+':'-'} {money(t.amount)}</b><div>{t.reason||t.source}<div style={{fontSize:12,color:'#6b7280'}}>{t.source}</div></div><div style={{textAlign:'right',color:'#9ca3af',fontSize:13}}>{new Date(t.created_at).toLocaleString('pt-BR')}</div></div>)}{!txs.length&&<div style={{color:'#9ca3af'}}>Nenhuma movimentação ainda.</div>}</div></section>}
  {msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b'}}>{msg}</div>}
 </div></main>
}
