'use client'

import { useEffect,useMemo,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Driver={id:string;status:string;has_card_machine:boolean;card_machine_approved:boolean}
type Profile={id:string;full_name:string|null;email:string|null}
type Wallet={driver_id:string;balance:number|string}
type Tx={id:string;driver_id:string;transaction_type:string;source:string;amount:number|string;reason:string|null;created_at:string}
type Pix={txid:string;qrcode:string|null;qrcode_image:string|null;amount:number|string;status:string}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:18}
const input:React.CSSProperties={width:'100%',background:'#0d0d0d',color:'#fff',border:'1px solid #333',borderRadius:10,padding:'10px 11px'}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',border:0,borderRadius:9,padding:'10px 12px',fontWeight:800,cursor:'pointer'}
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export default function FranchiseWalletsPage(){
 const[drivers,setDrivers]=useState<Driver[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[wallets,setWallets]=useState<Wallet[]>([]),[txs,setTxs]=useState<Tx[]>([]),[selected,setSelected]=useState(''),[amount,setAmount]=useState('30'),[reason,setReason]=useState('Crédito operacional'),[pix,setPix]=useState<Pix|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>{load()},[])
 async function load(){setBusy(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Faça login.');const{data:p,error:pe}=await supabase.from('profiles').select('franchise_id,role').eq('id',user.id).single();if(pe)throw pe;if(!p?.franchise_id||p.role!=='franchise_admin')throw new Error('Acesso exclusivo do franqueado.');const{data:d,error:de}=await supabase.from('drivers').select('id,status,has_card_machine,card_machine_approved').eq('franchise_id',p.franchise_id).order('created_at',{ascending:false});if(de)throw de;const ids=(d||[]).map(x=>x.id);const[{data:pr,error:pre},{data:w,error:we},{data:t,error:te}]=await Promise.all([ids.length?supabase.from('profiles').select('id,full_name,email').in('id',ids):Promise.resolve({data:[],error:null} as any),supabase.from('driver_operational_wallets').select('driver_id,balance'),supabase.from('driver_operational_transactions').select('id,driver_id,transaction_type,source,amount,reason,created_at').order('created_at',{ascending:false}).limit(100)]);if(pre)throw pre;if(we)throw we;if(te)throw te;setDrivers((d||[]) as Driver[]);setProfiles((pr||[]) as Profile[]);setWallets((w||[]) as Wallet[]);setTxs((t||[]) as Tx[]);if(!selected&&ids[0])setSelected(ids[0])}catch(e:any){setMsg(e.message||'Erro ao carregar carteiras.')}finally{setBusy(false)}}
 const nameMap=useMemo(()=>Object.fromEntries(profiles.map(p=>[p.id,p])),[profiles]);
 function bal(id:string){return Number(wallets.find(w=>w.driver_id===id)?.balance||0)}
 async function adjust(sign:1|-1){if(!selected)return;const n=Number(amount.replace(',','.'));if(!Number.isFinite(n)||n<=0){setMsg('Informe um valor válido.');return}setBusy(true);const{data,error}=await supabase.rpc('adjust_driver_operational_balance',{p_driver_id:selected,p_amount:n*sign,p_reason:reason||'Ajuste operacional'});setBusy(false);if(error){setMsg(error.message);return}setMsg(`Novo saldo operacional: ${money(data)}`);await load()}
 async function generatePix(){if(!selected)return;const n=Number(amount.replace(',','.'));if(!Number.isFinite(n)||n<5){setMsg('PIX mínimo de R$ 5,00.');return}setBusy(true);const{data,error}=await supabase.functions.invoke('efi-pix',{body:{action:'create_driver_recharge',driver_id:selected,amount:n}});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Erro ao gerar PIX.');return}setPix(data as Pix);setMsg('Cobrança PIX gerada para a carteira operacional do motorista.')}
 async function checkPix(){if(!pix)return;setBusy(true);const{data,error}=await supabase.functions.invoke('efi-pix',{body:{action:'status',txid:pix.txid}});setBusy(false);if(error||data?.error){setMsg(data?.error||error?.message||'Erro ao verificar PIX.');return}setPix(data as Pix);if(data?.status==='paid'){setMsg('PIX confirmado e saldo creditado.');await load()}else setMsg('PIX ainda pendente.')}
 async function approveMachine(d:Driver){setBusy(true);const{error}=await supabase.rpc('set_driver_card_machine_approval',{p_driver_id:d.id,p_approved:!d.card_machine_approved});setBusy(false);if(error){setMsg(error.message);return}setMsg(!d.card_machine_approved?'Maquininha autorizada.':'Autorização da maquininha removida.');await load()}
 const current=drivers.find(d=>d.id===selected);const currentProfile=selected?nameMap[selected]:null;const currentTx=txs.filter(t=>t.driver_id===selected);
 return <main style={{minHeight:'100vh',background:'#080808',color:'#fff',padding:20}}><div style={{maxWidth:1200,margin:'0 auto',display:'grid',gap:14}}>
  <div><div className="eyebrow">Painel do franqueado</div><h1>Carteiras dos motoristas</h1><p className="subtitle">Adicione/retire créditos, gere PIX, veja extrato e autorize maquininha.</p></div>
  <div style={{display:'grid',gridTemplateColumns:'360px 1fr',gap:14}}><aside style={box}><h2>Motoristas</h2><div style={{display:'grid',gap:8,maxHeight:620,overflow:'auto'}}>{drivers.map(d=>{const p=nameMap[d.id];return <button key={d.id} onClick={()=>{setSelected(d.id);setPix(null)}} style={{...box,textAlign:'left',color:'#fff',cursor:'pointer',outline:selected===d.id?'2px solid #ffd400':'none'}}><b>{p?.full_name||p?.email||d.id.slice(0,8)}</b><div style={{color:'#9ca3af',fontSize:13,marginTop:4}}>{d.status} · saldo {money(bal(d.id))}</div>{d.has_card_machine&&<div style={{fontSize:12,color:d.card_machine_approved?'#86efac':'#fbbf24',marginTop:4}}>Maquininha: {d.card_machine_approved?'autorizada':'aguardando autorização'}</div>}</button>})}{!drivers.length&&<div style={{color:'#9ca3af'}}>Nenhum motorista cadastrado.</div>}</div></aside>
  <section style={{display:'grid',gap:14}}>{current?<><div style={box}><div className="label">Motorista selecionado</div><h2>{currentProfile?.full_name||currentProfile?.email||current.id}</h2><div className="metric">{money(bal(current.id))}</div><div style={{color:'#9ca3af'}}>Saldo operacional</div></div>
   <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><div style={box}><h3>Ajuste manual</h3><input style={input} value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Valor"/><input style={{...input,marginTop:8}} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo obrigatório"/><div style={{display:'flex',gap:8,marginTop:10}}><button style={btn} disabled={busy} onClick={()=>adjust(1)}>Adicionar crédito</button><button style={{...btn,background:'#3a1b1b',color:'#fff'}} disabled={busy} onClick={()=>adjust(-1)}>Retirar crédito</button></div></div><div style={box}><h3>Gerar cobrança PIX</h3><p className="subtitle">O PIX será creditado automaticamente após confirmação da Efí.</p><button style={btn} disabled={busy} onClick={generatePix}>Gerar PIX de {money(Number(amount.replace(',','.'))||0)}</button>{pix&&<div style={{display:'grid',gap:8,marginTop:12}}>{pix.qrcode_image&&<img src={pix.qrcode_image} alt="QR PIX" style={{maxWidth:220,background:'#fff',padding:7,borderRadius:10}}/>}{pix.qrcode&&<textarea readOnly value={pix.qrcode} style={{...input,minHeight:75}}/>}<div style={{display:'flex',gap:8}}>{pix.qrcode&&<button style={{...btn,background:'#222',color:'#fff'}} onClick={()=>navigator.clipboard?.writeText(pix.qrcode||'')}>Copiar PIX</button>}<button style={btn} onClick={checkPix}>Verificar pagamento</button></div></div>}</div></div>
   <div style={box}><h3>Maquininha do motorista</h3><div>Informou que possui: <b>{current.has_card_machine?'SIM':'NÃO'}</b></div><div style={{marginTop:6}}>Autorizada para receber corridas com cartão na máquina: <b>{current.card_machine_approved?'SIM':'NÃO'}</b></div><button style={{...btn,marginTop:10,background:current.card_machine_approved?'#3a1b1b':'#ffd400',color:current.card_machine_approved?'#fff':'#000'}} disabled={busy||(!current.has_card_machine&&!current.card_machine_approved)} onClick={()=>approveMachine(current)}>{current.card_machine_approved?'Revogar autorização':'Autorizar maquininha'}</button></div>
   <div style={box}><h3>Extrato</h3><div style={{display:'grid',gap:7}}>{currentTx.map(t=><div key={t.id} style={{display:'grid',gridTemplateColumns:'110px 1fr 150px',gap:10,borderBottom:'1px solid #262626',padding:'9px 0'}}><b style={{color:t.transaction_type==='credit'?'#86efac':'#fca5a5'}}>{t.transaction_type==='credit'?'+':'-'} {money(t.amount)}</b><div>{t.reason||t.source}</div><div style={{textAlign:'right',color:'#9ca3af',fontSize:13}}>{new Date(t.created_at).toLocaleString('pt-BR')}</div></div>)}{!currentTx.length&&<div style={{color:'#9ca3af'}}>Sem movimentações.</div>}</div></div></>:<div style={box}>Selecione um motorista.</div>}</section></div>
  {msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b'}}>{msg}</div>}
 </div></main>
}
