'use client'

import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Alert={
 id:string;ride_id:string;alert_type:'sos'|'route_deviation';severity:string;reporter_role:string;lat:number|null;lng:number|null;
 distance_from_route_m:number|null;message:string|null;status:'open'|'resolved';created_at:string;resolved_at:string|null;
 ride_status:string;origin_label:string;destination_label:string;passenger_name:string|null;driver_name:string|null;franchise_id:string|null;city_id:string|null
}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:16}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',border:0,borderRadius:10,padding:'10px 13px',fontWeight:900,cursor:'pointer'}

export default function AdminSafetyPage(){
 const[items,setItems]=useState<Alert[]>([]),[filter,setFilter]=useState<'open'|'all'>('open'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>{void load();const t=window.setInterval(load,10000);return()=>window.clearInterval(t)},[filter])
 async function load(){const{data,error}=await supabase.rpc('get_operation_safety_alerts',{p_status:filter,p_limit:500});if(error){setMsg(error.message);return}setItems(Array.isArray(data)?data as Alert[]:[])}
 async function resolve(id:string){if(!window.confirm('Marcar este alerta como atendido/resolvido pela matriz?'))return;setBusy(true);const{error}=await supabase.rpc('resolve_ride_safety_alert',{p_alert_id:id});setBusy(false);if(error){setMsg(error.message);return}setMsg('Alerta marcado como resolvido pela matriz.');await load()}
 const openCount=items.filter(x=>x.status==='open').length,sosCount=items.filter(x=>x.status==='open'&&x.alert_type==='sos').length,deviationCount=items.filter(x=>x.status==='open'&&x.alert_type==='route_deviation').length
 return <div><div className="topbar"><div><div className="eyebrow">Segurança da rede</div><h1 className="title">Central de Segurança CLICK-GO</h1><p className="subtitle">Visão da matriz sobre SOS e desvios de rota em todas as franquias.</p></div></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12,marginBottom:16}}><div style={box}><div style={{fontSize:12,color:'#9ca3af'}}>ALERTAS ABERTOS</div><div style={{fontSize:32,fontWeight:950,color:openCount?'#f87171':'#4ade80'}}>{openCount}</div></div><div style={box}><div style={{fontSize:12,color:'#9ca3af'}}>SOS ABERTOS</div><div style={{fontSize:32,fontWeight:950,color:sosCount?'#f87171':'#e5e7eb'}}>{sosCount}</div></div><div style={box}><div style={{fontSize:12,color:'#9ca3af'}}>DESVIOS ABERTOS</div><div style={{fontSize:32,fontWeight:950,color:deviationCount?'#fbbf24':'#e5e7eb'}}>{deviationCount}</div></div></div>
  <div style={{display:'flex',gap:8,marginBottom:16}}><button onClick={()=>setFilter('open')} style={{...btn,background:filter==='open'?'#ffd400':'#222',color:filter==='open'?'#000':'#fff'}}>Abertos</button><button onClick={()=>setFilter('all')} style={{...btn,background:filter==='all'?'#ffd400':'#222',color:filter==='all'?'#000':'#fff'}}>Todos</button><button onClick={()=>load()} style={{...btn,background:'#222',color:'#fff'}}>Atualizar</button></div>
  {msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b',marginBottom:12}}>{msg}</div>}
  <div style={{display:'grid',gap:12}}>{items.map(a=>{const isSos=a.alert_type==='sos',maps=a.lat!=null&&a.lng!=null?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${a.lat},${a.lng}`)}`:'';return <article key={a.id} style={{...box,borderColor:a.status==='open'?(isSos?'#991b1b':'#a16207'):'#2f4f3a'}}><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:12}}><div><div style={{fontWeight:950,fontSize:18}}>{isSos?'🆘 SOS':'⚠️ Desvio de rota'} <span style={{fontSize:11,color:a.status==='open'?'#fca5a5':'#86efac'}}>· {a.status==='open'?'ABERTO':'RESOLVIDO'}</span></div><div style={{color:'#9ca3af',fontSize:12,marginTop:5}}>{new Date(a.created_at).toLocaleString('pt-BR')} · corrida {a.ride_id.slice(0,8)} · franquia {a.franchise_id?.slice(0,8)||'—'} · cidade {a.city_id?.slice(0,8)||'—'}</div></div>{a.status==='open'&&<button disabled={busy} onClick={()=>resolve(a.id)} style={{...btn,background:'#166534',color:'#fff'}}>✓ Resolver</button>}</div><div style={{marginTop:12,lineHeight:1.55}}><div><b>Passageiro:</b> {a.passenger_name||'—'} · <b>Motorista:</b> {a.driver_name||'—'}</div><div><b>Embarque:</b> {a.origin_label}</div><div><b>Destino:</b> {a.destination_label}</div><div><b>Coordenadas:</b> {a.lat!=null&&a.lng!=null?`${Number(a.lat).toFixed(6)}, ${Number(a.lng).toFixed(6)}`:'não disponíveis'}{a.distance_from_route_m!=null?` · ${Math.round(Number(a.distance_from_route_m))} m da rota`:''}</div>{a.message&&<div><b>Registro:</b> {a.message}</div>}</div><div style={{display:'flex',gap:8,marginTop:11,flexWrap:'wrap'}}>{maps&&<a href={maps} target="_blank" rel="noreferrer" style={{...btn,textDecoration:'none',background:'#222',color:'#fff'}}>📍 Abrir localização</a>}<span style={{border:'1px solid #333',borderRadius:10,padding:'10px 12px',fontSize:12,color:'#9ca3af'}}>Corrida: {a.ride_status}</span>{a.resolved_at&&<span style={{border:'1px solid #333',borderRadius:10,padding:'10px 12px',fontSize:12,color:'#9ca3af'}}>Resolvido: {new Date(a.resolved_at).toLocaleString('pt-BR')}</span>}</div></article>})}{!items.length&&<div style={{...box,textAlign:'center',padding:32,color:'#9ca3af'}}>Nenhum alerta {filter==='open'?'aberto':''} encontrado.</div>}</div>
 </div>
}
