'use client'

import Link from 'next/link'
import {FormEvent,useEffect,useMemo,useRef,useState} from 'react'
import type {Map as LeafletMap,Circle as LeafletCircle,Marker as LeafletMarker} from 'leaflet'
import {supabase} from '@/lib/supabase'
import 'leaflet/dist/leaflet.css'

type City={id:string;name:string;state:string;center_lat:number|null;center_lng:number|null;max_pickup_radius_km:number|string;heatmap_window_minutes:number;locked_by_matrix:boolean}
type Category={id:string;city_id:string;name:string}
type Rule={id:string;name:string;city_id:string;category_id:string|null;days_of_week:number[];start_time:string;end_time:string;multiplier:number|string;priority:number;active:boolean;locked_by_matrix:boolean;center_lat:number;center_lng:number;radius_km:number|string;visible_to_drivers:boolean}
type Config={cities:City[];categories:Category[];rules:Rule[]}
type Draft={name:string;category_id:string;multiplier:string;radius_km:string;center_lat:string;center_lng:string;start_time:string;end_time:string;priority:string;days_of_week:number[];active:boolean;visible_to_drivers:boolean}

const days=[['Dom',0],['Seg',1],['Ter',2],['Qua',3],['Qui',4],['Sex',5],['Sáb',6]] as const
const box={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:18} as const
const input={width:'100%',background:'#0b0b0b',color:'#fff',border:'1px solid #333',borderRadius:10,padding:'11px 12px',boxSizing:'border-box'} as const
const btn={background:'#ffd400',color:'#000',border:0,borderRadius:10,padding:'11px 14px',fontWeight:800,cursor:'pointer'} as const
const secondary={...btn,background:'#252525',color:'#fff',border:'1px solid #3a3a3a'} as const
const label={fontSize:12,color:'#a1a1aa',display:'grid',gap:5} as const
const blank=(c?:City):Draft=>({name:'Horário de pico',category_id:'',multiplier:'1.30',radius_km:'2',center_lat:c?.center_lat==null?'':String(c.center_lat),center_lng:c?.center_lng==null?'':String(c.center_lng),start_time:'17:00',end_time:'20:00',priority:'50',days_of_week:[1,2,3,4,5],active:true,visible_to_drivers:true})
const toDraft=(r:Rule):Draft=>({name:r.name,category_id:r.category_id||'',multiplier:String(r.multiplier),radius_km:String(r.radius_km),center_lat:String(r.center_lat),center_lng:String(r.center_lng),start_time:(r.start_time||'00:00').slice(0,5),end_time:(r.end_time||'23:59').slice(0,5),priority:String(r.priority||50),days_of_week:r.days_of_week||[0,1,2,3,4,5,6],active:r.active,visible_to_drivers:r.visible_to_drivers})

export default function DynamicPricingPage(){
 const[cfg,setCfg]=useState<Config>({cities:[],categories:[],rules:[]}),[cityId,setCityId]=useState(''),[radius,setRadius]=useState('8'),[windowMin,setWindowMin]=useState('60'),[draft,setDraft]=useState<Draft>(blank()),[editing,setEditing]=useState<Rule|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false)
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<LeafletMap|null>(null),leafletRef=useRef<typeof import('leaflet')|null>(null),layers=useRef<(LeafletCircle|LeafletMarker)[]>([])
 const city=cfg.cities.find(c=>c.id===cityId),rules=useMemo(()=>cfg.rules.filter(r=>r.city_id===cityId),[cfg.rules,cityId]),categories=useMemo(()=>cfg.categories.filter(c=>c.city_id===cityId),[cfg.categories,cityId])
 useEffect(()=>{void load()},[])
 useEffect(()=>{let alive=true;(async()=>{if(!mapEl.current)return;const L=await import('leaflet');if(!alive||!mapEl.current)return;leafletRef.current=L;mapRef.current=L.map(mapEl.current).setView([-14.52472,-49.14083],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(mapRef.current);mapRef.current.on('click',(e)=>setDraft(v=>({...v,center_lat:e.latlng.lat.toFixed(6),center_lng:e.latlng.lng.toFixed(6)})));setReady(true)})();return()=>{alive=false;mapRef.current?.remove();mapRef.current=null;leafletRef.current=null}},[])
 useEffect(()=>{if(!ready)return;renderMap()},[ready,cityId,cfg.rules,draft.center_lat,draft.center_lng,draft.radius_km,draft.multiplier])
 async function load(){setBusy(true);setMsg('');try{const{data,error}=await supabase.rpc('franchise_market_config');if(error)throw error;const next=(data||{cities:[],categories:[],rules:[]}) as Config;setCfg(next);const first=next.cities[0];setCityId(v=>next.cities.some(c=>c.id===v)?v:first?.id||'');if(first){setRadius(String(first.max_pickup_radius_km||8));setWindowMin(String(first.heatmap_window_minutes||60));setDraft(blank(first))}}catch(e){setMsg(e instanceof Error?e.message:'Erro ao carregar configurações.')}finally{setBusy(false)}}
 function selectCity(id:string){setCityId(id);const c=cfg.cities.find(x=>x.id===id);if(c){setRadius(String(c.max_pickup_radius_km||8));setWindowMin(String(c.heatmap_window_minutes||60));setDraft(blank(c));setEditing(null)}}
 function renderMap(){const L=leafletRef.current,map=mapRef.current;if(!L||!map)return;layers.current.forEach(x=>x.remove());layers.current=[];const c=cfg.cities.find(x=>x.id===cityId);if(c&&Number.isFinite(Number(c.center_lat))&&Number.isFinite(Number(c.center_lng)))map.setView([Number(c.center_lat),Number(c.center_lng)],13);for(const r of rules){if(!Number.isFinite(Number(r.center_lat))||!Number.isFinite(Number(r.center_lng)))continue;const circle=L.circle([Number(r.center_lat),Number(r.center_lng)],{radius:Number(r.radius_km)*1000,color:r.active?'#f59e0b':'#777',weight:3,fillColor:'#facc15',fillOpacity:r.active?.16:.06}).addTo(map);circle.bindPopup(`<strong>${r.name}</strong><br/>Dinâmica ${Number(r.multiplier).toFixed(2)}x · ${r.radius_km} km`);layers.current.push(circle)}const lat=Number(draft.center_lat),lng=Number(draft.center_lng),rr=Number(draft.radius_km);if(Number.isFinite(lat)&&Number.isFinite(lng)&&Number.isFinite(rr)&&rr>0){const preview=L.circle([lat,lng],{radius:rr*1000,color:'#ffd400',weight:4,dashArray:'8 6',fillOpacity:.05}).addTo(map);const mark=L.marker([lat,lng]).addTo(map).bindPopup(`Nova área · ${Number(draft.multiplier||1).toFixed(2)}x`);layers.current.push(preview,mark)}}
 async function saveDispatch(e:FormEvent){e.preventDefault();if(!cityId)return;setBusy(true);setMsg('');try{const{error}=await supabase.rpc('franchise_save_dispatch_settings',{p_city_id:cityId,p_max_pickup_radius_km:Number(radius),p_heatmap_window_minutes:Number(windowMin)});if(error)throw error;setMsg('Raio de chamada e mapa de calor atualizados.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Erro ao salvar raio.')}finally{setBusy(false)}}
 async function saveRule(e:FormEvent){e.preventDefault();if(!cityId)return;setBusy(true);setMsg('');try{const payload={...draft,category_id:draft.category_id||null,multiplier:Number(draft.multiplier),radius_km:Number(draft.radius_km),center_lat:Number(draft.center_lat),center_lng:Number(draft.center_lng),priority:Number(draft.priority)};const{error}=await supabase.rpc('franchise_save_dynamic_rule',{p_rule_id:editing?.id||null,p_city_id:cityId,p_payload:payload});if(error)throw error;setMsg(editing?'Dinâmica atualizada.':'Dinâmica criada.');setEditing(null);await load()}catch(e){setMsg(e instanceof Error?e.message:'Erro ao salvar dinâmica.')}finally{setBusy(false)}}
 async function remove(r:Rule){if(r.locked_by_matrix){setMsg('Dinâmica bloqueada pela Matriz.');return}if(!confirm(`Excluir a dinâmica “${r.name}”?`))return;setBusy(true);const{error}=await supabase.rpc('franchise_delete_dynamic_rule',{p_rule_id:r.id});setBusy(false);setMsg(error?error.message:'Dinâmica excluída.');if(!error)await load()}
 function edit(r:Rule){if(r.locked_by_matrix){setMsg('Dinâmica bloqueada pela Matriz.');return}setEditing(r);setCityId(r.city_id);setDraft(toDraft(r));window.scrollTo({top:0,behavior:'smooth'})}
 function toggleDay(n:number){setDraft(v=>({...v,days_of_week:v.days_of_week.includes(n)?v.days_of_week.filter(x=>x!==n):[...v.days_of_week,n].sort()}))}
 return <main style={{minHeight:'100vh',background:'#080808',color:'#fff',padding:24}}><div style={{maxWidth:1280,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center',marginBottom:18}}><div><div style={{color:'#ffd400',fontWeight:900}}>CLICK-GO · FRANQUEADO</div><h1 style={{margin:'6px 0'}}>Raio, dinâmica e mapa de calor</h1><p style={{margin:0,color:'#a1a1aa'}}>Controle o alcance das chamadas e as zonas de tarifa dinâmica que os motoristas verão no mapa.</p></div><Link href="/franqueado" style={{...secondary,textDecoration:'none'}}>← Dashboard</Link></header>
  {msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b',marginBottom:16}}>{msg}</div>}
  <div style={{display:'grid',gridTemplateColumns:'minmax(300px,420px) 1fr',gap:16,alignItems:'start'}}>
   <div style={{display:'grid',gap:16}}>
    <form onSubmit={saveDispatch} style={box}><h2 style={{marginTop:0}}>Alcance das chamadas</h2><label style={label}>Cidade<select style={input} value={cityId} onChange={e=>selectCity(e.target.value)}>{cfg.cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></label><div style={{height:10}}/><label style={label}>Raio máximo de chamada (km)<input type="number" min="0.5" max="50" step="0.5" style={input} value={radius} onChange={e=>setRadius(e.target.value)} disabled={city?.locked_by_matrix}/></label><div style={{height:10}}/><label style={label}>Mapa de calor: últimos minutos<select style={input} value={windowMin} onChange={e=>setWindowMin(e.target.value)} disabled={city?.locked_by_matrix}><option value="30">30 minutos</option><option value="60">1 hora</option><option value="120">2 horas</option><option value="180">3 horas</option><option value="360">6 horas</option></select></label>{city?.locked_by_matrix&&<p style={{color:'#fbbf24'}}>Esta configuração foi bloqueada pela Matriz.</p>}<button style={{...btn,width:'100%',marginTop:14}} disabled={busy||city?.locked_by_matrix}>Salvar alcance</button></form>
    <form onSubmit={saveRule} style={box}><h2 style={{marginTop:0}}>{editing?'Editar dinâmica':'Nova dinâmica'}</h2><label style={label}>Nome<input style={input} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div style={{height:9}}/><label style={label}>Categoria<select style={input} value={draft.category_id} onChange={e=>setDraft({...draft,category_id:e.target.value})}><option value="">Todas as categorias</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9,marginTop:9}}><label style={label}>Multiplicador<input type="number" min="1" max="5" step="0.05" style={input} value={draft.multiplier} onChange={e=>setDraft({...draft,multiplier:e.target.value})}/></label><label style={label}>Raio da zona (km)<input type="number" min="0.2" max="50" step="0.1" style={input} value={draft.radius_km} onChange={e=>setDraft({...draft,radius_km:e.target.value})}/></label><label style={label}>Latitude<input type="number" step="0.000001" style={input} value={draft.center_lat} onChange={e=>setDraft({...draft,center_lat:e.target.value})}/></label><label style={label}>Longitude<input type="number" step="0.000001" style={input} value={draft.center_lng} onChange={e=>setDraft({...draft,center_lng:e.target.value})}/></label><label style={label}>Início<input type="time" style={input} value={draft.start_time} onChange={e=>setDraft({...draft,start_time:e.target.value})}/></label><label style={label}>Fim<input type="time" style={input} value={draft.end_time} onChange={e=>setDraft({...draft,end_time:e.target.value})}/></label></div><div style={{marginTop:10,fontSize:12,color:'#a1a1aa'}}>Clique no mapa para definir o centro da zona.</div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:9}}>{days.map(([d,n])=><button type="button" key={n} onClick={()=>toggleDay(n)} style={draft.days_of_week.includes(n)?btn:secondary}>{d}</button>)}</div><label style={{display:'flex',gap:8,alignItems:'center',marginTop:12}}><input type="checkbox" checked={draft.visible_to_drivers} onChange={e=>setDraft({...draft,visible_to_drivers:e.target.checked})}/> Mostrar valor da dinâmica no mapa dos motoristas</label><label style={{display:'flex',gap:8,alignItems:'center',marginTop:8}}><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Dinâmica ativa</label><div style={{display:'flex',gap:8,marginTop:14}}><button style={{...btn,flex:1}} disabled={busy}>Salvar dinâmica</button>{editing&&<button type="button" style={secondary} onClick={()=>{setEditing(null);setDraft(blank(city))}}>Cancelar</button>}</div></form>
   </div>
   <div style={{display:'grid',gap:16}}><section style={box}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 4px'}}>Mapa das zonas</h2><span style={{color:'#a1a1aa',fontSize:13}}>Círculos amarelos = áreas dinâmicas cadastradas.</span></div></div><div ref={mapEl} style={{height:480,borderRadius:14,overflow:'hidden',marginTop:14}}/></section><section style={box}><h2 style={{marginTop:0}}>Dinâmicas cadastradas</h2>{rules.length===0?<p style={{color:'#a1a1aa'}}>Nenhuma dinâmica nesta cidade.</p>:<div style={{display:'grid',gap:9}}>{rules.map(r=><div key={r.id} style={{background:'#0b0b0b',border:'1px solid #2b2b2b',borderRadius:12,padding:13,display:'grid',gridTemplateColumns:'1fr auto',gap:10}}><div><strong>{r.name} · {Number(r.multiplier).toFixed(2)}x</strong><div style={{color:'#a1a1aa',fontSize:13,marginTop:4}}>{r.radius_km} km · {(r.start_time||'').slice(0,5)}–{(r.end_time||'').slice(0,5)} · {r.active?'Ativa':'Pausada'}{r.visible_to_drivers?' · visível ao motorista':''}</div>{r.locked_by_matrix&&<div style={{color:'#fbbf24',fontSize:12,marginTop:4}}>Bloqueada pela Matriz</div>}</div><div style={{display:'flex',gap:7,alignItems:'center'}}><button type="button" style={secondary} onClick={()=>edit(r)} disabled={r.locked_by_matrix}>Editar</button><button type="button" style={{...secondary,color:'#fca5a5'}} onClick={()=>void remove(r)} disabled={r.locked_by_matrix}>Excluir</button></div></div>)}</div>}</section></div>
  </div>
 </div></main>
}
