from pathlib import Path

path = Path('app/src/main/java/com/clickgo/passageiro/MainActivity.java')
text = path.read_text(encoding='utf-8')

old = '''        Marker selected = new Marker(picker);\n        selected.setPosition(initial);\n        selected.setTitle(forOrigin ? "Embarque" : "Destino");\n        selected.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);\n        picker.getOverlays().add(selected);\n        final GeoPoint[] chosen = { initial };\n        MapEventsOverlay events = new MapEventsOverlay(new MapEventsReceiver() {\n            @Override public boolean singleTapConfirmedHelper(GeoPoint point) {\n                chosen[0] = point; selected.setPosition(point); picker.invalidate(); return true;\n            }\n            @Override public boolean longPressHelper(GeoPoint point) { return singleTapConfirmedHelper(point); }\n        });\n        picker.getOverlays().add(0, events);\n        TextView tip = text("Toque no mapa para mover o marcador.", 13, Color.WHITE, true);\n'''

new = '''        final GeoPoint[] chosen = { initial };\n        MapEventsOverlay events = new MapEventsOverlay(new MapEventsReceiver() {\n            @Override public boolean singleTapConfirmedHelper(GeoPoint point) {\n                chosen[0] = point;\n                selected.setPosition(point);\n                selected.setTitle(forOrigin ? "Embarque escolhido" : "Destino escolhido");\n                picker.getController().animateTo(point);\n                picker.invalidate();\n                return true;\n            }\n            @Override public boolean longPressHelper(GeoPoint point) {\n                return singleTapConfirmedHelper(point);\n            }\n        });\n        picker.getOverlays().add(events);\n\n        Marker selected = new Marker(picker);\n        selected.setPosition(initial);\n        selected.setTitle(forOrigin ? "Embarque escolhido" : "Destino escolhido");\n        selected.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);\n        selected.setDraggable(true);\n        selected.setOnMarkerDragListener(new Marker.OnMarkerDragListener() {\n            @Override public void onMarkerDrag(Marker marker) {\n                chosen[0] = marker.getPosition();\n            }\n            @Override public void onMarkerDragEnd(Marker marker) {\n                chosen[0] = marker.getPosition();\n                picker.getController().animateTo(marker.getPosition());\n                picker.invalidate();\n            }\n            @Override public void onMarkerDragStart(Marker marker) {\n                chosen[0] = marker.getPosition();\n            }\n        });\n        picker.getOverlays().add(selected);\n        TextView tip = text(forOrigin ? "Toque no mapa ou arraste o marcador para ajustar o embarque." : "Toque no mapa ou arraste o marcador para escolher o DESTINO.", 13, Color.WHITE, true);\n'''

# O bloco novo referencia selected dentro do receiver; em Java a variável precisa existir antes.
# Portanto aplicamos uma versão equivalente com o marcador criado antes e o overlay de eventos adicionado depois.
new = '''        final GeoPoint[] chosen = { initial };\n        Marker selected = new Marker(picker);\n        selected.setPosition(initial);\n        selected.setTitle(forOrigin ? "Embarque escolhido" : "Destino escolhido");\n        selected.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);\n        selected.setDraggable(true);\n        selected.setOnMarkerDragListener(new Marker.OnMarkerDragListener() {\n            @Override public void onMarkerDrag(Marker marker) {\n                chosen[0] = marker.getPosition();\n            }\n            @Override public void onMarkerDragEnd(Marker marker) {\n                chosen[0] = marker.getPosition();\n                picker.getController().animateTo(marker.getPosition());\n                picker.invalidate();\n            }\n            @Override public void onMarkerDragStart(Marker marker) {\n                chosen[0] = marker.getPosition();\n            }\n        });\n        picker.getOverlays().add(selected);\n\n        MapEventsOverlay events = new MapEventsOverlay(new MapEventsReceiver() {\n            @Override public boolean singleTapConfirmedHelper(GeoPoint point) {\n                chosen[0] = point;\n                selected.setPosition(point);\n                selected.setTitle(forOrigin ? "Embarque escolhido" : "Destino escolhido");\n                picker.getController().animateTo(point);\n                picker.invalidate();\n                return true;\n            }\n            @Override public boolean longPressHelper(GeoPoint point) {\n                return singleTapConfirmedHelper(point);\n            }\n        });\n        picker.getOverlays().add(0, events);\n        TextView tip = text(forOrigin ? "Toque no mapa ou arraste o marcador para ajustar o embarque." : "Toque no mapa ou arraste o marcador para escolher o DESTINO.", 13, Color.WHITE, true);\n'''

if old not in text:
    raise SystemExit('Bloco do marcador do seletor não encontrado')
text = text.replace(old, new, 1)

# Deixa claro que o ponto confirmado é o destino quando o seletor foi aberto pelo Passageiro.
text = text.replace('''            else { destination = point; destinationLabel = "Destino marcado no mapa"; picker.onDetach(); showOptions(); }\n''', '''            else {\n                destination = point;\n                destinationLabel = "Destino marcado no mapa";\n                picker.onDetach();\n                showOptions();\n            }\n''', 1)

build_path = Path('app/build.gradle')
build = build_path.read_text(encoding='utf-8')
build = build.replace('versionCode 11', 'versionCode 12', 1)
build = build.replace("versionName '1.1-native-beta'", "versionName '1.2-native-beta'", 1)
build_path.write_text(build, encoding='utf-8')

path.write_text(text, encoding='utf-8')
print('Passageiro v1.2: marcador de destino móvel por toque e arraste.')
