create table if not exists public.user_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  ride_id uuid references public.rides(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists user_notifications_user_time_idx on public.user_notifications(user_id,created_at desc);
create index if not exists user_notifications_unread_idx on public.user_notifications(user_id,created_at desc) where read_at is null;

alter table public.user_notifications enable row level security;
revoke all on public.user_notifications from anon,authenticated;
grant select,update on public.user_notifications to authenticated;

drop policy if exists user_notifications_owner_select on public.user_notifications;
create policy user_notifications_owner_select on public.user_notifications for select to authenticated using ((select auth.uid())=user_id);

drop policy if exists user_notifications_owner_update on public.user_notifications;
create policy user_notifications_owner_update on public.user_notifications for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='user_notifications') then
    alter publication supabase_realtime add table public.user_notifications;
  end if;
end $$;

create or replace function public.enqueue_user_notification(p_user_id uuid,p_type text,p_title text,p_body text,p_ride_id uuid default null,p_data jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path to 'public','pg_temp' as $$
begin
  if p_user_id is null then return; end if;
  insert into public.user_notifications(user_id,ride_id,type,title,body,data)
  values(p_user_id,p_ride_id,p_type,left(coalesce(p_title,''),160),left(coalesce(p_body,''),600),coalesce(p_data,'{}'::jsonb));
end;
$$;
revoke all on function public.enqueue_user_notification(uuid,text,text,text,uuid,jsonb) from public,anon,authenticated;

create or replace function public.notify_ride_participants()
returns trigger language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_body text;
begin
  if new.status is not distinct from old.status and new.driver_id is not distinct from old.driver_id then return new; end if;
  if new.status is distinct from old.status then
    if new.status::text='accepted' then
      perform public.enqueue_user_notification(new.passenger_id,'ride_accepted','Motorista a caminho','Sua corrida foi aceita. Confira motorista, foto, veículo e placa antes do embarque.',new.id,jsonb_build_object('status',new.status));
      perform public.enqueue_user_notification(new.driver_id,'ride_assigned','Corrida aceita','Abra a navegação e siga até o ponto de embarque.',new.id,jsonb_build_object('status',new.status));
    elsif new.status::text='driver_arriving' then
      v_body:=format('O motorista chegou. Tolerância de espera: %s min. Após isso: R$ %s/min.',greatest(0,coalesce(new.wait_free_seconds,0)/60),to_char(coalesce(new.wait_fee_per_minute,0),'FM999990D00'));
      perform public.enqueue_user_notification(new.passenger_id,'driver_arrived','Motorista chegou ao embarque',v_body,new.id,jsonb_build_object('status',new.status,'wait_free_seconds',new.wait_free_seconds,'wait_fee_per_minute',new.wait_fee_per_minute));
      perform public.enqueue_user_notification(new.driver_id,'pickup_wait_started','Tolerância de embarque iniciada','A chegada foi registrada e o relógio de espera está ativo.',new.id,jsonb_build_object('status',new.status));
    elsif new.status::text='in_progress' then
      v_body:=case when coalesce(new.wait_charge_amount,0)>0 then format('Corrida iniciada. Espera no embarque registrada: R$ %s.',to_char(new.wait_charge_amount,'FM999990D00')) else 'Corrida iniciada com segurança.' end;
      perform public.enqueue_user_notification(new.passenger_id,'ride_started','Corrida iniciada',v_body,new.id,jsonb_build_object('status',new.status,'wait_charge_amount',new.wait_charge_amount));
      perform public.enqueue_user_notification(new.driver_id,'ride_started','Corrida iniciada',v_body,new.id,jsonb_build_object('status',new.status,'wait_charge_amount',new.wait_charge_amount));
    elsif new.status::text='completed' then
      v_body:=format('Corrida concluída. Valor final: R$ %s.',to_char(coalesce(new.final_fare,new.estimated_fare,0),'FM999990D00'));
      perform public.enqueue_user_notification(new.passenger_id,'ride_completed','Corrida concluída',v_body,new.id,jsonb_build_object('status',new.status,'final_fare',new.final_fare));
      perform public.enqueue_user_notification(new.driver_id,'ride_completed','Corrida concluída',v_body,new.id,jsonb_build_object('status',new.status,'final_fare',new.final_fare));
    elsif new.status::text='cancelled' then
      perform public.enqueue_user_notification(new.passenger_id,'ride_cancelled','Corrida cancelada','A corrida foi cancelada. Consulte o histórico para ver detalhes e eventual taxa.',new.id,jsonb_build_object('status',new.status,'cancellation_fee_amount',new.cancellation_fee_amount));
      perform public.enqueue_user_notification(new.driver_id,'ride_cancelled','Corrida cancelada','A corrida foi cancelada.',new.id,jsonb_build_object('status',new.status));
    end if;
  elsif new.driver_id is distinct from old.driver_id and new.driver_id is not null then
    perform public.enqueue_user_notification(new.passenger_id,'driver_found','Motorista encontrado','Um motorista foi vinculado à sua corrida.',new.id,jsonb_build_object('driver_id',new.driver_id));
    perform public.enqueue_user_notification(new.driver_id,'ride_assigned','Nova corrida atribuída','Abra o App Motorista para conferir embarque e destino.',new.id,'{}'::jsonb);
  end if;
  return new;
end;
$$;
revoke all on function public.notify_ride_participants() from public,anon,authenticated;

drop trigger if exists trg_notify_ride_participants on public.rides;
create trigger trg_notify_ride_participants after update of status,driver_id on public.rides for each row execute function public.notify_ride_participants();

create or replace function public.notify_users_on_ride_safety_alert()
returns trigger language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_ride public.rides%rowtype; v_title text; v_body text;
begin
  select * into v_ride from public.rides where id=new.ride_id;
  if not found then return new; end if;
  if new.alert_type='sos' then
    v_title:='🆘 SOS registrado na corrida';
    v_body:='Um alerta SOS foi registrado e está visível para a central de segurança CLICK-GO.';
  else
    v_title:='⚠️ Alerta de rota';
    v_body:=format('Possível desvio de rota detectado%s.',case when new.distance_from_route_m is null then '' else format(' a aproximadamente %s m da rota',round(new.distance_from_route_m)) end);
  end if;
  perform public.enqueue_user_notification(v_ride.passenger_id,'safety_'||new.alert_type,v_title,v_body,new.ride_id,jsonb_build_object('alert_id',new.id,'alert_type',new.alert_type,'severity',new.severity));
  perform public.enqueue_user_notification(v_ride.driver_id,'safety_'||new.alert_type,v_title,v_body,new.ride_id,jsonb_build_object('alert_id',new.id,'alert_type',new.alert_type,'severity',new.severity));
  return new;
end;
$$;
revoke all on function public.notify_users_on_ride_safety_alert() from public,anon,authenticated;

drop trigger if exists trg_notify_users_on_ride_safety_alert on public.ride_safety_alerts;
create trigger trg_notify_users_on_ride_safety_alert after insert on public.ride_safety_alerts for each row execute function public.notify_users_on_ride_safety_alert();
