create table if not exists public.driver_taximeter_sessions (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.drivers(id) on delete cascade,
  franchise_id uuid references public.franchises(id) on delete set null,
  city_id uuid references public.cities(id) on delete set null,
  category_id uuid not null references public.ride_categories(id) on delete restrict,
  status text not null default 'running' check (status in ('running','finished','cancelled')),
  base_fare numeric(12,2) not null default 0 check (base_fare >= 0),
  price_per_km numeric(12,4) not null default 0 check (price_per_km >= 0),
  price_per_minute numeric(12,4) not null default 0 check (price_per_minute >= 0),
  minimum_fare numeric(12,2) not null default 0 check (minimum_fare >= 0),
  multiplier numeric(8,3) not null default 1 check (multiplier between 1 and 10),
  started_at timestamptz not null default now(),
  last_tick_at timestamptz not null default now(),
  ended_at timestamptz,
  start_lat double precision check (start_lat is null or start_lat between -90 and 90),
  start_lng double precision check (start_lng is null or start_lng between -180 and 180),
  last_lat double precision check (last_lat is null or last_lat between -90 and 90),
  last_lng double precision check (last_lng is null or last_lng between -180 and 180),
  end_lat double precision check (end_lat is null or end_lat between -90 and 90),
  end_lng double precision check (end_lng is null or end_lng between -180 and 180),
  distance_m numeric(14,2) not null default 0 check (distance_m >= 0),
  elapsed_seconds integer not null default 0 check (elapsed_seconds >= 0),
  current_amount numeric(12,2) not null default 0 check (current_amount >= 0),
  final_amount numeric(12,2),
  payment_method text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists driver_taximeter_one_running_idx on public.driver_taximeter_sessions(driver_id) where status='running';
create index if not exists driver_taximeter_driver_time_idx on public.driver_taximeter_sessions(driver_id,started_at desc);
create index if not exists driver_taximeter_franchise_time_idx on public.driver_taximeter_sessions(franchise_id,started_at desc);

create table if not exists public.driver_taximeter_points (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.driver_taximeter_sessions(id) on delete cascade,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  distance_from_prev_m numeric(12,2),
  accepted boolean not null default true,
  recorded_at timestamptz not null default now()
);
create index if not exists driver_taximeter_points_session_time_idx on public.driver_taximeter_points(session_id,recorded_at);

alter table public.driver_taximeter_sessions enable row level security;
alter table public.driver_taximeter_points enable row level security;
revoke all on public.driver_taximeter_sessions from anon, authenticated;
revoke all on public.driver_taximeter_points from anon, authenticated;
grant select on public.driver_taximeter_sessions to authenticated;
grant select on public.driver_taximeter_points to authenticated;

drop policy if exists taximeter_sessions_read_scope on public.driver_taximeter_sessions;
create policy taximeter_sessions_read_scope on public.driver_taximeter_sessions for select to authenticated using (
  driver_id=(select auth.uid()) or public.jwt_app_role()='super_admin' or (public.jwt_app_role()='franchise_admin' and franchise_id=public.jwt_franchise_id())
);

drop policy if exists taximeter_points_read_scope on public.driver_taximeter_points;
create policy taximeter_points_read_scope on public.driver_taximeter_points for select to authenticated using (
  driver_id=(select auth.uid()) or exists (
    select 1 from public.driver_taximeter_sessions s where s.id=session_id and (
      public.jwt_app_role()='super_admin' or (public.jwt_app_role()='franchise_admin' and s.franchise_id=public.jwt_franchise_id())
    )
  )
);

create or replace function public.taximeter_distance_m(p_lat1 double precision,p_lng1 double precision,p_lat2 double precision,p_lng2 double precision)
returns numeric language sql immutable set search_path to 'pg_catalog','public' as $$
  select 6371000 * 2 * asin(sqrt(power(sin(radians(p_lat2-p_lat1)/2),2) + cos(radians(p_lat1))*cos(radians(p_lat2))*power(sin(radians(p_lng2-p_lng1)/2),2)));
$$;
revoke all on function public.taximeter_distance_m(double precision,double precision,double precision,double precision) from public,anon,authenticated;

create or replace function public.get_my_taximeter_categories()
returns table(category_id uuid,category_name text,base_fare numeric,price_per_km numeric,price_per_minute numeric,minimum_fare numeric,multiplier numeric)
language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_uid uuid:=auth.uid(); v_driver public.drivers%rowtype;
begin
  if v_uid is null then raise exception 'Não autenticado'; end if;
  select * into v_driver from public.drivers where id=v_uid;
  if not found or v_driver.status::text<>'approved' then raise exception 'Motorista ainda não está aprovado'; end if;
  return query
  select c.id,c.name,c.base_fare,c.price_per_km,c.price_per_minute,c.minimum_fare,greatest(coalesce(c.dynamic_multiplier,1),1)
  from public.ride_categories c
  where c.active=true and c.city_id is not distinct from v_driver.city_id and c.franchise_id is not distinct from v_driver.franchise_id
    and (not exists(select 1 from public.driver_category_eligibility e0 where e0.driver_id=v_uid) or exists(select 1 from public.driver_category_eligibility e where e.driver_id=v_uid and e.category_id=c.id and e.active=true))
  order by c.name;
end;
$$;
revoke all on function public.get_my_taximeter_categories() from public,anon;
grant execute on function public.get_my_taximeter_categories() to authenticated;

create or replace function public.start_driver_taximeter(p_category_id uuid,p_lat double precision,p_lng double precision)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_uid uuid:=auth.uid(); v_driver public.drivers%rowtype; v_cat public.ride_categories%rowtype; v_id uuid; v_amount numeric;
begin
  if v_uid is null then raise exception 'Não autenticado'; end if;
  if p_lat not between -90 and 90 or p_lng not between -180 and 180 then raise exception 'Localização inválida'; end if;
  select * into v_driver from public.drivers where id=v_uid for update;
  if not found or v_driver.status::text<>'approved' then raise exception 'Motorista não aprovado'; end if;
  if exists(select 1 from public.rides r where r.driver_id=v_uid and r.status::text in ('accepted','driver_arriving','in_progress')) then raise exception 'Finalize a corrida CLICK-GO ativa antes de usar o taxímetro livre'; end if;
  if exists(select 1 from public.driver_taximeter_sessions s where s.driver_id=v_uid and s.status='running') then raise exception 'Já existe um taxímetro em andamento'; end if;
  select * into v_cat from public.ride_categories c where c.id=p_category_id and c.active=true and c.city_id is not distinct from v_driver.city_id and c.franchise_id is not distinct from v_driver.franchise_id;
  if not found then raise exception 'Categoria indisponível para este motorista'; end if;
  if exists(select 1 from public.driver_category_eligibility e0 where e0.driver_id=v_uid) and not exists(select 1 from public.driver_category_eligibility e where e.driver_id=v_uid and e.category_id=p_category_id and e.active=true) then raise exception 'Categoria não autorizada para este motorista'; end if;
  v_amount:=round(greatest(coalesce(v_cat.minimum_fare,0),coalesce(v_cat.base_fare,0))*greatest(coalesce(v_cat.dynamic_multiplier,1),1),2);
  insert into public.driver_taximeter_sessions(driver_id,franchise_id,city_id,category_id,base_fare,price_per_km,price_per_minute,minimum_fare,multiplier,start_lat,start_lng,last_lat,last_lng,current_amount)
  values(v_uid,v_driver.franchise_id,v_driver.city_id,v_cat.id,coalesce(v_cat.base_fare,0),coalesce(v_cat.price_per_km,0),coalesce(v_cat.price_per_minute,0),coalesce(v_cat.minimum_fare,0),greatest(coalesce(v_cat.dynamic_multiplier,1),1),p_lat,p_lng,p_lat,p_lng,v_amount) returning id into v_id;
  insert into public.driver_taximeter_points(session_id,driver_id,lat,lng,distance_from_prev_m,accepted) values(v_id,v_uid,p_lat,p_lng,0,true);
  return jsonb_build_object('ok',true,'session_id',v_id,'status','running','amount',v_amount,'started_at',now());
end;
$$;
revoke all on function public.start_driver_taximeter(uuid,double precision,double precision) from public,anon;
grant execute on function public.start_driver_taximeter(uuid,double precision,double precision) to authenticated;

create or replace function public.tick_driver_taximeter(p_session_id uuid,p_lat double precision,p_lng double precision)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_uid uuid:=auth.uid(); v_s public.driver_taximeter_sessions%rowtype; v_step numeric:=0; v_delta_s integer:=0; v_total_s integer:=0; v_max_step numeric:=0; v_accept boolean:=true; v_distance numeric:=0; v_amount numeric:=0;
begin
  if v_uid is null then raise exception 'Não autenticado'; end if;
  if p_lat not between -90 and 90 or p_lng not between -180 and 180 then raise exception 'Localização inválida'; end if;
  select * into v_s from public.driver_taximeter_sessions where id=p_session_id and driver_id=v_uid for update;
  if not found or v_s.status<>'running' then raise exception 'Taxímetro não está em andamento'; end if;
  v_delta_s:=greatest(1,floor(extract(epoch from (now()-v_s.last_tick_at)))::integer);
  v_total_s:=greatest(0,floor(extract(epoch from (now()-v_s.started_at)))::integer);
  if v_s.last_lat is not null and v_s.last_lng is not null then v_step:=public.taximeter_distance_m(v_s.last_lat,v_s.last_lng,p_lat,p_lng); end if;
  v_max_step:=greatest(120::numeric,v_delta_s*70::numeric);
  if v_step>v_max_step then v_accept:=false; end if;
  v_distance:=v_s.distance_m + case when v_accept then coalesce(v_step,0) else 0 end;
  v_amount:=round(greatest(v_s.minimum_fare,(v_s.base_fare + (v_distance/1000.0)*v_s.price_per_km + (v_total_s/60.0)*v_s.price_per_minute)*v_s.multiplier),2);
  update public.driver_taximeter_sessions set last_tick_at=now(),last_lat=p_lat,last_lng=p_lng,distance_m=v_distance,elapsed_seconds=v_total_s,current_amount=v_amount,updated_at=now() where id=v_s.id;
  insert into public.driver_taximeter_points(session_id,driver_id,lat,lng,distance_from_prev_m,accepted) values(v_s.id,v_uid,p_lat,p_lng,v_step,v_accept);
  return jsonb_build_object('ok',true,'session_id',v_s.id,'status','running','amount',v_amount,'distance_m',v_distance,'elapsed_seconds',v_total_s,'point_accepted',v_accept);
end;
$$;
revoke all on function public.tick_driver_taximeter(uuid,double precision,double precision) from public,anon;
grant execute on function public.tick_driver_taximeter(uuid,double precision,double precision) to authenticated;

create or replace function public.finish_driver_taximeter(p_session_id uuid,p_lat double precision,p_lng double precision,p_payment_method text default null)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_uid uuid:=auth.uid(); v_tick jsonb; v_amount numeric; v_distance numeric; v_elapsed integer;
begin
  if v_uid is null then raise exception 'Não autenticado'; end if;
  perform 1 from public.driver_taximeter_sessions where id=p_session_id and driver_id=v_uid and status='running';
  if not found then raise exception 'Taxímetro não está em andamento'; end if;
  v_tick:=public.tick_driver_taximeter(p_session_id,p_lat,p_lng);
  select current_amount,distance_m,elapsed_seconds into v_amount,v_distance,v_elapsed from public.driver_taximeter_sessions where id=p_session_id and driver_id=v_uid for update;
  update public.driver_taximeter_sessions set status='finished',ended_at=now(),end_lat=p_lat,end_lng=p_lng,final_amount=v_amount,payment_method=nullif(trim(coalesce(p_payment_method,'')),''),updated_at=now() where id=p_session_id and driver_id=v_uid;
  return jsonb_build_object('ok',true,'session_id',p_session_id,'status','finished','final_amount',v_amount,'distance_m',v_distance,'elapsed_seconds',v_elapsed,'payment_method',nullif(trim(coalesce(p_payment_method,'')),''));
end;
$$;
revoke all on function public.finish_driver_taximeter(uuid,double precision,double precision,text) from public,anon;
grant execute on function public.finish_driver_taximeter(uuid,double precision,double precision,text) to authenticated;

create or replace function public.cancel_driver_taximeter(p_session_id uuid)
returns jsonb language plpgsql security definer set search_path to 'public','pg_temp' as $$
declare v_uid uuid:=auth.uid();
begin
  if v_uid is null then raise exception 'Não autenticado'; end if;
  update public.driver_taximeter_sessions set status='cancelled',ended_at=now(),updated_at=now() where id=p_session_id and driver_id=v_uid and status='running';
  if not found then raise exception 'Taxímetro não está em andamento'; end if;
  return jsonb_build_object('ok',true,'session_id',p_session_id,'status','cancelled');
end;
$$;
revoke all on function public.cancel_driver_taximeter(uuid) from public,anon;
grant execute on function public.cancel_driver_taximeter(uuid) to authenticated;
