'use client'

import Link from 'next/link'
import {useEffect,useState} from 'react'
import {usePathname} from 'next/navigation'
import RoleGate from '@/components/RoleGate'
import LogoutButton from '@/components/LogoutButton'
import {supabase} from '@/lib/supabase'

type NavItem={href:string;label:string;permission?:string|string[]}
type CollectionState={overdue_days:number;open_overdue_amount:number;allow_new_drivers:boolean;allow_new_rides:boolean;operation_suspended:boolean;license_status:string}
const core:NavItem[]=[
 {href:'/franqueado',label:'📊 Dashboard'},
 {href:'/franqueado/chamadas',label:'📲 Chamar corrida',permission:'operation'},
 {href:'/franqueado/cadastros',label:'👥 Motoristas e Passageiros',permission:['drivers','users']},
 {href:'/franqueado/operacao',label:'🛣️ Corridas',permission:'operation'},
 {href:'/franqueado/mapa',label:'🗺️ Motoristas Online / Mapa',permission:'operation'},
 {href:'/franqueado/categorias',label:'💰 Tarifas Locais',permission:'pricing'},
 {href:'/franqueado/taximetro',label:'🚕 Tarifas do Taxímetro',permission:'pricing'},
 {href:'/franqueado/anuncios',label:'🎯 Promoções e Cupons',permission:'marketing'},
 {href:'/franqueado/notificacoes',label:'🔔 Notificações',permission:['marketing','support']},
 {href:'/franqueado/pagamentos',label:'💳 Financeiro',permission:'finance'},
 {href:'/franqueado/fatura',label:'🧾 Fatura CLICK-GO',permission:'finance'},
 {href:'/franqueado/relatorios',label:'📈 Relatórios',permission:['finance','operation']},
 {href:'/franqueado/suporte',label:'💬 Chamados',permission:'support'},
 {href:'/franqueado/logs',label:'🛡️ Logs',permission:['settings','support']},
 {href:'/franqueado/configuracoes',label:'⚙️ Configurações da Operação',permission:['settings','pricing','finance']},
]
const more:NavItem[]=[
 {href:'/franqueado/documentos',label:'Documentos de motoristas',permission:'drivers'},
 {href:'/franqueado/cancelamentos',label:'Cancelamentos',permission:'operation'},
 {href:'/franqueado/repasse',label:'Repasses',permission:'finance'},
 {href:'/franqueado/equipe',label:'Equipe e permissões',permission:'settings'},
 {href:'/franqueado/seguranca',label:'Segurança',permission:['operation','support']},
 {href:'/franqueado/carteiras',label:'Carteiras',permission:'finance'},
]
const css=`
.regional-shell{min-height:100vh;background:#f6f7f9;color:#171717;display:grid;grid-template-columns:248px minmax(0,1fr)}
.regional-sidebar{height:100vh;position:sticky;top:0;border-right:1px solid #e2e2e2;background:#111;padding:20px 14px;overflow:auto;display:flex;flex-direction:column}.regional-brand{display:flex;align-items:center;gap:10px;margin:0 6px 22px;color:#fff}.regional-brand span{width:42px;height:42px;border-radius:12px;background:#ffd400;color:#000;display:grid;place-items:center;font-weight:950}.regional-brand strong{display:block;font-size:17px}.regional-brand small{display:block;color:#a5a5a5;font-size:11px;margin-top:2px}
.regional-nav{display:grid;gap:4px}.regional-nav>a,.regional-more a{display:block;padding:10px 11px;border-radius:9px;color:#c8c8c8;font-size:13px;font-weight:650}.regional-nav>a:hover,.regional-more a:hover{background:#202020;color:#fff}.regional-nav>a.active,.regional-more a.active{background:#ffd400;color:#000}.regional-more{margin-top:8px;border-top:1px solid #2b2b2b;padding-top:8px}.regional-more summary{cursor:pointer;list-style:none;color:#888;font-size:11px;text-transform:uppercase;letter-spacing:.08em;padding:9px 11px}.regional-more summary::-webkit-details-marker{display:none}.regional-more summary:after{content:'+';float:right}.regional-more[open] summary:after{content:'−'}.regional-more div{display:grid;gap:2px;padding-left:4px}.regional-logout{width:100%;margin-top:12px;border:1px solid #443434;background:#1b1010;color:#ffb4b4;border-radius:9px;padding:10px 12px;font-weight:850;cursor:pointer}.regional-logout:hover{background:#291313;border-color:#7f2b2b;color:#fff}.regional-logout:disabled{opacity:.6;cursor:wait}.regional-sidebar-foot{margin-top:auto;padding:14px 7px 2px;border-top:1px solid #2b2b2b}.regional-sidebar-foot span{display:flex;align-items:center;gap:6px;color:#8bd99c;font-size:9px}.regional-sidebar-foot b{display:block;color:#e8e8e8;font-size:10px;margin-top:5px}.regional-sidebar-foot small{display:block;color:#787878;font-size:8px;margin-top:2px}
.regional-main{min-width:0;padding:28px}.regional-home{max-width:1280px;margin:0 auto}.regional-heading{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:22px}.regional-heading h1{font-size:30px;margin:4px 0}.regional-heading p{margin:0;color:#6d6d6d;font-size:14px}.regional-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.regional-kpi{background:#fff;border:1px solid #e4e4e4;border-radius:14px;padding:16px}.regional-kpi span{display:block;color:#777;font-size:12px}.regional-kpi strong{display:block;font-size:27px;margin:8px 0 4px}.regional-kpi small{color:#777;font-size:11px}.regional-alert{padding:12px 14px;border:1px solid #e3c600;background:#fff9cf;color:#5d4e00;border-radius:12px;margin-bottom:14px}.regional-license-banner{max-width:1280px;margin:0 auto 14px;padding:13px 15px;border-radius:12px;font-size:13px}.regional-license-banner strong{display:block;margin-bottom:3px}.regional-license-banner.warning{background:#fff8ce;border:1px solid #e2c700;color:#5c4b00}.regional-license-banner.danger{background:#fff0f0;border:1px solid #d44;color:#841414}.regional-actions{margin-top:24px}.regional-action-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.regional-action{position:relative;min-height:92px;padding:16px 42px 16px 16px;border:1px solid #e2e2e2;background:#fff;border-radius:14px}.regional-action:hover{border-color:#c8c8c8}.regional-action strong{display:block;font-size:15px;margin-bottom:5px}.regional-action span{display:block;color:#777;font-size:12px;line-height:1.45}.regional-action b{position:absolute;right:16px;top:50%;transform:translateY(-50%);color:#b99700;font-size:19px}
@media(max-width:1000px){.regional-kpis{grid-template-columns:repeat(2,1fr)}.regional-action-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:820px){.regional-shell{display:block}.regional-sidebar{height:auto;position:sticky;top:0;z-index:50;padding:10px 12px;display:flex;flex-direction:row;align-items:center;gap:10px;overflow-x:auto;border-right:0;border-bottom:1px solid #242424}.regional-brand{margin:0;flex:0 0 auto}.regional-brand div{display:none}.regional-nav{display:flex;gap:3px;min-width:max-content}.regional-nav>a{white-space:nowrap}.regional-more,.regional-sidebar-foot{display:none}.regional-logout{width:auto;min-width:max-content;margin:0;padding:9px 11px;white-space:nowrap;flex:0 0 auto}.regional-main{padding:18px}}@media(max-width:620px){.regional-heading{align-items:flex-start}.regional-heading h1{font-size:24px}.regional-kpis,.regional-action-grid{grid-template-columns:1fr}.regional-main{padding:14px}.regional-heading .button{padding:9px 10px;font-size:12px}}
`

export default function FranchiseLayout({children}:{children:React.ReactNode}){
 const pathname=usePathname(),[role,setRole]=useState('franchise_admin'),[staffRole,setStaffRole]=useState(''),[permissions,setPermissions]=useState<Record<string,boolean>>({}),[configVersion,setConfigVersion]=useState(0),[license,setLicense]=useState(''),[collection,setCollection]=useState<CollectionState|null>(null)
 useEffect(()=>{let alive=true;(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user||!alive)return;const r=String(user.app_metadata?.role||'franchise_admin');setRole(r);const{data:p}=await supabase.from('profiles').select('franchise_id').eq('id',user.id).maybeSingle();const fid=String(p?.franchise_id||user.app_metadata?.franchise_id||'');if(r==='operator'){const{data:s}=await supabase.from('franchise_staff_permissions').select('staff_role,permissions').eq('profile_id',user.id).maybeSingle();if(s){setStaffRole(String(s.staff_role||''));setPermissions((s.permissions||{}) as Record<string,boolean>)}}if(fid){const[c,b]=await Promise.all([supabase.rpc('get_app_configuration_state',{p_franchise_id:fid,p_city_id:null}),supabase.rpc('get_franchise_collection_state',{p_franchise_id:fid})]);if(c.data){setConfigVersion(Number(c.data.version||0));setLicense(String(c.data.license_status||''))}if(b.data)setCollection(b.data as CollectionState)}})();return()=>{alive=false}},[])
 if(pathname==='/franqueado/login'||pathname==='/franqueado/trocar-senha-temporaria')return <>{children}</>
 const can=(item:NavItem)=>{if(role==='franchise_admin')return true;if(!item.permission)return true;const list=Array.isArray(item.permission)?item.permission:[item.permission];return list.some(p=>permissions[p]===true)}
 const visibleCore=core.filter(can),visibleMore=more.filter(can),active=(href:string)=>pathname===href||pathname.startsWith(href+'/'),moreOpen=visibleMore.some(item=>active(item.href)),title=role==='franchise_admin'?'Franqueado':staffRole==='manager'?'Gerente':staffRole==='financial'?'Financeiro':staffRole==='support'?'Suporte':staffRole==='marketing'?'Marketing':'Operador'
 return <RoleGate role={['franchise_admin','operator']} loginPath="/franqueado/login"><style>{css}</style><div className="regional-shell"><aside className="regional-sidebar"><Link href="/franqueado" className="regional-brand"><span>CG</span><div><strong>CLICK-GO</strong><small>Painel {title}</small></div></Link><nav className="regional-nav">{visibleCore.map(item=><Link key={item.href} href={item.href} className={active(item.href)?'active':''}>{item.label}</Link>)}{visibleMore.length>0&&<details className="regional-more" open={moreOpen}><summary>Mais opções</summary><div>{visibleMore.map(item=><Link key={item.href} href={item.href} className={active(item.href)?'active':''}>{item.label}</Link>)}</div></details>}</nav><LogoutButton loginPath="/franqueado/login" className="regional-logout"/><div className="regional-sidebar-foot"><span>● Operação sincronizada</span><b>Configuração v{configVersion}</b><small>Licença: {license||'verificando...'}</small></div></aside><main className="regional-main">{collection?.operation_suspended?<div className="regional-license-banner danger"><strong>Sua licença está suspensa. Corridas bloqueadas.</strong>Regularize a fatura CLICK-GO ou entre em contato com a Matriz. Motoristas desta franquia não podem operar enquanto a suspensão estiver ativa.</div>:collection&&collection.overdue_days>0?<div className="regional-license-banner warning"><strong>Fatura CLICK-GO em atraso: {collection.overdue_days} dia(s).</strong>{!collection.allow_new_drivers?'Novos motoristas estão bloqueados. ':''}{!collection.allow_new_rides?'Novas corridas estão bloqueadas. ':''}Consulte Financeiro → Fatura CLICK-GO.</div>:null}{children}</main></div></RoleGate>
}
