'use client'

import Link from 'next/link'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import RealtimeMapData from '@/components/RealtimeMapData'

type Profile={id:string;full_name:string|null;franchise_id:string|null}
type CityJoin={cities:{name:string;state:string}[]}
type RideFare={final_fare:number|string|null}
type Summary={online:number;activeRides:number;pendingDrivers:number;todayRevenue:number}
type Action={href:string;title:string;desc:string;permission?:string|string[]}
const brl=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0)

export default function FranchiseHome(){
 const[me,setMe]=useState<Profile|null>(null),[cities,setCities]=useState<string[]>([]),[summary,setSummary]=useState<Summary>({online:0,activeRides:0,pendingDrivers:0,todayRevenue:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[isAdmin,setIsAdmin]=useState(true),[permissions,setPermissions]=useState<Record<string,boolean>>({})
 useEffect(()=>{void load()},[])
 async function load(){setLoading(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão não encontrada.');const role=String(user.app_metadata?.role||'franchise_admin');setIsAdmin(role==='franchise_admin');if(role==='operator'){const{data:s}=await supabase.from('franchise_staff_permissions').select('permissions').eq('profile_id',user.id).maybeSingle();setPermissions((s?.permissions||{}) as Record<string,boolean>)}const{data:profile,error:pe}=await supabase.from('profiles').select('id,full_name,franchise_id').eq('id',user.id).single();if(pe)throw pe;const current=profile as Profile;setMe(current);if(!current.franchise_id)throw new Error('Franquia não vinculada a este acesso.');const start=new Date();start.setHours(0,0,0,0);const[cityRes,onlineRes,activeRes,pendingRes,revenueRes]=await Promise.all([supabase.from('franchise_cities').select('cities(name,state)').eq('franchise_id',current.franchise_id),supabase.from('drivers').select('id',{count:'exact',head:true}).eq('franchise_id',current.franchise_id).eq('online',true),supabase.from('rides').select('id',{count:'exact',head:true}).eq('franchise_id',current.franchise_id).in('status',['accepted','driver_arriving','arrived','in_progress']),supabase.from('drivers').select('id',{count:'exact',head:true}).eq('franchise_id',current.franchise_id).eq('status','pending'),supabase.from('rides').select('final_fare').eq('franchise_id',current.franchise_id).eq('status','completed').gte('completed_at',start.toISOString())]);if(cityRes.error)throw cityRes.error;const cityNames=((cityRes.data||[]) as CityJoin[]).map(r=>r.cities?.[0]).filter((c):c is{name:string;state:string}=>Boolean(c)).map(c=>`${c.name}/${c.state}`);const todayRevenue=((revenueRes.data||[]) as RideFare[]).reduce((sum,r)=>sum+Number(r.final_fare||0),0);setCities(cityNames);setSummary({online:onlineRes.count||0,activeRides:activeRes.count||0,pendingDrivers:pendingRes.count||0,todayRevenue})}catch(err){setError(err instanceof Error?err.message:'Erro ao carregar o painel regional.')}finally{setLoading(false)}}
 const can=(permission?:string|string[])=>{if(isAdmin||!permission)return true;const list=Array.isArray(permission)?permission:[permission];return list.some(p=>permissions[p]===true)}
 const cards=[['Motoristas online',String(summary.online),'agora'],['Corridas em andamento',String(summary.activeRides),'ao vivo'],['Cadastros pendentes',String(summary.pendingDrivers),'motoristas'],['Faturamento hoje',brl(summary.todayRevenue),'corridas concluídas']]
 const actions:Action[]=[{href:'/franqueado/operacao',title:'Corridas',desc:'Acompanhar a operação',permission:'operation'},{href:'/franqueado/cadastros',title:'Pessoas',desc:'Motoristas e passageiros',permission:['drivers','users']},{href:'/franqueado/pagamentos',title:'Financeiro',desc:'Recebimentos e movimentações',permission:'finance'},{href:'/franqueado/suporte',title:'Suporte',desc:'Atender chamados',permission:'support'},{href:'/franqueado/categorias',title:'Tarifas',desc:'Valores da operação',permission:'pricing'},{href:'/franqueado/equipe',title:'Equipe',desc:'Acessos e permissões',permission:'settings'}]
 const visibleActions=actions.filter(a=>can(a.permission)).slice(0,4),canMap=can('operation')
 return <div className="simple-page"><div className="simple-header"><div><div className="simple-eyebrow">CLICK-GO Regional</div><h1>{cities[0]||'Minha operação'}</h1><p>Olá, {me?.full_name?.split(' ')[0]||'Administrador'}. Aqui está o que importa agora.</p></div><button className="simple-btn" onClick={()=>void load()} disabled={loading}>{loading?'Atualizando…':'Atualizar'}</button></div>{error&&<div className="simple-card" style={{marginBottom:12}}>{error}</div>}<div className="simple-kpis">{cards.map(([label,value,hint])=><div className="simple-kpi" key={label}><span>{label}</span><strong>{loading?'—':value}</strong><small>{hint}</small></div>)}</div><div className="simple-grid-2">{canMap?<div className="simple-card"><div className="simple-section-head"><div><h2>Mapa da operação</h2><p>Motoristas e atividade em tempo real.</p></div><Link className="simple-btn" href="/franqueado/mapa">Abrir mapa</Link></div><RealtimeMapData compact/></div>:<div className="simple-card"><h2>Resumo da operação</h2><p>Seu acesso mostra apenas as informações necessárias para a sua função.</p><div className="simple-attention"><div className="simple-attention-row"><span>Corridas em andamento</span><strong>{summary.activeRides}</strong></div><div className="simple-attention-row"><span>Motoristas online</span><strong>{summary.online}</strong></div></div></div>}<div className="simple-card"><h2>Precisa da sua atenção</h2><p>Prioridades antes de qualquer configuração.</p><div className="simple-attention"><div className={`simple-attention-row ${summary.pendingDrivers?'warn':''}`}><span>Motoristas aguardando análise</span><strong>{summary.pendingDrivers}</strong></div><div className={`simple-attention-row ${summary.activeRides?'':''}`}><span>Corridas acontecendo agora</span><strong>{summary.activeRides}</strong></div></div><div className="simple-quick">{visibleActions.map(a=><Link href={a.href} key={a.href}><strong>{a.title}</strong><span>{a.desc}</span></Link>)}</div></div></div></div>
}
