'use client'

import Link from 'next/link'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import RealtimeMapData from '@/components/RealtimeMapData'

type Profile={id:string;full_name:string|null;franchise_id:string|null}
type CityJoin={cities:{name:string;state:string}[]}
type RideFare={final_fare:number|string|null}
type Summary={online:number;activeRides:number;pendingDrivers:number;todayRevenue:number}
const brl=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0)

export default function FranchiseHome(){
 const[me,setMe]=useState<Profile|null>(null),[cities,setCities]=useState<string[]>([]),[summary,setSummary]=useState<Summary>({online:0,activeRides:0,pendingDrivers:0,todayRevenue:0}),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{void load()},[])
 async function load(){setLoading(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão não encontrada.');const{data:profile,error:pe}=await supabase.from('profiles').select('id,full_name,franchise_id').eq('id',user.id).single();if(pe)throw pe;const current=profile as Profile;setMe(current);if(!current.franchise_id)throw new Error('Franquia não vinculada a este acesso.');const start=new Date();start.setHours(0,0,0,0);const[cityRes,onlineRes,activeRes,pendingRes,revenueRes]=await Promise.all([supabase.from('franchise_cities').select('cities(name,state)').eq('franchise_id',current.franchise_id),supabase.from('drivers').select('id',{count:'exact',head:true}).eq('franchise_id',current.franchise_id).eq('online',true),supabase.from('rides').select('id',{count:'exact',head:true}).eq('franchise_id',current.franchise_id).in('status',['accepted','driver_arriving','arrived','in_progress']),supabase.from('drivers').select('id',{count:'exact',head:true}).eq('franchise_id',current.franchise_id).eq('status','pending'),supabase.from('rides').select('final_fare').eq('franchise_id',current.franchise_id).eq('status','completed').gte('completed_at',start.toISOString())]);if(cityRes.error)throw cityRes.error;if(onlineRes.error)throw onlineRes.error;if(activeRes.error)throw activeRes.error;if(pendingRes.error)throw pendingRes.error;if(revenueRes.error)throw revenueRes.error;const cityNames=((cityRes.data||[]) as CityJoin[]).map(r=>r.cities?.[0]).filter((c):c is{name:string;state:string}=>Boolean(c)).map(c=>`${c.name}/${c.state}`);const todayRevenue=((revenueRes.data||[]) as RideFare[]).reduce((sum,r)=>sum+Number(r.final_fare||0),0);setCities(cityNames);setSummary({online:onlineRes.count||0,activeRides:activeRes.count||0,pendingDrivers:pendingRes.count||0,todayRevenue})}catch(err){setError(err instanceof Error?err.message:'Erro ao carregar o painel regional.')}finally{setLoading(false)}}
 const cards=[{label:'Motoristas online',value:String(summary.online),hint:'agora'},{label:'Corridas em andamento',value:String(summary.activeRides),hint:'ao vivo'},{label:'Motoristas pendentes',value:String(summary.pendingDrivers),hint:'para revisar'},{label:'Faturamento hoje',value:brl(summary.todayRevenue),hint:'concluídas'}]
 const actions=[['/franqueado/motoristas','Motoristas','Editar, aprovar, bloquear, créditos e cobrança'],['/franqueado/cadastros','Novos cadastros','Cadastrar motorista ou passageiro'],['/franqueado/operacao','Corridas','Acompanhar e despachar'],['/franqueado/categorias','Tarifas','Preço base, km, minuto e mínima'],['/franqueado/pagamentos','Financeiro','Recebimentos e movimentações'],['/franqueado/equipe','Minha equipe','Acessos e permissões'],['/franqueado/anuncios','Promoções','Campanhas e anúncios']] as const
 return <div className="regional-home"><div className="regional-heading"><div><div className="eyebrow">Meu Dashboard</div><h1>{cities[0]||'CLICK-GO Regional'}</h1><p>{me?.full_name||'Administrador'}{cities.length>1?` · ${cities.join(' · ')}`:''}</p></div><button className="button secondary" onClick={()=>void load()} disabled={loading}>{loading?'Atualizando…':'Atualizar'}</button></div>{error&&<div className="regional-alert">{error}</div>}<div className="regional-kpis">{cards.map(card=><div className="regional-kpi" key={card.label}><span>{card.label}</span><strong>{loading?'—':card.value}</strong><small>{card.hint}</small></div>)}</div><RealtimeMapData compact/><div style={{display:'flex',justifyContent:'flex-end',marginTop:8}}><Link className="button secondary" href="/franqueado/mapa">Abrir mapa completo</Link></div><section className="regional-actions"><div className="section-heading"><div><h2>Acesso rápido</h2><p className="subtitle">Somente as funções mais usadas no dia a dia.</p></div></div><div className="regional-action-grid">{actions.map(([href,title,desc])=><Link href={href} key={href} className="regional-action"><strong>{title}</strong><span>{desc}</span><b>→</b></Link>)}</div></section></div>
}
