'use client'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {getMyFranchise} from '@/lib/myFranchise'

type City={id:string;name:string;state:string}
const empty={full_name:'',email:'',phone:'',password:'',city_id:''}
export default function Page(){
 const [rows,setRows]=useState<any[]>([]);const [docs,setDocs]=useState<any[]>([]);const [cities,setCities]=useState<City[]>([]);const [form,setForm]=useState(empty);const [msg,setMsg]=useState('');const [saving,setSaving]=useState(false);const [fid,setFid]=useState('')
 async function load(){try{const me=await getMyFranchise();setFid(me.franchiseId);const fc=await supabase.from('franchise_cities').select('city_id,cities(id,name,state)').eq('franchise_id',me.franchiseId);setCities((fc.data||[]).map((x:any)=>x.cities).filter(Boolean));const d=await supabase.from('drivers').select('id,status,online,rating,city_id,profiles(full_name,phone),cities(name,state)').eq('franchise_id',me.franchiseId).order('created_at',{ascending:false});if(d.error)throw d.error;setRows(d.data||[]);const ids=(d.data||[]).map((x:any)=>x.id);if(ids.length){const x=await supabase.from('driver_documents').select('*').in('driver_id',ids).order('created_at',{ascending:false});setDocs(x.data||[])}else setDocs([])}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load()},[])
 async function createDriver(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg('');try{const {data,error}=await supabase.functions.invoke('admin-users',{body:{action:'create_operational_user',user_role:'driver',full_name:form.full_name,email:form.email,phone:form.phone,password:form.password,city_id:form.city_id}});if(error)throw error;if(data?.error)throw new Error(data.error);setForm(empty);setMsg('Motorista cadastrado com sucesso.');await load()}catch(e:any){setMsg(e.message||'Não foi possível cadastrar o motorista.')}finally{setSaving(false)}}
 async function status(id:string,status:string){const {error}=await supabase.from('drivers').update({status,...(status==='blocked'?{online:false}:{} )}).eq('id',id).eq('franchise_id',fid);if(error)setMsg(error.message);else load()}
 async function review(id:string,status:string){const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('driver_documents').update({status,reviewed_by:user?.id||null,reviewed_at:new Date().toISOString()}).eq('id',id);if(error)setMsg(error.message);else load()}
 return <><div className="topbar"><div><div className="eyebrow">Operação</div><h1 className="title">Motoristas</h1><p className="subtitle">Cadastre, aprove documentos, bloqueie motoristas e acompanhe quem está online.</p></div></div>
 <div className="card"><h2>Cadastrar motorista</h2><form onSubmit={createDriver}><div className="form-grid"><div className="field"><label>Nome completo</label><input className="input" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></div><div className="field"><label>E-mail</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div className="field"><label>Telefone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></div><div className="field"><label>Senha temporária</label><input className="input" type="password" minLength={6} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></div><div className="field"><label>Cidade</label><select className="input" value={form.city_id} onChange={e=>setForm({...form,city_id:e.target.value})} required><option value="">Selecione</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></div></div><button className="button" disabled={saving} style={{marginTop:14}}>{saving?'Cadastrando...':'Cadastrar motorista'}</button></form></div>
 {msg&&<p className="empty">{msg}</p>}<div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Motorista</th><th>Cidade</th><th>Status</th><th>Online</th><th>Ações</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.profiles?.full_name||r.id.slice(0,8)}</td><td>{r.cities?`${r.cities.name}/${r.cities.state}`:'—'}</td><td>{r.status}</td><td>{r.online?'Sim':'Não'}</td><td><div className="toolbar"><button className="button secondary" onClick={()=>status(r.id,'approved')}>Aprovar</button><button className="button danger" onClick={()=>status(r.id,'blocked')}>Bloquear</button></div></td></tr>):<tr><td colSpan={5} className="empty">Nenhum motorista.</td></tr>}</tbody></table></div></div>
 <div className="section"><h2>Documentos</h2><div className="table-wrap"><table className="table"><thead><tr><th>Motorista</th><th>Documento</th><th>Status</th><th>Ações</th></tr></thead><tbody>{docs.length?docs.map(d=><tr key={d.id}><td>{d.driver_id.slice(0,8)}…</td><td>{d.document_type}</td><td>{d.status}</td><td><div className="toolbar"><button className="button secondary" onClick={()=>review(d.id,'approved')}>Aprovar</button><button className="button danger" onClick={()=>review(d.id,'rejected')}>Rejeitar</button></div></td></tr>):<tr><td colSpan={4} className="empty">Nenhum documento pendente.</td></tr>}</tbody></table></div></div></>}
