'use client'

import { useEffect,useMemo,useState } from 'react'
import { supabase } from '@/lib/supabase'

type City={id:string;name:string;state:string}
type GlobalPay={cash_enabled:boolean;pix_enabled:boolean;card_app_enabled:boolean;card_machine_enabled:boolean;card_credit_enabled:boolean;card_debit_enabled:boolean;app_card_gateway:string|null;card_surcharge_percentage:number|string;card_fee_bearer:string;installments_enabled:boolean;max_installments:number;franchise_can_manage:boolean}
type LocalPay={franchise_id:string;city_id:string;cash_enabled:boolean|null;pix_enabled:boolean|null;card_app_enabled:boolean|null;card_machine_enabled:boolean|null;card_credit_enabled:boolean|null;card_debit_enabled:boolean|null;app_card_gateway:string|null;card_surcharge_percentage:number|string|null;card_fee_bearer:string|null;installments_enabled:boolean|null;max_installments:number|null;locked_by_matrix:boolean}
type WalletGlobal={enabled:boolean;minimum_balance_to_receive:number|string;low_balance_threshold:number|string;default_ride_fee:number|string;franchise_can_set_ride_fee:boolean;franchise_manual_credit_enabled:boolean;franchise_manual_credit_limit:number|string|null}
type WalletLocal={franchise_id:string;ride_fee:number|string|null;minimum_balance_to_receive:number|string|null;low_balance_threshold:number|string|null;locked_by_matrix:boolean}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:18}
const input:React.CSSProperties={width:'100%',background:'#0d0d0d',color:'#fff',border:'1px solid #333',borderRadius:10,padding:'10px 11px'}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',border:0,borderRadius:9,padding:'10px 13px',fontWeight:800,cursor:'pointer'}

export default function FranchisePaymentsPage(){
 const[fid,setFid]=useState(''),[cities,setCities]=useState<City[]>([]),[selectedCity,setSelectedCity]=useState(''),[globalPay,setGlobalPay]=useState<GlobalPay|null>(null),[locals,setLocals]=useState<LocalPay[]>([]),[walletGlobal,setWalletGlobal]=useState<WalletGlobal|null>(null),[walletLocal,setWalletLocal]=useState<WalletLocal|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const[form,setForm]=useState({cash:true,pix:true,cardApp:false,cardMachine:false,credit:true,debit:false,gateway:'',surcharge:'0',bearer:'passenger',installments:false,maxInstallments:'1'})
 const[walletForm,setWalletForm]=useState({rideFee:'0',minimum:'0.01',low:'5'})
 useEffect(()=>{load()},[])
 async function load(){setBusy(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Faça login.');const{data:p,error:pe}=await supabase.from('profiles').select('role,franchise_id').eq('id',user.id).single();if(pe)throw pe;if(p?.role!=='franchise_admin'||!p.franchise_id)throw new Error('Acesso exclusivo do franqueado.');setFid(p.franchise_id);const[{data:fc,error:fce},{data:g,error:ge},{data:l,error:le},{data:wg,error:wge},{data:wl,error:wle}]=await Promise.all([supabase.from('franchise_cities').select('city_id,cities(id,name,state)').eq('franchise_id',p.franchise_id),supabase.from('platform_payment_settings').select('*').eq('scope','global').single(),supabase.from('franchise_city_payment_settings').select('*').eq('franchise_id',p.franchise_id),supabase.from('platform_operational_wallet_settings').select('*').eq('scope','global').single(),supabase.from('franchise_operational_wallet_settings').select('*').eq('franchise_id',p.franchise_id).maybeSingle()]);if(fce)throw fce;if(ge)throw ge;if(le)throw le;if(wge)throw wge;if(wle)throw wle;const cs=(fc||[]).map((x:any)=>x.cities).filter(Boolean) as City[];setCities(cs);setGlobalPay(g as GlobalPay);setLocals((l||[]) as LocalPay[]);setWalletGlobal(wg as WalletGlobal);setWalletLocal(wl as WalletLocal|null);const cid=selectedCity||cs[0]?.id||'';setSelectedCity(cid);applyPaymentForm(cid,(l||[]) as LocalPay[],g as GlobalPay);setWalletForm({rideFee:String(wl?.ride_fee??wg?.default_ride_fee??0),minimum:String(wl?.minimum_balance_to_receive??wg?.minimum_balance_to_receive??0.01),low:String(wl?.low_balance_threshold??wg?.low_balance_threshold??5)})}catch(e:any){setMsg(e.message||'Erro ao carregar configurações.')}finally{setBusy(false)}}
 function applyPaymentForm(cid:string,list=locals,g=globalPay){if(!g)return;const l=list.find(x=>x.city_id===cid);setForm({cash:l?.cash_enabled??g.cash_enabled,pix:l?.pix_enabled??g.pix_enabled,cardApp:l?.card_app_enabled??g.card_app_enabled,cardMachine:l?.card_machine_enabled??g.card_machine_enabled,credit:l?.card_credit_enabled??g.card_credit_enabled,debit:l?.card_debit_enabled??g.card_debit_enabled,gateway:l?.app_card_gateway??g.app_card_gateway??'',surcharge:String(l?.card_surcharge_percentage??g.card_surcharge_percentage??0),bearer:l?.card_fee_bearer??g.card_fee_bearer??'passenger',installments:l?.installments_enabled??g.installments_enabled,maxInstallments:String(l?.max_installments??g.max_installments??1)})}
 const local=useMemo(()=>locals.find(x=>x.city_id===selectedCity),[locals,selectedCity]);
 async function savePayment(){if(!globalPay||!selectedCity||!fid)return;if(!globalPay.franchise_can_manage){setMsg('A Matriz bloqueou alterações de meios de pagamento pelos franqueados.');return}if(local?.locked_by_matrix){setMsg('Esta cidade está bloqueada pela Matriz.');return}setBusy(true);const{error}=await supabase.from('franchise_city_payment_settings').upsert({franchise_id:fid,city_id:selectedCity,cash_enabled:form.cash,pix_enabled:form.pix,card_app_enabled:form.cardApp,card_machine_enabled:form.cardMachine,card_credit_enabled:form.credit,card_debit_enabled:form.debit,app_card_gateway:form.gateway||null,card_surcharge_percentage:Number(form.surcharge||0),card_fee_bearer:form.bearer,installments_enabled:form.installments,max_installments:Number(form.maxInstallments||1),locked_by_matrix:false,updated_at:new Date().toISOString()},{onConflict:'franchise_id,city_id'});setBusy(false);if(error){setMsg(error.message);return}setMsg('Configurações de pagamento salvas. As opções bloqueadas globalmente pela Matriz continuam indisponíveis.');await load()}
 async function saveWallet(){if(!fid||!walletGlobal)return;if(walletLocal?.locked_by_matrix){setMsg('As regras da carteira desta franquia estão bloqueadas pela Matriz.');return}setBusy(true);const payload={franchise_id:fid,ride_fee:walletGlobal.franchise_can_set_ride_fee?Number(walletForm.rideFee||0):walletLocal?.ride_fee??null,minimum_balance_to_receive:Number(walletForm.minimum||0),low_balance_threshold:Number(walletForm.low||0),locked_by_matrix:false,updated_at:new Date().toISOString()};const{error}=await supabase.from('franchise_operational_wallet_settings').upsert(payload,{onConflict:'franchise_id'});setBusy(false);if(error){setMsg(error.message);return}setMsg('Regras da carteira operacional atualizadas.');await load()}
 const disabled=!globalPay?.franchise_can_manage||!!local?.locked_by_matrix;
 const toggle=(key:keyof typeof form,label:string,globalAllowed=true)=><label style={{...box,padding:12,display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',opacity:globalAllowed?1:.5}}><span>{label}{!globalAllowed&&<small style={{display:'block',color:'#fbbf24'}}>Bloqueado pela Matriz</small>}</span><input type="checkbox" checked={Boolean(form[key])} disabled={disabled||!globalAllowed} onChange={e=>setForm({...form,[key]:e.target.checked})}/></label>
 return <main style={{minHeight:'100vh',background:'#080808',color:'#fff',padding:20}}><div style={{maxWidth:1150,margin:'0 auto',display:'grid',gap:14}}>
  <div><div className="eyebrow">Configurações</div><h1>Pagamentos e carteira operacional</h1><p className="subtitle">A Matriz define o limite máximo de liberdade; a franquia configura somente o que estiver permitido.</p></div>
  <section style={box}><h2>Meios de pagamento por cidade</h2><label style={{display:'grid',gap:6,maxWidth:360}}>Cidade<select style={input} value={selectedCity} onChange={e=>{setSelectedCity(e.target.value);applyPaymentForm(e.target.value)}}>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></label>{local?.locked_by_matrix&&<p style={{color:'#fbbf24'}}>Esta configuração foi bloqueada pela Matriz.</p>}{globalPay&&!globalPay.franchise_can_manage&&<p style={{color:'#fbbf24'}}>A Matriz desativou a edição de pagamentos pelos franqueados.</p>}
   <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9,marginTop:14}}>{toggle('cash','Dinheiro',!!globalPay?.cash_enabled)}{toggle('pix','PIX',!!globalPay?.pix_enabled)}{toggle('cardApp','Cartão pelo aplicativo',!!globalPay?.card_app_enabled)}{toggle('cardMachine','Cartão na maquininha do motorista',!!globalPay?.card_machine_enabled)}{toggle('credit','Cartão de crédito',!!globalPay?.card_credit_enabled)}{toggle('debit','Cartão de débito',!!globalPay?.card_debit_enabled)}{toggle('installments','Permitir parcelamento',!!globalPay?.installments_enabled)}</div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:9,marginTop:12}}><label>Gateway<input style={input} value={form.gateway} disabled={disabled||!globalPay?.card_app_enabled} onChange={e=>setForm({...form,gateway:e.target.value})} placeholder="ex.: Mercado Pago"/></label><label>Acréscimo cartão (%)<input type="number" step="0.01" style={input} value={form.surcharge} disabled={disabled} onChange={e=>setForm({...form,surcharge:e.target.value})}/></label><label>Quem paga a taxa<select style={input} value={form.bearer} disabled={disabled} onChange={e=>setForm({...form,bearer:e.target.value})}><option value="passenger">Passageiro</option><option value="driver">Motorista</option><option value="franchise">Franqueado</option><option value="platform">Matriz</option></select></label><label>Máx. parcelas<input type="number" min={1} max={24} style={input} value={form.maxInstallments} disabled={disabled||!form.installments} onChange={e=>setForm({...form,maxInstallments:e.target.value})}/></label></div><button style={{...btn,marginTop:12}} disabled={busy||disabled||!selectedCity} onClick={savePayment}>Salvar pagamentos da cidade</button>
  </section>
  <section style={box}><h2>Carteira operacional</h2><p className="subtitle">Saldo usado para liberar chamadas e cobrir taxas/comissões recebidas diretamente pelo motorista.</p>{walletLocal?.locked_by_matrix&&<p style={{color:'#fbbf24'}}>Regras bloqueadas pela Matriz.</p>}<div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:10}}><label>Taxa operacional por corrida<input type="number" step="0.01" style={input} value={walletForm.rideFee} disabled={busy||!!walletLocal?.locked_by_matrix||!walletGlobal?.franchise_can_set_ride_fee} onChange={e=>setWalletForm({...walletForm,rideFee:e.target.value})}/>{walletGlobal&&!walletGlobal.franchise_can_set_ride_fee&&<small style={{color:'#fbbf24'}}>Definida somente pela Matriz</small>}</label><label>Saldo mínimo para receber corrida<input type="number" step="0.01" style={input} value={walletForm.minimum} disabled={busy||!!walletLocal?.locked_by_matrix} onChange={e=>setWalletForm({...walletForm,minimum:e.target.value})}/></label><label>Alerta de saldo baixo<input type="number" step="0.01" style={input} value={walletForm.low} disabled={busy||!!walletLocal?.locked_by_matrix} onChange={e=>setWalletForm({...walletForm,low:e.target.value})}/></label></div><div style={{color:'#9ca3af',marginTop:10}}>Crédito manual pelo franqueado: <b>{walletGlobal?.franchise_manual_credit_enabled?'permitido':'bloqueado'}</b>{walletGlobal?.franchise_manual_credit_limit?` · limite por lançamento R$ ${Number(walletGlobal.franchise_manual_credit_limit).toFixed(2)}`:''}</div><button style={{...btn,marginTop:12}} disabled={busy||!!walletLocal?.locked_by_matrix} onClick={saveWallet}>Salvar regras da carteira</button></section>
  {msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b'}}>{msg}</div>}
 </div></main>
}
