import {useEffect,useState} from 'react'
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native'
import * as Location from 'expo-location'
import {router} from 'expo-router'
import {supabase} from '@/lib/supabase'
import {colors} from '@/lib/theme'

type Category={id:string;name:string;base_fare:number;minimum_fare:number;price_per_km:number;price_per_minute:number;city_id:string;franchise_id:string|null}
export default function Home(){
 const[origin,setOrigin]=useState('Localizando...');const[coords,setCoords]=useState<{lat:number;lng:number}|null>(null);const[destination,setDestination]=useState('');const[categories,setCategories]=useState<Category[]>([]);const[selected,setSelected]=useState<Category|null>(null);const[cityId,setCityId]=useState<string|null>(null)
 useEffect(()=>{(async()=>{const {status}=await Location.requestForegroundPermissionsAsync();if(status!=='granted'){setOrigin('Permissão de localização negada');return}const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setCoords({lat:p.coords.latitude,lng:p.coords.longitude});const r=await Location.reverseGeocodeAsync({latitude:p.coords.latitude,longitude:p.coords.longitude});const a=r[0];const city=a?.city||a?.subregion||'';const state=a?.region||'';setOrigin([a?.street,a?.streetNumber,city].filter(Boolean).join(', ')||'Sua localização');if(city){const {data:c}=await supabase.from('cities').select('id').ilike('name',city).eq('active',true).limit(1).maybeSingle();if(c?.id){setCityId(c.id);const {data:cats}=await supabase.from('ride_categories').select('id,name,base_fare,minimum_fare,price_per_km,price_per_minute,city_id,franchise_id').eq('city_id',c.id).eq('active',true);setCategories((cats||[]) as Category[]);setSelected((cats?.[0] as Category)||null)}}}})()},[])
 function estimate(c:Category){return Math.max(Number(c.minimum_fare||0),Number(c.base_fare||0))}
 async function requestRide(){if(!coords||!destination||!selected||!cityId){Alert.alert('Complete a corrida','Informe o destino e escolha uma categoria disponível.');return}const {data:{user}}=await supabase.auth.getUser();if(!user)return router.replace('/login');const {data,error}=await supabase.from('rides').insert({passenger_id:user.id,franchise_id:selected.franchise_id,city_id:cityId,category_id:selected.id,status:'requested',origin_label:origin,origin_lat:coords.lat,origin_lng:coords.lng,destination_label:destination,destination_lat:coords.lat,destination_lng:coords.lng,estimated_fare:estimate(selected)}).select('id').single();if(error)Alert.alert('Não foi possível solicitar',error.message);else router.push({pathname:'/ride',params:{id:data.id}})}
 return <ScrollView style={s.screen} contentContainerStyle={{paddingBottom:40}}><View style={s.header}><Text style={s.logo}>CLICK-GO</Text><Pressable onPress={()=>router.push('/history')}><Text style={s.link}>Histórico</Text></Pressable></View><View style={s.map}><Text style={s.mapPin}>●</Text><Text style={s.mapText}>GPS ativo</Text><Text style={s.mapSub}>{origin}</Text></View><View style={s.card}><Text style={s.label}>Para onde você vai?</Text><TextInput style={s.input} placeholder="Digite o destino" placeholderTextColor={colors.muted} value={destination} onChangeText={setDestination}/><View style={s.shortcuts}><Pressable onPress={()=>router.push('/favorites')}><Text style={s.chip}>★ Favoritos</Text></Pressable><Pressable onPress={()=>router.push('/schedule')}><Text style={s.chip}>◷ Agendar</Text></Pressable><Pressable onPress={()=>router.push('/wallet')}><Text style={s.chip}>$ Pagamento</Text></Pressable></View></View><Text style={s.section}>Escolha uma categoria</Text>{categories.length?categories.map(c=><Pressable key={c.id} onPress={()=>setSelected(c)} style={[s.category,selected?.id===c.id&&s.selected]}><View><Text style={s.categoryName}>{c.name}</Text><Text style={s.categoryMeta}>Estimativa inicial • chegada calculada ao localizar motoristas</Text></View><Text style={s.price}>R$ {estimate(c).toFixed(2).replace('.',',')}</Text></Pressable>):<View style={s.card}><Text style={s.muted}>Nenhuma categoria disponível nesta cidade.</Text></View>}<Pressable style={[s.button,!selected&&{opacity:.5}]} onPress={requestRide}><Text style={s.buttonText}>Solicitar motorista</Text></Pressable><View style={s.bottom}><Pressable onPress={()=>router.push('/safety')}><Text style={s.bottomLink}>Segurança</Text></Pressable><Pressable onPress={()=>router.push('/support')}><Text style={s.bottomLink}>Suporte</Text></Pressable></View></ScrollView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.black,padding:18},header:{marginTop:42,marginBottom:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},logo:{color:colors.yellow,fontSize:26,fontWeight:'900'},link:{color:colors.yellow,fontWeight:'700'},map:{height:210,backgroundColor:'#101820',borderRadius:22,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},mapPin:{color:colors.yellow,fontSize:36},mapText:{color:colors.white,fontWeight:'800',fontSize:18},mapSub:{color:colors.muted,marginTop:6,textAlign:'center',paddingHorizontal:16},card:{backgroundColor:colors.panel,borderRadius:18,padding:16,marginTop:16,borderWidth:1,borderColor:colors.line},label:{color:colors.white,fontWeight:'800',marginBottom:10},input:{backgroundColor:'#0b0b0b',color:colors.white,borderRadius:14,padding:15,borderWidth:1,borderColor:colors.line},shortcuts:{flexDirection:'row',gap:8,marginTop:12,flexWrap:'wrap'},chip:{color:colors.white,backgroundColor:colors.panel2,paddingVertical:9,paddingHorizontal:12,borderRadius:999},section:{color:colors.white,fontSize:19,fontWeight:'800',marginTop:22,marginBottom:8},category:{backgroundColor:colors.panel,borderRadius:16,padding:16,marginBottom:10,borderWidth:1,borderColor:colors.line,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},selected:{borderColor:colors.yellow},categoryName:{color:colors.white,fontWeight:'900',fontSize:17},categoryMeta:{color:colors.muted,fontSize:12,marginTop:4,maxWidth:250},price:{color:colors.yellow,fontWeight:'900',fontSize:17},button:{backgroundColor:colors.yellow,padding:17,borderRadius:16,alignItems:'center',marginTop:14},buttonText:{color:'#000',fontWeight:'900',fontSize:17},bottom:{flexDirection:'row',justifyContent:'space-around',marginTop:24},bottomLink:{color:colors.muted,fontWeight:'700'},muted:{color:colors.muted}})
