import {useState} from 'react'
import {Alert,Pressable,StyleSheet,Text,TextInput,View} from 'react-native'
import {router} from 'expo-router'
import {supabase} from '@/lib/supabase'
import {colors} from '@/lib/theme'

export default function Login(){
 const[phone,setPhone]=useState('+55');const[token,setToken]=useState('');const[sent,setSent]=useState(false);const[loading,setLoading]=useState(false)
 async function send(){setLoading(true);const {error}=await supabase.auth.signInWithOtp({phone});setLoading(false);if(error)Alert.alert('Não foi possível enviar',error.message);else setSent(true)}
 async function verify(){setLoading(true);const {data,error}=await supabase.auth.verifyOtp({phone,token,type:'sms'});if(error){setLoading(false);Alert.alert('Código inválido',error.message);return}if(data.user){await supabase.from('profiles').upsert({id:data.user.id,role:'passenger',phone,active:true},{onConflict:'id'});router.replace('/home')}setLoading(false)}
 return <View style={s.screen}><Text style={s.logo}>CLICK-GO</Text><Text style={s.title}>{sent?'Digite o código':'Entre com seu telefone'}</Text><Text style={s.sub}>Cadastro e acesso por SMS. Se você já tiver conta, o mesmo número faz o login.</Text>{!sent?<TextInput style={s.input} value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="+55 62 99999-9999" placeholderTextColor={colors.muted}/>:<TextInput style={s.input} value={token} onChangeText={setToken} keyboardType="number-pad" placeholder="Código SMS" placeholderTextColor={colors.muted}/>}<Pressable style={s.button} onPress={sent?verify:send} disabled={loading}><Text style={s.buttonText}>{loading?'Aguarde...':sent?'Confirmar código':'Enviar código'}</Text></Pressable>{sent&&<Pressable onPress={()=>setSent(false)}><Text style={s.link}>Alterar telefone</Text></Pressable>}<Text style={s.note}>Recuperação de acesso: solicite um novo código SMS a qualquer momento.</Text></View>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.black,padding:24,justifyContent:'center'},logo:{color:colors.yellow,fontSize:30,fontWeight:'900',marginBottom:28},title:{color:colors.white,fontSize:28,fontWeight:'800'},sub:{color:colors.muted,fontSize:15,lineHeight:22,marginTop:8,marginBottom:24},input:{backgroundColor:colors.panel,color:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:14,padding:16,fontSize:18},button:{backgroundColor:colors.yellow,padding:16,borderRadius:14,alignItems:'center',marginTop:14},buttonText:{color:'#000',fontWeight:'900',fontSize:16},link:{color:colors.yellow,textAlign:'center',marginTop:18,fontWeight:'700'},note:{color:colors.muted,fontSize:12,textAlign:'center',marginTop:28}})
