import {useEffect,useState} from 'react'
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native'
import {supabase} from '@/lib/supabase'
import {colors} from '@/lib/theme'

export default function Profile(){
 const[form,setForm]=useState({full_name:'',phone:'',email:'',cpf:''});const[loading,setLoading]=useState(false)
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from('profiles').select('full_name,phone,email,cpf').eq('id',user.id).single();if(data)setForm({full_name:data.full_name||'',phone:data.phone||'',email:data.email||user.email||'',cpf:data.cpf||''})})()},[])
 async function save(){setLoading(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const{error}=await supabase.from('profiles').update({full_name:form.full_name.trim(),phone:form.phone.trim(),updated_at:new Date().toISOString()}).eq('id',user.id);setLoading(false);Alert.alert(error?'Erro':'Cadastro',error?.message||'Dados atualizados com sucesso.')}
 const masked=form.cpf?`${form.cpf.slice(0,3)}.***.***-${form.cpf.slice(-2)}`:''
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><Text style={s.title}>Meu cadastro</Text><Text style={s.label}>Nome completo</Text><TextInput style={s.input} value={form.full_name} onChangeText={v=>setForm({...form,full_name:v})}/><Text style={s.label}>Telefone</Text><TextInput style={s.input} value={form.phone} onChangeText={v=>setForm({...form,phone:v})} keyboardType="phone-pad"/><Text style={s.label}>E-mail</Text><View style={s.readonly}><Text style={s.readonlyText}>{form.email}</Text></View><Text style={s.label}>CPF</Text><View style={s.readonly}><Text style={s.readonlyText}>{masked||'Não informado'}</Text></View><Text style={s.note}>O cadastro do passageiro é livre. A cidade é identificada automaticamente quando você solicita uma corrida.</Text><Pressable style={s.button} onPress={save} disabled={loading}><Text style={s.buttonText}>{loading?'Salvando...':'Salvar alterações'}</Text></Pressable></ScrollView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.black},content:{padding:22,paddingBottom:40},title:{color:colors.yellow,fontSize:27,fontWeight:'900',marginBottom:20},label:{color:colors.white,fontWeight:'800',marginTop:14,marginBottom:7},input:{backgroundColor:colors.panel,color:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:14,padding:15,fontSize:16},readonly:{backgroundColor:'#101010',borderWidth:1,borderColor:colors.line,borderRadius:14,padding:15},readonlyText:{color:colors.muted},note:{color:colors.muted,lineHeight:20,marginTop:20},button:{backgroundColor:colors.yellow,padding:16,borderRadius:14,alignItems:'center',marginTop:24},buttonText:{color:'#000',fontWeight:'900'}})
