import {useEffect,useState} from 'react'
import {Alert,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native'
import MapView,{Marker} from 'react-native-maps'
import {router,useLocalSearchParams} from 'expo-router'
import {supabase} from '@/lib/supabase'
import {colors} from '@/lib/theme'

export default function Ride(){
 const{id}=useLocalSearchParams<{id:string}>();const[ride,setRide]=useState<any>(null),[driverLoc,setDriverLoc]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[text,setText]=useState('')
 async function load(){if(!id)return;const {data}=await supabase.from('rides').select('*,drivers(id,rating,online,profiles(full_name,phone,avatar_url),vehicles(make,model,plate,color))').eq('id',id).single();setRide(data);if(data?.driver_id){const l=await supabase.from('driver_locations').select('*').eq('driver_id',data.driver_id).maybeSingle();setDriverLoc(l.data)}const m=await supabase.from('ride_chat_messages').select('*').eq('ride_id',id).order('created_at');setMessages(m.data||[])}
 useEffect(()=>{load();if(!id)return;const ch=supabase.channel(`passenger-ride-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'rides',filter:`id=eq.${id}`},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'ride_chat_messages',filter:`ride_id=eq.${id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'driver_locations'},payload=>{const p:any=payload.new;if(ride?.driver_id&&p?.driver_id===ride.driver_id)setDriverLoc(p)}).subscribe();return()=>{supabase.removeChannel(ch)}},[id,ride?.driver_id])
 async function send(){if(!text.trim()||!id)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('ride_chat_messages').insert({ride_id:id,sender_id:user.id,message:text.trim()});setText('')}
 async function cancel(){if(!id)return;const {error}=await supabase.from('rides').update({status:'cancelled',cancelled_at:new Date().toISOString()}).eq('id',id);if(error)Alert.alert('Erro',error.message);else router.replace('/home')}
 async function safety(){if(!id)return;const {data:{user}}=await supabase.auth.getUser();await supabase.from('safety_events').insert({ride_id:id,passenger_id:user?.id,event_type:'panic_button',details:{source:'passenger_app'}});Alert.alert('Alerta registrado','Seu evento de segurança foi registrado no sistema.')}
 async function protectedCall(){if(!id||!ride?.driver_id)return Alert.alert('Aguarde','A ligação protegida ficará disponível após um motorista aceitar.');const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from('masked_call_sessions').insert({ride_id:id,passenger_id:user?.id,driver_id:ride.driver_id,status:'requested'});if(error)Alert.alert('Ligação',error.message);else Alert.alert('Ligação protegida solicitada','A sessão foi registrada. O provedor de telefonia fará a ponte sem revelar os números.')}
 const status:Record<string,string>={requested:'Procurando motorista',searching:'Buscando motorista',accepted:'Motorista aceitou',driver_arriving:'Motorista a caminho',in_progress:'Viagem em andamento',completed:'Viagem concluída',cancelled:'Corrida cancelada'}
 if(!ride)return <View style={s.center}><Text style={s.muted}>Carregando corrida...</Text></View>
 const d=ride.drivers,v=Array.isArray(d?.vehicles)?d.vehicles[0]:d?.vehicles;const center=driverLoc?{latitude:driverLoc.lat,longitude:driverLoc.lng}:{latitude:ride.origin_lat,longitude:ride.origin_lng}
 return <ScrollView style={s.screen} contentContainerStyle={{padding:18,paddingBottom:40}}><Text style={s.status}>{status[ride.status]||ride.status}</Text><MapView style={s.map} region={{...center,latitudeDelta:.035,longitudeDelta:.035}}><Marker coordinate={{latitude:ride.origin_lat,longitude:ride.origin_lng}} title="Origem"/>{driverLoc&&<Marker coordinate={{latitude:driverLoc.lat,longitude:driverLoc.lng}} title="Seu motorista" pinColor={colors.yellow}/>}<Marker coordinate={{latitude:ride.destination_lat,longitude:ride.destination_lng}} title="Destino"/></MapView>{d&&<View style={s.card}><View style={s.driverRow}>{d.profiles?.avatar_url?<Image source={{uri:d.profiles.avatar_url}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.avatarText}>CG</Text></View>}<View style={{flex:1}}><Text style={s.driver}>{d.profiles?.full_name||'Motorista CLICK-GO'}</Text><Text style={s.mutedLeft}>★ {d.rating||5} • {v?`${v.make} ${v.model} • ${v.color||''} • ${v.plate}`:'Veículo aguardando dados'}</Text></View></View><View style={s.actions}><Pressable style={s.secondary} onPress={protectedCall}><Text style={s.white}>Ligação protegida</Text></Pressable><Pressable style={s.secondary} onPress={()=>router.push({pathname:'/safety',params:{rideId:id}})}><Text style={s.white}>Compartilhar viagem</Text></Pressable></View></View>}<View style={s.card}><Text style={s.title}>Chat</Text>{messages.slice(-8).map(m=><Text key={m.id} style={s.message}>{m.message}</Text>)}<View style={s.chat}><TextInput style={s.input} value={text} onChangeText={setText} placeholder="Mensagem para o motorista" placeholderTextColor={colors.muted}/><Pressable style={s.send} onPress={send}><Text style={s.sendText}>Enviar</Text></Pressable></View></View><View style={s.actions}><Pressable style={s.danger} onPress={safety}><Text style={s.white}>Botão de segurança</Text></Pressable>{!['completed','cancelled'].includes(ride.status)&&<Pressable style={s.secondary} onPress={cancel}><Text style={s.white}>Cancelar corrida</Text></Pressable>}</View>{ride.status==='completed'&&<Pressable style={s.pay} onPress={()=>router.push({pathname:'/wallet',params:{rideId:id}})}><Text style={s.payText}>Pagar e avaliar</Text></Pressable>}</ScrollView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.black},center:{flex:1,backgroundColor:colors.black,alignItems:'center',justifyContent:'center'},status:{color:colors.yellow,fontSize:26,fontWeight:'900',marginBottom:14},map:{height:260,borderRadius:20,overflow:'hidden'},card:{backgroundColor:colors.panel,borderRadius:18,padding:16,marginTop:14,borderWidth:1,borderColor:colors.line},driverRow:{flexDirection:'row',alignItems:'center',gap:12},avatar:{width:58,height:58,borderRadius:29},avatarFallback:{width:58,height:58,borderRadius:29,backgroundColor:colors.yellow,alignItems:'center',justifyContent:'center'},avatarText:{color:'#000',fontWeight:'900'},driver:{color:colors.white,fontWeight:'900',fontSize:20},muted:{color:colors.muted,textAlign:'center'},mutedLeft:{color:colors.muted,marginTop:3},title:{color:colors.white,fontWeight:'900',fontSize:18,marginBottom:10},actions:{flexDirection:'row',gap:10,marginTop:14,flexWrap:'wrap'},secondary:{backgroundColor:colors.panel2,padding:13,borderRadius:12},danger:{backgroundColor:'#4b1111',padding:13,borderRadius:12},white:{color:colors.white,fontWeight:'800'},message:{color:colors.white,backgroundColor:'#222',padding:10,borderRadius:10,marginTop:6},chat:{flexDirection:'row',gap:8,marginTop:10},input:{flex:1,backgroundColor:'#0b0b0b',color:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:12},send:{backgroundColor:colors.yellow,borderRadius:12,paddingHorizontal:14,justifyContent:'center'},sendText:{fontWeight:'900',color:'#000'},pay:{backgroundColor:colors.yellow,padding:17,borderRadius:16,alignItems:'center',marginTop:18},payText:{fontWeight:'900',fontSize:17,color:'#000'}})
