import {useState} from 'react'
import {Alert,Pressable,Share,StyleSheet,Text,View} from 'react-native'
import {useLocalSearchParams} from 'expo-router'
import * as Location from 'expo-location'
import {supabase} from '@/lib/supabase'
import {colors} from '@/lib/theme'

export default function Safety(){const{rideId}=useLocalSearchParams<{rideId?:string}>();const[loading,setLoading]=useState(false);async function shareRide(){if(!rideId)return Alert.alert('Sem corrida ativa');setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const expires=new Date(Date.now()+6*60*60*1000).toISOString();const {data,error}=await supabase.from('ride_shares').insert({ride_id:rideId,passenger_id:user.id,expires_at:expires}).select('share_token').single();setLoading(false);if(error)return Alert.alert('Erro',error.message);const url=`https://clickgo.com.br/viagem/${data.share_token}`;await Share.share({message:`Acompanhe minha viagem CLICK-GO: ${url}`})}async function emergency(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user)return;let lat=null,lng=null;try{const p=await Location.getCurrentPositionAsync({});lat=p.coords.latitude;lng=p.coords.longitude}catch{}const {error}=await supabase.from('safety_events').insert({ride_id:rideId||null,passenger_id:user.id,event_type:'panic_button',lat,lng,details:{source:'safety_center'}});setLoading(false);if(error)Alert.alert('Erro',error.message);else Alert.alert('Alerta enviado','O evento foi registrado com sua localização disponível.')}return <View style={s.screen}><Text style={s.title}>Central de Segurança</Text><Text style={s.muted}>Ferramentas para compartilhar a viagem e registrar situações de emergência.</Text><Pressable style={s.card} onPress={shareRide} disabled={loading}><Text style={s.cardTitle}>Compartilhar viagem</Text><Text style={s.muted}>Gera um link temporário para alguém acompanhar sua corrida.</Text></Pressable><Pressable style={[s.card,{borderColor:'#7f1d1d'}]} onPress={emergency} disabled={loading}><Text style={[s.cardTitle,{color:'#fecaca'}]}>Botão de segurança</Text><Text style={s.muted}>Registra imediatamente um evento de segurança e sua localização, quando disponível.</Text></Pressable><View style={s.notice}><Text style={s.noticeText}>Em risco imediato, use também os serviços oficiais de emergência disponíveis no seu local.</Text></View></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.black,padding:20},title:{color:colors.white,fontSize:27,fontWeight:'900',marginTop:20},muted:{color:colors.muted,lineHeight:21,marginTop:7},card:{backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:18,marginTop:18},cardTitle:{color:colors.yellow,fontSize:19,fontWeight:'900'},notice:{marginTop:26,padding:16,borderRadius:14,backgroundColor:'#161616'},noticeText:{color:colors.muted,fontSize:12,lineHeight:18}})
