import {useEffect,useState} from 'react'
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native'
import {router,useLocalSearchParams} from 'expo-router'
import {supabase} from '@/lib/supabase'
import {colors} from '@/lib/theme'

const methods=['pix','cash','card','wallet']
export default function Wallet(){const{rideId}=useLocalSearchParams<{rideId?:string}>();const[ride,setRide]=useState<any>(null),[method,setMethod]=useState('pix'),[rating,setRating]=useState('5'),[comment,setComment]=useState(''),[saved,setSaved]=useState<any[]>([]);useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const m=await supabase.from('passenger_payment_methods').select('*').eq('passenger_id',user.id).eq('active',true);setSaved(m.data||[]);if(rideId){const r=await supabase.from('rides').select('*').eq('id',rideId).single();setRide(r.data)}})()},[rideId]);async function finish(){if(!rideId||!ride)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const amount=Number(ride.final_fare||ride.estimated_fare||0);const {error}=await supabase.from('payments').insert({ride_id:rideId,franchise_id:ride.franchise_id,payer_id:user.id,amount,method,status:method==='cash'?'authorized':'pending',provider:method==='pix'?'efi':method==='card'?'card_provider':null});if(error)return Alert.alert('Pagamento',error.message);if(ride.driver_id)await supabase.from('ride_ratings').upsert({ride_id:rideId,passenger_id:user.id,driver_id:ride.driver_id,rating:Number(rating),comment},{onConflict:'ride_id,passenger_id'});await supabase.from('ride_receipts').upsert({ride_id:rideId,passenger_id:user.id,fare:amount,discount:0,total:amount,payment_method:method},{onConflict:'ride_id'});Alert.alert('Concluído','Pagamento registrado e avaliação salva.');router.replace('/history')}
 return <ScrollView style={s.screen} contentContainerStyle={{padding:18}}><Text style={s.title}>Pagamento</Text><Text style={s.muted}>Escolha Pix, dinheiro, cartão ou carteira.</Text><View style={s.methods}>{methods.map(m=><Pressable key={m} style={[s.method,method===m&&s.selected]} onPress={()=>setMethod(m)}><Text style={s.methodText}>{m==='cash'?'Dinheiro':m==='card'?'Cartão':m==='wallet'?'Carteira':'Pix'}</Text></Pressable>)}</View>{saved.length>0&&<View style={s.card}><Text style={s.section}>Cartões/meios salvos</Text>{saved.map(x=><Text key={x.id} style={s.muted}>{x.method_type} {x.brand||''} {x.last4?`•••• ${x.last4}`:''}</Text>)}</View>}{rideId&&<View style={s.card}><Text style={s.section}>Avalie o motorista</Text><View style={s.stars}>{['1','2','3','4','5'].map(x=><Pressable key={x} onPress={()=>setRating(x)}><Text style={[s.star,Number(x)<=Number(rating)&&{color:colors.yellow}]}>★</Text></Pressable>)}</View><TextInput style={s.input} value={comment} onChangeText={setComment} placeholder="Comentário opcional" placeholderTextColor={colors.muted}/><Pressable style={s.button} onPress={finish}><Text style={s.buttonText}>Confirmar pagamento e avaliação</Text></Pressable></View>}</ScrollView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.black},title:{color:colors.white,fontSize:27,fontWeight:'900'},muted:{color:colors.muted,marginTop:7},methods:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:18},method:{backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,borderRadius:14,paddingVertical:14,paddingHorizontal:18},selected:{borderColor:colors.yellow},methodText:{color:colors.white,fontWeight:'800'},card:{backgroundColor:colors.panel,padding:16,borderRadius:16,borderWidth:1,borderColor:colors.line,marginTop:18},section:{color:colors.white,fontWeight:'900',fontSize:18,marginBottom:10},stars:{flexDirection:'row',marginBottom:12},star:{fontSize:34,color:'#444'},input:{backgroundColor:'#0b0b0b',color:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:13},button:{backgroundColor:colors.yellow,padding:15,borderRadius:12,alignItems:'center',marginTop:12},buttonText:{color:'#000',fontWeight:'900'}})
