'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Franchise={id:string;trade_name:string};type AdminRow={id:string;full_name:string|null;phone:string|null;franchise_id:string|null;active:boolean}
export default function AccessManager(){
 const [franchises,setFranchises]=useState<Franchise[]>([]);const [admins,setAdmins]=useState<AdminRow[]>([]);const [msg,setMsg]=useState('');const [form,setForm]=useState({full_name:'',phone:'',email:'',password:'',franchise_id:''})
 async function load(){const f=await supabase.from('franchises').select('id,trade_name').is('deleted_at',null).eq('active',true).order('trade_name');setFranchises(f.data||[]);const a=await supabase.from('profiles').select('id,full_name,phone,franchise_id,active').eq('role','franchise_admin').order('created_at',{ascending:false});if(a.error)setMsg(a.error.message);else setAdmins((a.data||[]) as AdminRow[])}
 useEffect(()=>{load()},[])
 async function create(e:React.FormEvent){e.preventDefault();setMsg('Criando acesso...');const {data,error}=await supabase.functions.invoke('admin-users',{body:{action:'create_franchise_admin',...form}});if(error){setMsg(error.message);return}if(data?.error){setMsg(data.error);return}setMsg('Acesso criado com sucesso.');setForm({full_name:'',phone:'',email:'',password:'',franchise_id:''});load()}
 async function setBlock(id:string,active:boolean){const {data,error}=await supabase.functions.invoke('admin-users',{body:{action:active?'block_user':'unblock_user',user_id:id}});if(error||data?.error)setMsg(error?.message||data.error);else{setMsg(active?'Acesso bloqueado.':'Acesso reativado.');load()}}
 const fname=(id:string|null)=>franchises.find(f=>f.id===id)?.trade_name||'—'
 return <><div className="card"><form onSubmit={create}><div className="form-grid"><div className="field"><label>Nome do administrador</label><input className="input" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></div><div className="field"><label>Franquia</label><select className="input" value={form.franchise_id} onChange={e=>setForm({...form,franchise_id:e.target.value})} required><option value="">Selecione</option>{franchises.map(f=><option key={f.id} value={f.id}>{f.trade_name}</option>)}</select></div><div className="field"><label>E-mail de acesso</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div className="field"><label>Senha temporária</label><input className="input" type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></div><div className="field"><label>Telefone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button">Gerar acesso</button></div>{msg&&<p className="empty">{msg}</p>}</form></div><div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Administrador</th><th>Franquia</th><th>Status</th><th>Ações</th></tr></thead><tbody>{admins.length===0?<tr><td colSpan={4} className="empty">Nenhum administrador de franquia criado.</td></tr>:admins.map(a=><tr key={a.id}><td>{a.full_name||a.id}</td><td>{fname(a.franchise_id)}</td><td><span className={'pill '+(a.active?'green':'red')}>{a.active?'Ativo':'Bloqueado'}</span></td><td><button className="button secondary" onClick={()=>setBlock(a.id,a.active)}>{a.active?'Bloquear':'Reativar'}</button></td></tr>)}</tbody></table></div></div></>
}
