'use client'

import { useEffect,useRef,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Notice={id:number;user_id:string;ride_id:string|null;type:string;title:string;body:string;data:any;created_at:string;read_at:string|null}

export default function AppNotifications(){
 const[userId,setUserId]=useState(''),[items,setItems]=useState<Notice[]>([]),[open,setOpen]=useState(false),[flash,setFlash]=useState<Notice|null>(null)
 const timer=useRef<number|null>(null)
 useEffect(()=>{let channel:any=null;let mounted=true;(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!mounted||!user)return;setUserId(user.id);const{data}=await supabase.from('user_notifications').select('id,user_id,ride_id,type,title,body,data,created_at,read_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(20);if(mounted)setItems((data||[]) as Notice[]);channel=supabase.channel(`user-notifications-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'user_notifications',filter:`user_id=eq.${user.id}`},(payload:any)=>{const n=payload.new as Notice;setItems(v=>[n,...v.filter(x=>x.id!==n.id)].slice(0,20));setFlash(n);if(timer.current)window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>setFlash(null),6500);if(typeof window!=='undefined'&&'Notification'in window&&Notification.permission==='granted'){try{new Notification(n.title,{body:n.body,tag:`clickgo-${n.id}`})}catch{}}}).subscribe()})();return()=>{mounted=false;if(channel)supabase.removeChannel(channel);if(timer.current)window.clearTimeout(timer.current)}},[])
 async function mark(id:number){if(!userId)return;setItems(v=>v.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x));await supabase.from('user_notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',userId)}
 async function markAll(){if(!userId)return;const now=new Date().toISOString();setItems(v=>v.map(x=>({...x,read_at:x.read_at||now})));await supabase.from('user_notifications').update({read_at:now}).eq('user_id',userId).is('read_at',null)}
 async function enableBrowser(){if(!('Notification'in window))return;try{await Notification.requestPermission()}catch{}}
 if(!userId)return null
 const unread=items.filter(x=>!x.read_at).length
 return <>
  <button aria-label="Notificações" title="Notificações" onClick={()=>setOpen(v=>!v)} style={{position:'fixed',right:18,bottom:18,zIndex:9997,width:52,height:52,borderRadius:'50%',border:'2px solid #ffd400',background:'#111',color:'#ffd400',fontSize:22,cursor:'pointer',boxShadow:'0 10px 30px #0007'}}>🔔{unread>0&&<span style={{position:'absolute',right:-3,top:-5,minWidth:21,height:21,padding:'0 5px',borderRadius:999,display:'grid',placeItems:'center',background:'#dc2626',color:'#fff',fontSize:11,fontWeight:900}}>{unread>99?'99+':unread}</span>}</button>
  {flash&&<div onClick={()=>{void mark(flash.id);setFlash(null)}} style={{position:'fixed',right:18,bottom:82,zIndex:9998,width:'min(390px,calc(100vw - 36px))',background:'#111',color:'#fff',border:'2px solid #ffd400',borderRadius:16,padding:14,boxShadow:'0 18px 60px #0009',cursor:'pointer'}}><div style={{fontWeight:950,color:'#ffd400'}}>{flash.title}</div><div style={{fontSize:13,color:'#e5e7eb',marginTop:4,lineHeight:1.45}}>{flash.body}</div><div style={{fontSize:10,color:'#9ca3af',marginTop:6}}>agora · toque para marcar como lida</div></div>}
  {open&&<div style={{position:'fixed',right:18,bottom:82,zIndex:9999,width:'min(430px,calc(100vw - 36px))',maxHeight:'70vh',overflow:'auto',background:'#0b0b0b',color:'#fff',border:'1px solid #333',borderRadius:18,padding:14,boxShadow:'0 24px 80px #000c'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center'}}><div><b style={{fontSize:18}}>Notificações</b><div style={{fontSize:11,color:'#9ca3af'}}>{unread} não lida(s)</div></div><div style={{display:'flex',gap:6}}>{typeof window!=='undefined'&&'Notification'in window&&Notification.permission!=='granted'&&<button onClick={enableBrowser} style={{border:0,borderRadius:8,padding:'7px 9px',background:'#ffd400',color:'#000',fontWeight:800,cursor:'pointer'}}>Ativar alertas</button>}<button onClick={markAll} style={{border:'1px solid #333',borderRadius:8,padding:'7px 9px',background:'#171717',color:'#fff',cursor:'pointer'}}>Marcar lidas</button></div></div><div style={{display:'grid',gap:8,marginTop:12}}>{items.map(n=><button key={n.id} onClick={()=>mark(n.id)} style={{textAlign:'left',border:`1px solid ${n.read_at?'#292929':'#665600'}`,borderRadius:12,padding:11,background:n.read_at?'#111':'#181508',color:'#fff',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b style={{color:n.read_at?'#e5e7eb':'#ffd400'}}>{n.title}</b><span style={{fontSize:10,color:'#9ca3af'}}>{new Date(n.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span></div><div style={{fontSize:12,color:'#cbd5e1',marginTop:4,lineHeight:1.4}}>{n.body}</div></button>)}{!items.length&&<div style={{padding:20,textAlign:'center',color:'#9ca3af'}}>Nenhuma notificação.</div>}</div></div>}
 </>
}
