'use client'

import {useEffect,useMemo,useState} from 'react'
import {ChevronDown, ChevronUp, RefreshCw, Search, ShieldCheck} from 'lucide-react'
import {supabase} from '@/lib/supabase'

type Audit={id:number;actor_id:string|null;action:string;entity:string;entity_id:string|null;metadata:Record<string,any>|null;created_at:string}
type Profile={id:string;full_name:string|null;email:string|null;role:string}
type Franchise={id:string;trade_name:string}
const actionLabel:Record<string,string>={insert:'Criou registro',update:'Alterou registro',delete:'Excluiu registro',territory_assignment:'Liberou território',territory_override:'Sobrescreveu território',territory_removal:'Removeu território',license_suspend:'Suspendeu licença',license_reactivate:'Reativou licença',license_cancel:'Cancelou licença',invoice_due_date_extended:'Prorrogou vencimento',configuration_insert:'Criou configuração',configuration_update:'Alterou configuração',configuration_delete:'Removeu configuração'}
const entityLabel:Record<string,string>={franchises:'Franquia',franchise_plans:'Plano',franchise_subscriptions:'Plano da franquia',franchise_cities:'Território',account_blocks:'Bloqueio',franchise_invoices:'Fatura',franchise_collection_rules:'Regra de inadimplência',franchise_invoice_adjustments:'Ajuste financeiro',franchise_support_sessions:'Sessão de suporte',franchise_fares:'Tarifa',franchise_categories:'Categoria',franchise_promotions:'Promoção'}

function compactDiff(meta:Record<string,any>|null){
 const oldValue=meta?.old_value,newValue=meta?.new_value
 if(!oldValue&&!newValue)return meta?.reason||'—'
 if(oldValue&&newValue&&typeof oldValue==='object'&&typeof newValue==='object'){
  const keys=Array.from(new Set([...Object.keys(oldValue),...Object.keys(newValue)]))
  const changed=keys.filter(k=>JSON.stringify(oldValue[k])!==JSON.stringify(newValue[k])).slice(0,4)
  if(changed.length)return changed.map(k=>`${k}: ${String(oldValue[k]??'—')} → ${String(newValue[k]??'—')}`).join(' · ')
 }
 return oldValue?'Registro removido':'Novo registro'
}

export default function AuditManager(){
 const[rows,setRows]=useState<Audit[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[franchises,setFranchises]=useState<Franchise[]>([])
 const[franchiseId,setFranchiseId]=useState(''),[search,setSearch]=useState(''),[days,setDays]=useState('7'),[expanded,setExpanded]=useState<number|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);setMsg('');const since=new Date(Date.now()-Number(days)*86400000).toISOString();let query=supabase.from('audit_logs').select('id,actor_id,action,entity,entity_id,metadata,created_at').gte('created_at',since).order('created_at',{ascending:false}).limit(500);if(franchiseId)query=query.contains('metadata',{franchise_id:franchiseId});const[a,f]=await Promise.all([query,supabase.from('franchises').select('id,trade_name').is('deleted_at',null).order('trade_name')]);if(a.error||f.error){setMsg(a.error?.message||f.error?.message||'Erro ao carregar auditoria.');setBusy(false);return}const logs=(a.data||[]) as Audit[];setRows(logs);setFranchises((f.data||[]) as Franchise[]);const ids=Array.from(new Set(logs.map(x=>x.actor_id).filter(Boolean))) as string[];if(ids.length){const{data}=await supabase.from('profiles').select('id,full_name,email,role').in('id',ids);setProfiles((data||[]) as Profile[])}else setProfiles([]);setBusy(false)}
 useEffect(()=>{void load()},[days,franchiseId])
 const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]),franchiseMap=useMemo(()=>new Map(franchises.map(f=>[f.id,f.trade_name])),[franchises])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>{const p=r.actor_id?profileMap.get(r.actor_id):null;const fid=String(r.metadata?.franchise_id||'');return `${r.action} ${r.entity} ${r.entity_id||''} ${p?.full_name||''} ${p?.email||''} ${franchiseMap.get(fid)||''} ${r.metadata?.reason||''}`.toLowerCase().includes(q)})},[rows,search,profileMap,franchiseMap])
 const actor=(r:Audit)=>{const p=r.actor_id?profileMap.get(r.actor_id):null;const source=r.metadata?.source;const sourceLabel=source==='matrix_support'?'Matriz (Suporte)':source==='matrix'?'Matriz':source==='franchise'?'Franqueado':source==='staff'?'Equipe':source==='system'?'Sistema':'';return p?.full_name||p?.email||sourceLabel||'Sistema'}
 return <>
  <div className="card"><div className="section-heading"><div><div className="eyebrow">Governança da rede</div><h2>Auditoria Geral</h2><p className="subtitle">Alterações críticas guardam quem fez, quando fez, a franquia afetada e os valores antes/depois.</p></div><button className="button secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/>Atualizar</button></div><div className="form-grid"><div className="field"><label>Franquia</label><select className="input" value={franchiseId} onChange={e=>setFranchiseId(e.target.value)}><option value="">Todas</option>{franchises.map(f=><option key={f.id} value={f.id}>{f.trade_name}</option>)}</select></div><div className="field"><label>Período</label><select className="input" value={days} onChange={e=>setDays(e.target.value)}><option value="1">Últimas 24 horas</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option></select></div><div className="field"><label>Buscar ação ou usuário</label><div style={{position:'relative'}}><Search size={15} style={{position:'absolute',left:12,top:12}}/><input className="input" style={{paddingLeft:34}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="tarifa, bloqueio, João..."/></div></div></div>{msg&&<p className="empty">{msg}</p>}</div>
  <div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Data/Hora</th><th>Usuário</th><th>Franquia</th><th>Ação</th><th>Alteração</th><th></th></tr></thead><tbody>{filtered.length===0?<tr><td colSpan={6} className="empty">Nenhum evento no período selecionado.</td></tr>:filtered.map(r=>{const fid=String(r.metadata?.franchise_id||'');const isOpen=expanded===r.id;return <tr key={r.id}><td>{new Date(r.created_at).toLocaleString('pt-BR')}</td><td><strong>{actor(r)}</strong><br/><small>{r.metadata?.source||'—'}</small></td><td>{franchiseMap.get(fid)||r.metadata?.franchise_name||'Global'}</td><td><span className="pill"><ShieldCheck size={12}/>{actionLabel[r.action]||r.action}</span><br/><small>{entityLabel[r.entity]||r.entity}</small></td><td style={{maxWidth:440}}>{compactDiff(r.metadata)}</td><td><button className="button secondary" onClick={()=>setExpanded(isOpen?null:r.id)}>{isOpen?<ChevronUp size={14}/>:<ChevronDown size={14}/>}Detalhes</button>{isOpen&&<div className="card" style={{position:'absolute',right:28,left:300,marginTop:8,zIndex:20,maxHeight:420,overflow:'auto'}}><div className="section-heading"><div><strong>Detalhes da auditoria #{r.id}</strong><p className="subtitle">Justificativa: {r.metadata?.reason||'não informada'}</p></div></div><div className="form-grid"><div><small>Valor anterior</small><pre style={{whiteSpace:'pre-wrap',fontSize:11,background:'#f5f5f5',padding:12,borderRadius:10}}>{JSON.stringify(r.metadata?.old_value??null,null,2)}</pre></div><div><small>Valor novo</small><pre style={{whiteSpace:'pre-wrap',fontSize:11,background:'#f5f5f5',padding:12,borderRadius:10}}>{JSON.stringify(r.metadata?.new_value??null,null,2)}</pre></div></div><small>Entidade: {r.entity} · ID: {r.entity_id||'—'}</small></div>}</td></tr>})}</tbody></table></div></div>
 </>
}
