'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Block={id:string;profile_id:string|null;driver_id:string|null;franchise_id:string|null;reason:string;blocked_at:string;unblocked_at:string|null;active:boolean}
export default function BlockManager(){
 const [rows,setRows]=useState<Block[]>([]);const [msg,setMsg]=useState('');const [targetType,setTargetType]=useState('franchise');const [targetId,setTargetId]=useState('');const [reason,setReason]=useState('')
 async function load(){const {data,error}=await supabase.from('account_blocks').select('*').order('blocked_at',{ascending:false}).limit(200);if(error)setMsg(error.message);else setRows((data||[]) as Block[])}
 useEffect(()=>{load()},[])
 async function add(e:React.FormEvent){e.preventDefault();const {data:{user}}=await supabase.auth.getUser();const payload:any={reason,blocked_by:user?.id||null,active:true};payload[targetType==='franchise'?'franchise_id':targetType==='driver'?'driver_id':'profile_id']=targetId;const {error}=await supabase.from('account_blocks').insert(payload);if(error){setMsg(error.message);return}if(targetType==='franchise')await supabase.from('franchises').update({active:false,blocked_at:new Date().toISOString(),blocked_reason:reason}).eq('id',targetId);if(targetType==='driver')await supabase.from('drivers').update({status:'blocked'}).eq('id',targetId);if(targetType==='profile')await supabase.from('profiles').update({active:false}).eq('id',targetId);setTargetId('');setReason('');setMsg('Bloqueio registrado.');load()}
 async function unblock(b:Block){await supabase.from('account_blocks').update({active:false,unblocked_at:new Date().toISOString()}).eq('id',b.id);if(b.franchise_id)await supabase.from('franchises').update({active:true,blocked_at:null,blocked_reason:null}).eq('id',b.franchise_id);if(b.driver_id)await supabase.from('drivers').update({status:'approved'}).eq('id',b.driver_id);if(b.profile_id)await supabase.from('profiles').update({active:true}).eq('id',b.profile_id);load()}
 const target=(b:Block)=>b.franchise_id?`Franquia: ${b.franchise_id}`:b.driver_id?`Motorista: ${b.driver_id}`:`Perfil: ${b.profile_id}`
 return <><div className="card"><form onSubmit={add}><div className="form-grid"><div className="field"><label>Tipo de alvo</label><select className="input" value={targetType} onChange={e=>setTargetType(e.target.value)}><option value="franchise">Franquia</option><option value="driver">Motorista</option><option value="profile">Passageiro/usuário</option></select></div><div className="field"><label>ID do alvo</label><input className="input" value={targetId} onChange={e=>setTargetId(e.target.value)} required/></div><div className="field"><label>Motivo</label><textarea className="input" value={reason} onChange={e=>setReason(e.target.value)} required/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button danger">Registrar bloqueio</button></div>{msg&&<p className="empty">{msg}</p>}</form></div><div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Alvo</th><th>Motivo</th><th>Bloqueado em</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Nenhum bloqueio registrado.</td></tr>:rows.map(b=><tr key={b.id}><td>{target(b)}</td><td>{b.reason}</td><td>{new Date(b.blocked_at).toLocaleString('pt-BR')}</td><td><span className={'pill '+(b.active?'red':'green')}>{b.active?'Bloqueado':'Liberado'}</span></td><td>{b.active&&<button className="button secondary" onClick={()=>unblock(b)}>Desbloquear</button>}</td></tr>)}</tbody></table></div></div></>
}
