'use client'

import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle, CalendarClock, CircleDollarSign, LockKeyhole, RefreshCw, ShieldCheck, UnlockKeyhole} from 'lucide-react'
import {supabase} from '@/lib/supabase'

type Snapshot={id:string;trade_name:string;license_status:string;active:boolean;plan_name?:string|null;computed_total_due?:number;invoice_status?:string|null;next_due_date?:string|null}
type Collection={franchise_id:string;license_status:string;active:boolean;overdue_days:number;open_overdue_amount:number;manual_override:boolean;manual_override_until:string|null;alert_before_due_days:number;restrict_new_drivers_after_days:number;block_new_rides_after_days:number;suspend_operation_after_days:number;allow_new_drivers:boolean;allow_new_rides:boolean;operation_suspended:boolean}
type Invoice={id:string;franchise_id:string;total_due:number;due_date:string;status:string;paid_at:string|null;created_at:string}
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0))
const statusLabel:Record<string,string>={active:'Ativa',past_due:'Em atraso',suspended:'Suspensa',cancelled:'Cancelada',pending:'Pendente'}

export default function BlockManager(){
 const[franchises,setFranchises]=useState<Snapshot[]>([]),[states,setStates]=useState<Record<string,Collection>>({}),[invoices,setInvoices]=useState<Invoice[]>([])
 const[selectedId,setSelectedId]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState('')
 const[rules,setRules]=useState({alert:3,drivers:5,rides:10,suspend:30}),[extendDays,setExtendDays]=useState('7')
 const[adjustment,setAdjustment]=useState({type:'fine',amount:'',description:''})

 async function load(){
  setBusy(true)
  const[snap,inv]=await Promise.all([
   supabase.rpc('super_admin_franchise_network_snapshot'),
   supabase.from('franchise_invoices').select('id,franchise_id,total_due,due_date,status,paid_at,created_at').order('created_at',{ascending:false}).limit(500),
  ])
  if(snap.error||inv.error){setMsg(snap.error?.message||inv.error?.message||'Erro ao carregar cobrança.');setBusy(false);return}
  const list=((snap.data||[]) as Snapshot[])
  setFranchises(list);setInvoices((inv.data||[]) as Invoice[])
  const stateEntries=await Promise.all(list.map(async f=>{const{data,error}=await supabase.rpc('get_franchise_collection_state',{p_franchise_id:f.id});return [f.id,error?null:data] as const}))
  const map:Record<string,Collection>={};for(const[id,data]of stateEntries)if(data)map[id]=data as Collection
  setStates(map)
  const chosen=selectedId&&list.some(f=>f.id===selectedId)?selectedId:(list[0]?.id||'');setSelectedId(chosen)
  if(chosen&&map[chosen])syncRules(map[chosen])
  setBusy(false)
 }
 useEffect(()=>{void load()},[])
 function syncRules(s:Collection){setRules({alert:Number(s.alert_before_due_days||3),drivers:Number(s.restrict_new_drivers_after_days||5),rides:Number(s.block_new_rides_after_days||10),suspend:Number(s.suspend_operation_after_days||30)})}
 function choose(id:string){setSelectedId(id);setReason('');const s=states[id];if(s)syncRules(s)}

 const selected=useMemo(()=>franchises.find(f=>f.id===selectedId)||null,[franchises,selectedId])
 const state=selectedId?states[selectedId]:undefined
 const franchiseInvoices=useMemo(()=>invoices.filter(i=>i.franchise_id===selectedId),[invoices,selectedId])
 const lastPaid=franchiseInvoices.find(i=>i.status==='paid'&&i.paid_at)
 const nextOpen=franchiseInvoices.find(i=>!['paid','cancelled'].includes(i.status))

 async function saveRules(){if(!selectedId)return;if(!(rules.alert>=0&&rules.drivers>=0&&rules.drivers<=rules.rides&&rules.rides<=rules.suspend)){setMsg('Os níveis devem respeitar a ordem: alerta → motoristas → corridas → suspensão.');return}setBusy(true);const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('franchise_collection_rules').upsert({franchise_id:selectedId,alert_before_due_days:rules.alert,restrict_new_drivers_after_days:rules.drivers,block_new_rides_after_days:rules.rides,suspend_operation_after_days:rules.suspend,updated_by:user?.id||null,updated_at:new Date().toISOString()});setBusy(false);setMsg(error?error.message:'Regras de inadimplência atualizadas e registradas na auditoria.');if(!error)void load()}
 async function license(action:'suspend'|'reactivate'|'cancel'){if(!selectedId)return;if(!reason.trim()){setMsg('Informe a justificativa da ação manual.');return}if(action==='cancel'&&!confirm('Cancelar esta licença? Essa ação é mais severa que uma suspensão.'))return;setBusy(true);const{error}=await supabase.rpc('matrix_set_franchise_license',{p_franchise_id:selectedId,p_action:action,p_reason:reason.trim()});setBusy(false);setMsg(error?error.message:action==='reactivate'?'Franquia reativada.':'Licença atualizada e motoristas retirados do modo online quando aplicável.');if(!error){setReason('');void load()}}
 async function extend(){if(!selectedId)return;if(!reason.trim()){setMsg('Informe a justificativa da prorrogação.');return}const days=Number(extendDays);if(!Number.isFinite(days)||days<1){setMsg('Informe uma quantidade válida de dias.');return}setBusy(true);const{data,error}=await supabase.rpc('matrix_extend_franchise_due_date',{p_franchise_id:selectedId,p_days:days,p_reason:reason.trim()});setBusy(false);setMsg(error?error.message:`Vencimento prorrogado para ${new Date((data as any).new_due_date+'T12:00:00').toLocaleDateString('pt-BR')}.`);if(!error){setReason('');void load()}}
 async function addAdjustment(){if(!selectedId)return;const amount=Math.abs(Number(adjustment.amount));if(!amount||!adjustment.description.trim()){setMsg('Informe valor e descrição do ajuste.');return}const month=new Date();month.setDate(1);const signed=['credit','discount'].includes(adjustment.type)?-amount:amount;setBusy(true);const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('franchise_invoice_adjustments').insert({franchise_id:selectedId,invoice_id:nextOpen?.id||null,reference_month:month.toISOString().slice(0,10),adjustment_type:adjustment.type,description:adjustment.description.trim(),amount:signed,created_by:user?.id||null});setBusy(false);setMsg(error?error.message:`Ajuste de ${brl(signed)} aplicado ao demonstrativo do mês.`);if(!error){setAdjustment({type:'fine',amount:'',description:''});void load()}}

 return <>
  <div className="card"><div className="section-heading"><div><div className="eyebrow">Matriz · Cobranças</div><h2>Controle de inadimplência e licença</h2><p className="subtitle">A Matriz define os níveis automáticos e pode intervir manualmente. Toda ação crítica fica auditada.</p></div><button className="button secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/>Atualizar</button></div>{msg&&<div className="regional-alert" style={{marginTop:12}}>{msg}</div>}</div>

  <div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Franquia</th><th>Plano</th><th>Licença</th><th>Dias em atraso</th><th>Em aberto</th><th>Próximo vencimento</th><th></th></tr></thead><tbody>{franchises.length===0?<tr><td colSpan={7} className="empty">Nenhuma franquia cadastrada.</td></tr>:franchises.map(f=>{const s=states[f.id];return <tr key={f.id}><td><strong>{f.trade_name}</strong></td><td>{f.plan_name||'Sem plano'}</td><td><span className={'pill '+((s?.operation_suspended||f.license_status==='suspended'||f.license_status==='cancelled')?'red':s?.overdue_days>0?'yellow':'green')}>{statusLabel[f.license_status]||f.license_status}</span></td><td>{s?.overdue_days||0}</td><td>{brl(s?.open_overdue_amount||0)}</td><td>{f.next_due_date?new Date(f.next_due_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</td><td><button className="button secondary" onClick={()=>choose(f.id)}>Gerenciar</button></td></tr>})}</tbody></table></div></div>

  {selected&&state&&<div className="section"><div className="card"><div className="section-heading"><div><div className="eyebrow">Franquia selecionada</div><h2>{selected.trade_name}</h2><p className="subtitle">{selected.plan_name||'Sem plano'} · licença {statusLabel[selected.license_status]||selected.license_status}</p></div>{state.operation_suspended?<span className="pill red"><LockKeyhole size={13}/>Operação suspensa</span>:state.overdue_days>0?<span className="pill yellow"><AlertTriangle size={13}/>{state.overdue_days} dias em atraso</span>:<span className="pill green"><ShieldCheck size={13}/>Regular</span>}</div>
   <div className="regional-kpis"><div className="regional-kpi"><span>Último pagamento</span><strong>{lastPaid?brl(lastPaid.total_due):'—'}</strong><small>{lastPaid?.paid_at?new Date(lastPaid.paid_at).toLocaleDateString('pt-BR'):'Nenhum pagamento registrado'}</small></div><div className="regional-kpi"><span>Próximo / atual vencimento</span><strong>{nextOpen?new Date(nextOpen.due_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</strong><small>{nextOpen?brl(nextOpen.total_due):'Sem fatura aberta'}</small></div><div className="regional-kpi"><span>Dias em atraso</span><strong>{state.overdue_days}</strong><small>{brl(state.open_overdue_amount)} vencidos</small></div><div className="regional-kpi"><span>Permissões automáticas</span><strong>{state.allow_new_rides?'Corridas ✓':'Corridas ✕'}</strong><small>{state.allow_new_drivers?'Novos motoristas permitidos':'Novos motoristas bloqueados'}</small></div></div>

   <div className="section-heading" style={{marginTop:24}}><div><h3>Regras de bloqueio automático</h3><p className="subtitle">Valores padrão sugeridos: 3 / 5 / 10 / 30 dias.</p></div></div><div className="form-grid"><div className="field"><label>Alertar antes do vencimento</label><input className="input" type="number" min="0" max="60" value={rules.alert} onChange={e=>setRules({...rules,alert:Number(e.target.value)})}/><small>dias antes</small></div><div className="field"><label>Bloquear novos motoristas</label><input className="input" type="number" min="0" max="180" value={rules.drivers} onChange={e=>setRules({...rules,drivers:Number(e.target.value)})}/><small>dias de atraso</small></div><div className="field"><label>Bloquear novas corridas</label><input className="input" type="number" min="0" max="180" value={rules.rides} onChange={e=>setRules({...rules,rides:Number(e.target.value)})}/><small>dias de atraso</small></div><div className="field"><label>Suspender operação completa</label><input className="input" type="number" min="0" max="365" value={rules.suspend} onChange={e=>setRules({...rules,suspend:Number(e.target.value)})}/><small>dias de atraso</small></div></div><div className="toolbar" style={{marginTop:14}}><button className="button" onClick={()=>void saveRules()} disabled={busy}>Salvar regras</button></div>

   <div className="section-heading" style={{marginTop:28}}><div><h3>Ações manuais da Matriz</h3><p className="subtitle">A justificativa é obrigatória e aparece na auditoria.</p></div></div><div className="field"><label>Justificativa da ação</label><textarea className="input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: acordo comercial, inadimplência confirmada, prorrogação autorizada..."/></div><div className="toolbar" style={{marginTop:12}}><button className="button danger" onClick={()=>void license('suspend')} disabled={busy}><LockKeyhole size={15}/>Bloquear imediatamente</button><button className="button secondary" onClick={()=>void license('reactivate')} disabled={busy}><UnlockKeyhole size={15}/>Reativar</button><button className="button danger" onClick={()=>void license('cancel')} disabled={busy}>Cancelar licença</button><div style={{display:'flex',gap:6,alignItems:'center'}}><input className="input" style={{width:82}} type="number" min="1" max="180" value={extendDays} onChange={e=>setExtendDays(e.target.value)}/><button className="button secondary" onClick={()=>void extend()} disabled={busy}><CalendarClock size={15}/>Prorrogar vencimento</button></div></div>

   <div className="section-heading" style={{marginTop:28}}><div><h3>Multas, créditos e descontos</h3><p className="subtitle">O ajuste entra como linha separada no demonstrativo CLICK-GO do franqueado.</p></div><CircleDollarSign size={20}/></div><div className="form-grid"><div className="field"><label>Tipo</label><select className="input" value={adjustment.type} onChange={e=>setAdjustment({...adjustment,type:e.target.value})}><option value="fine">Multa / acréscimo</option><option value="credit">Crédito</option><option value="discount">Desconto</option><option value="other">Outro acréscimo</option></select></div><div className="field"><label>Valor</label><input className="input" type="number" min="0.01" step="0.01" value={adjustment.amount} onChange={e=>setAdjustment({...adjustment,amount:e.target.value})}/></div><div className="field"><label>Descrição</label><input className="input" value={adjustment.description} onChange={e=>setAdjustment({...adjustment,description:e.target.value})} placeholder="Ex.: crédito comercial autorizado"/></div></div><div className="toolbar" style={{marginTop:12}}><button className="button secondary" onClick={()=>void addAdjustment()} disabled={busy}>Aplicar ajuste</button></div>
  </div></div>}
 </>
}
