'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Block={id:string;profile_id:string|null;driver_id:string|null;franchise_id:string|null;reason:string;blocked_at:string;unblocked_at:string|null;active:boolean}
type Profile={id:string;full_name:string|null;email:string|null;role:string;active:boolean}
type Franchise={id:string;trade_name:string;active:boolean}
export default function BlockManager(){
 const[rows,setRows]=useState<Block[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[franchises,setFranchises]=useState<Franchise[]>([]);const[msg,setMsg]=useState('');const[targetType,setTargetType]=useState('franchise');const[targetId,setTargetId]=useState('');const[reason,setReason]=useState('')
 async function load(){const[b,p,f]=await Promise.all([supabase.from('account_blocks').select('*').order('blocked_at',{ascending:false}).limit(200),supabase.from('profiles').select('id,full_name,email,role,active').in('role',['driver','passenger']).order('full_name'),supabase.from('franchises').select('id,trade_name,active').is('deleted_at',null).order('trade_name')]);if(b.error)setMsg(b.error.message);else setRows((b.data||[]) as Block[]);setProfiles((p.data||[]) as Profile[]);setFranchises((f.data||[]) as Franchise[])}
 useEffect(()=>{load()},[])
 async function authBlock(userId:string,block:boolean){const{data,error}=await supabase.functions.invoke('admin-users',{body:{action:block?'block_user':'unblock_user',user_id:userId}});if(error||data?.error)throw new Error(error?.message||data.error)}
 async function add(e:React.FormEvent){e.preventDefault();if(!targetId){setMsg('Selecione o alvo.');return}const{data:{user}}=await supabase.auth.getUser();const payload:any={reason,blocked_by:user?.id||null,active:true};payload[targetType==='franchise'?'franchise_id':targetType==='driver'?'driver_id':'profile_id']=targetId;const{error}=await supabase.from('account_blocks').insert(payload);if(error){setMsg(error.message);return}try{if(targetType==='franchise')await supabase.from('franchises').update({active:false,blocked_at:new Date().toISOString(),blocked_reason:reason}).eq('id',targetId);if(targetType==='driver'){await authBlock(targetId,true);await supabase.from('drivers').update({status:'blocked',online:false}).eq('id',targetId)}if(targetType==='profile')await authBlock(targetId,true);setTargetId('');setReason('');setMsg('Bloqueio aplicado, inclusive no acesso da conta.');load()}catch(e:any){setMsg(e.message||'Bloqueio registrado, mas houve erro ao bloquear o acesso.') }}
 async function unblock(b:Block){await supabase.from('account_blocks').update({active:false,unblocked_at:new Date().toISOString()}).eq('id',b.id);try{if(b.franchise_id)await supabase.from('franchises').update({active:true,blocked_at:null,blocked_reason:null}).eq('id',b.franchise_id);if(b.driver_id){await authBlock(b.driver_id,false);await supabase.from('drivers').update({status:'approved',online:false}).eq('id',b.driver_id)}if(b.profile_id)await authBlock(b.profile_id,false);setMsg('Acesso liberado.');load()}catch(e:any){setMsg(e.message||'Não foi possível liberar o acesso.')}}
 const target=(b:Block)=>{if(b.franchise_id)return `Franquia: ${franchises.find(f=>f.id===b.franchise_id)?.trade_name||b.franchise_id}`;const id=b.driver_id||b.profile_id;const p=profiles.find(x=>x.id===id);return `${b.driver_id?'Motorista':'Usuário'}: ${p?.full_name||p?.email||id}`}
 const options=targetType==='franchise'?franchises:profiles.filter(p=>targetType==='driver'?p.role==='driver':p.role==='passenger')
 return <><div className="card"><form onSubmit={add}><div className="form-grid"><div className="field"><label>Tipo de alvo</label><select className="input" value={targetType} onChange={e=>{setTargetType(e.target.value);setTargetId('')}}><option value="franchise">Franquia</option><option value="driver">Motorista</option><option value="profile">Passageiro/usuário</option></select></div><div className="field"><label>Alvo</label><select className="input" value={targetId} onChange={e=>setTargetId(e.target.value)} required><option value="">Selecione</option>{options.map((x:any)=><option key={x.id} value={x.id}>{targetType==='franchise'?x.trade_name:(x.full_name||x.email||x.id)}</option>)}</select></div><div className="field"><label>Motivo</label><textarea className="input" value={reason} onChange={e=>setReason(e.target.value)} required/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button danger">Bloquear com um clique</button></div>{msg&&<p className="empty">{msg}</p>}</form></div><div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Alvo</th><th>Motivo</th><th>Bloqueado em</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Nenhum bloqueio registrado.</td></tr>:rows.map(b=><tr key={b.id}><td>{target(b)}</td><td>{b.reason}</td><td>{new Date(b.blocked_at).toLocaleString('pt-BR')}</td><td><span className={'pill '+(b.active?'red':'green')}>{b.active?'Bloqueado':'Liberado'}</span></td><td>{b.active&&<button className="button secondary" onClick={()=>unblock(b)}>Desbloquear</button>}</td></tr>)}</tbody></table></div></div></>
}
