'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Coupon={id:string;code:string;discount_type:string;discount_value:number;max_uses:number|null;uses_count:number;active:boolean}
export default function CouponManager(){
 const [rows,setRows]=useState<Coupon[]>([]);const [msg,setMsg]=useState('');const [form,setForm]=useState({code:'',discount_type:'percentage',discount_value:'10',max_uses:'100',min_ride_value:'0'})
 async function load(){const {data,error}=await supabase.from('coupons').select('id,code,discount_type,discount_value,max_uses,uses_count,active').order('created_at',{ascending:false});if(error)setMsg(error.message);else setRows((data||[]) as Coupon[])}
 useEffect(()=>{load()},[])
 async function add(e:React.FormEvent){e.preventDefault();const {error}=await supabase.from('coupons').insert({code:form.code.toUpperCase(),discount_type:form.discount_type,discount_value:Number(form.discount_value),max_uses:form.max_uses?Number(form.max_uses):null,min_ride_value:Number(form.min_ride_value),active:true});if(error){setMsg(error.message);return}setForm({code:'',discount_type:'percentage',discount_value:'10',max_uses:'100',min_ride_value:'0'});setMsg('Cupom criado.');load()}
 async function toggle(c:Coupon){await supabase.from('coupons').update({active:!c.active}).eq('id',c.id);load()}
 async function remove(id:string){if(!confirm('Excluir cupom?'))return;await supabase.from('coupons').delete().eq('id',id);load()}
 return <><div className="card"><form onSubmit={add}><div className="form-grid"><div className="field"><label>Código</label><input className="input" value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></div><div className="field"><label>Tipo</label><select className="input" value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})}><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select></div><div className="field"><label>Desconto</label><input className="input" type="number" step="0.01" value={form.discount_value} onChange={e=>setForm({...form,discount_value:e.target.value})}/></div><div className="field"><label>Máximo de usos</label><input className="input" type="number" value={form.max_uses} onChange={e=>setForm({...form,max_uses:e.target.value})}/></div><div className="field"><label>Corrida mínima</label><input className="input" type="number" step="0.01" value={form.min_ride_value} onChange={e=>setForm({...form,min_ride_value:e.target.value})}/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button">Salvar cupom</button></div>{msg&&<p className="empty">{msg}</p>}</form></div><div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Código</th><th>Tipo</th><th>Desconto</th><th>Usos</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={6} className="empty">Nenhum cupom cadastrado.</td></tr>:rows.map(c=><tr key={c.id}><td>{c.code}</td><td>{c.discount_type}</td><td>{c.discount_value}</td><td>{c.uses_count}/{c.max_uses??'∞'}</td><td><span className={'pill '+(c.active?'green':'red')}>{c.active?'Ativo':'Inativo'}</span></td><td><div className="toolbar"><button className="button secondary" onClick={()=>toggle(c)}>{c.active?'Pausar':'Ativar'}</button><button className="button danger" onClick={()=>remove(c.id)}>Excluir</button></div></td></tr>)}</tbody></table></div></div></>
}
