'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import RealtimeMapData from '@/components/RealtimeMapData'

type RideRow={city_id:string|null;franchise_id:string|null;final_fare:number|string|null}
type CityRow={id:string;name:string;state:string}
type FranchiseRow={id:string;trade_name:string|null}
type Row={city:string;franchise:string;rides:number;gross:number}
type Metrics={franchises:number;online:number;ongoing:number;revenue:number;pending:number;tickets:number}

export default function DashboardData(){
 const[k,setK]=useState<Metrics>({franchises:0,online:0,ongoing:0,revenue:0,pending:0,tickets:0}),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState('Carregando dados…')
 useEffect(()=>{void load()},[])
 async function count(table:string,filter?:[string,string]){let q=supabase.from(table).select('*',{count:'exact',head:true});if(filter)q=q.eq(filter[0],filter[1]);const{count,error}=await q;if(error)throw error;return count||0}
 async function load(){try{const start=new Date();start.setHours(0,0,0,0);const[franchises,online,ongoingRes,pendingPayments,pendingPayouts,tickets,rideRes,cityRes,frRes]=await Promise.all([count('franchises',['active','true']),count('drivers',['online','true']),supabase.from('rides').select('id',{count:'exact',head:true}).in('status',['accepted','driver_arriving','arrived','in_progress']),count('payments',['status','pending']),count('payouts',['status','requested']),count('support_tickets',['status','open']),supabase.from('rides').select('city_id,franchise_id,final_fare').eq('status','completed').gte('completed_at',start.toISOString()),supabase.from('cities').select('id,name,state'),supabase.from('franchises').select('id,trade_name')]);if(ongoingRes.error)throw ongoingRes.error;if(rideRes.error)throw rideRes.error;if(cityRes.error)throw cityRes.error;if(frRes.error)throw frRes.error;const rides=(rideRes.data||[]) as RideRow[],cities=(cityRes.data||[]) as CityRow[],frs=(frRes.data||[]) as FranchiseRow[];const cityById=new Map(cities.map(c=>[c.id,c])),frById=new Map(frs.map(f=>[f.id,f])),grouped=new Map<string,Row>();let revenue=0;for(const ride of rides){const fare=Number(ride.final_fare||0);revenue+=fare;const key=`${ride.city_id||''}|${ride.franchise_id||''}`,city=ride.city_id?cityById.get(ride.city_id):undefined,fr=ride.franchise_id?frById.get(ride.franchise_id):undefined,row=grouped.get(key)||{city:city?`${city.name}/${city.state}`:'—',franchise:fr?.trade_name||'—',rides:0,gross:0};row.rides++;row.gross+=fare;grouped.set(key,row)}setK({franchises,online,ongoing:ongoingRes.count||0,revenue,pending:pendingPayments+pendingPayouts,tickets});setRows([...grouped.values()].sort((a,b)=>b.gross-a.gross).slice(0,4));setMsg('')}catch(e){setMsg(e instanceof Error?e.message:'Erro ao carregar dashboard')}}
 const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0),primary=[['Franquias ativas',k.franchises,'na rede'],['Motoristas online',k.online,'agora'],['Corridas em andamento',k.ongoing,'ao vivo'],['Faturamento hoje',brl(k.revenue),'corridas concluídas']]
 return <div className="simple-page">{msg&&<div className="simple-card" style={{marginBottom:12}}>{msg}</div>}<div className="simple-kpis">{primary.map(([label,value,hint])=><div className="simple-kpi" key={String(label)}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>)}</div><div className="simple-grid-2"><div className="simple-card"><div className="simple-section-head"><div><h2>Mapa da operação</h2><p>Veja onde a rede está trabalhando agora.</p></div><Link href="/mapa" className="simple-btn">Abrir mapa</Link></div><RealtimeMapData compact/></div><div className="simple-card"><h2>Precisa da sua atenção</h2><p>Só mostramos o que pede alguma decisão.</p><div className="simple-attention"><div className={`simple-attention-row ${k.pending?'warn':''}`}><span>Pendências financeiras</span><strong>{k.pending}</strong></div><div className={`simple-attention-row ${k.tickets?'warn':''}`}><span>Chamados abertos</span><strong>{k.tickets}</strong></div></div><div className="simple-quick"><Link href="/franquias"><strong>Franquias</strong><span>Licenças, planos e cidades</span></Link><Link href="/financeiro"><strong>Financeiro</strong><span>Cobranças e repasses</span></Link><Link href="/suporte"><strong>Suporte</strong><span>Chamados que precisam de ajuda</span></Link><Link href="/planos"><strong>Planos</strong><span>Preços e regras comerciais</span></Link></div></div></div><section className="simple-section"><div className="simple-section-head"><div><h2>Movimento de hoje</h2><p>As cidades com maior atividade no dia.</p></div><Link className="simple-btn" href="/relatorios">Ver relatórios</Link></div><div className="simple-table-wrap"><table className="simple-table"><thead><tr><th>Cidade</th><th>Franquia</th><th>Corridas</th><th>Faturamento</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={4}>Ainda não há corridas concluídas hoje.</td></tr>:rows.map((r,i)=><tr key={`${r.city}-${i}`}><td><strong>{r.city}</strong></td><td>{r.franchise}</td><td>{r.rides}</td><td>{brl(r.gross)}</td></tr>)}</tbody></table></div></section></div>
}
