'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '@/lib/supabase'

type Driver={id:string;status:string;city_id:string|null;commission_percent:number|null;rating:number}
type Profile={id:string;full_name:string|null;phone:string|null;email:string|null}
type Ride={id:string;driver_id:string|null;status:string;final_fare:number|null;estimated_fare:number|null;requested_at:string;completed_at:string|null}
type Tx={driver_id:string|null;valor_motorista:number;valor_total:number;data_criacao:string}
type Ticket={requester_id:string|null;status:string;created_at:string}
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)
const statusLabel:Record<string,string>={pending:'Pendente',approved:'Aprovado',rejected:'Rejeitado',blocked:'Bloqueado'}
export default function DriverReports(){
 const[drivers,setDrivers]=useState<Driver[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[rides,setRides]=useState<Ride[]>([]);const[txs,setTxs]=useState<Tx[]>([]);const[tickets,setTickets]=useState<Ticket[]>([]);const[query,setQuery]=useState('')
 async function load(){const[d,p,r,t,k]=await Promise.all([supabase.from('drivers').select('id,status,city_id,commission_percent,rating'),supabase.from('profiles').select('id,full_name,phone,email').eq('role','driver'),supabase.from('rides').select('id,driver_id,status,final_fare,estimated_fare,requested_at,completed_at').not('driver_id','is',null),supabase.from('financial_transactions').select('driver_id,valor_motorista,valor_total,data_criacao').not('driver_id','is',null),supabase.from('support_tickets').select('requester_id,status,created_at')]);setDrivers((d.data||[]) as Driver[]);setProfiles((p.data||[]) as Profile[]);setRides((r.data||[]) as Ride[]);setTxs((t.data||[]) as Tx[]);setTickets((k.data||[]) as Ticket[])}
 useEffect(()=>{void load()},[])
 const rows=useMemo(()=>drivers.map(d=>{const p=profiles.find(x=>x.id===d.id);const dr=rides.filter(r=>r.driver_id===d.id);const completed=dr.filter(r=>r.status==='completed');const cancelled=dr.filter(r=>r.status==='cancelled');const earning=txs.filter(t=>t.driver_id===d.id).reduce((s,t)=>s+Number(t.valor_motorista||0),0);const gross=txs.filter(t=>t.driver_id===d.id).reduce((s,t)=>s+Number(t.valor_total||0),0);const support=tickets.filter(t=>t.requester_id===d.id);const last=[...dr].sort((a,b)=>new Date(b.requested_at).getTime()-new Date(a.requested_at).getTime())[0];return{d,p,total:dr.length,completed:completed.length,cancelled:cancelled.length,earning,gross,support:support.length,openSupport:support.filter(t=>t.status!=='closed').length,last:last?.requested_at||null}}).filter(x=>!query||`${x.p?.full_name||''} ${x.p?.email||''} ${x.p?.phone||''}`.toLowerCase().includes(query.toLowerCase())),[drivers,profiles,rides,txs,tickets,query])
 return <><div className="card"><div className="field"><label>Buscar motorista</label><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, e-mail ou telefone"/></div></div><div className="table-wrap" style={{marginTop:16}}><table className="table"><thead><tr><th>Motorista</th><th>Status</th><th>Chamados</th><th>Concluídos</th><th>Cancelados</th><th>Ganhos</th><th>Movimentado</th><th>Suporte</th><th>Última corrida</th><th>Contato</th></tr></thead><tbody>{rows.map(x=><tr key={x.d.id}><td><strong>{x.p?.full_name?.trim()||'Motorista sem nome cadastrado'}</strong><br/><span className="empty">Comissão: {x.d.commission_percent??'padrão'}%</span></td><td>{statusLabel[x.d.status]||x.d.status}<br/><span className="empty">★ {Number(x.d.rating||0).toFixed(1)}</span></td><td>{x.total}</td><td>{x.completed}</td><td>{x.cancelled}</td><td>{money(x.earning)}</td><td>{money(x.gross)}</td><td>{x.support}{x.openSupport?` (${x.openSupport} abertos)`:''}</td><td>{x.last?new Date(x.last).toLocaleString('pt-BR'):'—'}</td><td>{x.p?.phone?<a href={`tel:${x.p.phone}`}>{x.p.phone}</a>:'—'}<br/>{x.p?.email||''}</td></tr>)}</tbody></table></div></>
}
