'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Kind='payments'|'payouts'|'advances'|'audit'|'passengers'
export default function FinanceQueue({kind}:{kind:Kind}){
 const [rows,setRows]=useState<any[]>([]);const [msg,setMsg]=useState('')
 async function load(){let q:any;if(kind==='payments')q=supabase.from('payments').select('*').order('created_at',{ascending:false}).limit(100);if(kind==='payouts')q=supabase.from('payouts').select('*').order('requested_at',{ascending:false}).limit(100);if(kind==='advances')q=supabase.from('advance_requests').select('*').order('requested_at',{ascending:false}).limit(100);if(kind==='audit')q=supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(200);if(kind==='passengers')q=supabase.from('profiles').select('id,full_name,phone,email,city_id,active,created_at').eq('role','passenger').order('created_at',{ascending:false}).limit(200);const{data,error}=await q;if(error)setMsg(error.message);else{setRows(data||[]);setMsg('')}}
 useEffect(()=>{load()},[kind])
 async function paymentStatus(id:string,status:string){const{error}=await supabase.rpc('matrix_set_payment_status',{p_payment_id:id,p_status:status});setMsg(error?error.message:'Status do pagamento atualizado e auditado.');if(!error)load()}
 async function payoutStatus(id:string,status:string){const{error}=await supabase.rpc('matrix_set_payout_status',{p_payout_id:id,p_status:status,p_notes:null});setMsg(error?error.message:'Status do repasse atualizado e auditado.');if(!error)load()}
 async function advanceStatus(id:string,status:string){const{error}=await supabase.rpc('matrix_set_advance_status',{p_advance_id:id,p_status:status});setMsg(error?error.message:'Status da antecipação atualizado e auditado.');if(!error)load()}
 async function togglePassenger(r:any){const{data,error}=await supabase.functions.invoke('admin-users',{body:{action:r.active?'block_user':'unblock_user',user_id:r.id}});const fail=error?.message||data?.error;setMsg(fail||(!r.active?'Passageiro ativado.':'Passageiro bloqueado.'));if(!fail)load()}
 const brl=(v:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0))
 const finalPayment=(s:string)=>['paid','cancelled','refunded'].includes(s)
 const finalPayout=(s:string)=>['paid','rejected','cancelled'].includes(s)
 const finalAdvance=(s:string)=>['paid','rejected','cancelled'].includes(s)
 if(kind==='audit')return <><p className="empty">{msg}</p><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>ID</th><th>Ator</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Sem logs.</td></tr>:rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('pt-BR')}</td><td>{r.action}</td><td>{r.entity}</td><td>{r.entity_id||'—'}</td><td>{r.actor_id||'sistema'}</td></tr>)}</tbody></table></div></>
 if(kind==='passengers')return <><p className="empty">{msg}</p><div className="table-wrap"><table className="table"><thead><tr><th>Passageiro</th><th>Contato</th><th>Vínculo</th><th>Status</th><th>Cadastro</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={6} className="empty">Nenhum passageiro.</td></tr>:rows.map(r=><tr key={r.id}><td>{r.full_name||r.id}<br/><span className="empty">{r.email||''}</span></td><td>{r.phone?<a href={`tel:${r.phone}`}>{r.phone}</a>:'—'}</td><td>{r.city_id||'Cadastro livre / cidade automática'}</td><td><span className={'pill '+(r.active?'green':'red')}>{r.active?'Ativo':'Bloqueado'}</span></td><td>{new Date(r.created_at).toLocaleDateString('pt-BR')}</td><td><button className={r.active?'button danger':'button'} onClick={()=>togglePassenger(r)}>{r.active?'Bloquear':'Ativar'}</button></td></tr>)}</tbody></table></div></>
 if(kind==='payments')return <><p className="empty">{msg}</p><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Método</th><th>Valor</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Sem pagamentos.</td></tr>:rows.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('pt-BR')}</td><td>{r.method}</td><td>{brl(r.amount)}</td><td>{r.status}</td><td><select className="input" value={r.status} disabled={finalPayment(r.status)} onChange={e=>paymentStatus(r.id,e.target.value)}><option value="pending" disabled={r.status==='authorized'}>Pendente</option><option value="authorized" disabled={r.status==='failed'}>Autorizado</option><option value="paid">Pago</option><option value="failed">Falhou</option><option value="cancelled">Cancelado</option>{r.status==='refunded'&&<option value="refunded">Estornado</option>}</select></td></tr>)}</tbody></table></div></>
 if(kind==='payouts')return <><p className="empty">{msg}</p><div className="table-wrap"><table className="table"><thead><tr><th>Solicitado</th><th>Valor</th><th>Destino</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Sem repasses.</td></tr>:rows.map(r=><tr key={r.id}><td>{new Date(r.requested_at).toLocaleString('pt-BR')}</td><td>{brl(r.amount)}</td><td>{r.destination_type}</td><td>{r.status}</td><td><select className="input" value={r.status} disabled={finalPayout(r.status)} onChange={e=>payoutStatus(r.id,e.target.value)}><option value="requested" disabled={r.status!=='requested'}>Solicitado</option><option value="approved">Aprovado</option><option value="processing">Processando</option><option value="paid">Pago</option><option value="rejected">Rejeitado</option><option value="cancelled">Cancelado</option></select></td></tr>)}</tbody></table></div></>
 return <><p className="empty">{msg}</p><div className="table-wrap"><table className="table"><thead><tr><th>Solicitado</th><th>Valor</th><th>Taxa</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Sem antecipações.</td></tr>:rows.map(r=><tr key={r.id}><td>{new Date(r.requested_at).toLocaleString('pt-BR')}</td><td>{brl(r.amount)}</td><td>{brl(r.fee)}</td><td>{r.status}</td><td><select className="input" value={r.status} disabled={finalAdvance(r.status)} onChange={e=>advanceStatus(r.id,e.target.value)}><option value="requested" disabled={r.status!=='requested'}>Solicitado</option><option value="approved">Aprovado</option><option value="paid">Pago</option><option value="rejected">Rejeitado</option><option value="cancelled">Cancelado</option></select></td></tr>)}</tbody></table></div></>
}
