'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Franchise={id:string;trade_name:string;legal_name:string;document:string|null;active:boolean;contact_name:string|null;contact_email:string|null;contact_phone:string|null}
type City={id:string;name:string;state:string}
type Temp={franchise:string;email:string;password:string;created:boolean}
type FranchiseAdmin={id:string;full_name:string|null;email:string|null;franchise_id:string|null;active:boolean}
const empty={trade_name:'',legal_name:'',document:'',contact_name:'',contact_email:'',contact_phone:''}

export default function FranchiseManager(){
 const[rows,setRows]=useState<Franchise[]>([]);const[cities,setCities]=useState<City[]>([]);const[links,setLinks]=useState<Record<string,string[]>>({});const[msg,setMsg]=useState('');const[editingId,setEditingId]=useState<string|null>(null)
 const[form,setForm]=useState(empty);const[franchiseId,setFranchiseId]=useState('');const[cityId,setCityId]=useState('');const[temp,setTemp]=useState<Temp|null>(null);const[busyTemp,setBusyTemp]=useState<string|null>(null)
 const[admins,setAdmins]=useState<FranchiseAdmin[]>([]);const[adminTarget,setAdminTarget]=useState<Record<string,string>>({});const[busyAdmin,setBusyAdmin]=useState<string|null>(null)
 async function load(){
  const[f,c,l,a]=await Promise.all([
   supabase.from('franchises').select('id,trade_name,legal_name,document,active,contact_name,contact_email,contact_phone').is('deleted_at',null).order('created_at',{ascending:false}),
   supabase.from('cities').select('id,name,state').eq('active',true).order('name'),
   supabase.from('franchise_cities').select('franchise_id,city_id'),
   supabase.from('profiles').select('id,full_name,email,franchise_id,active').eq('role','franchise_admin').order('created_at',{ascending:false})
  ])
  if(f.error)setMsg(f.error.message);else setRows(f.data||[])
  setCities(c.data||[])
  const map:Record<string,string[]>={};(l.data||[]).forEach((x:any)=>{map[x.franchise_id]=[...(map[x.franchise_id]||[]),x.city_id]});setLinks(map)
  if(a.error)setMsg(a.error.message);else{const list=(a.data||[]) as FranchiseAdmin[];setAdmins(list);setAdminTarget(prev=>{const next={...prev};list.forEach(x=>{if(next[x.id]===undefined)next[x.id]=x.franchise_id||''});return next})}
 }
 useEffect(()=>{load()},[])
 async function save(e:React.FormEvent){e.preventDefault();const payload={...form,document:form.document||null};const q=editingId?supabase.from('franchises').update(payload).eq('id',editingId):supabase.from('franchises').insert({...payload,active:true});const{error}=await q;if(error){setMsg(error.message);return}setForm(empty);setEditingId(null);setMsg(editingId?'Franquia atualizada.':'Franquia cadastrada.');load()}
 function edit(f:Franchise){setEditingId(f.id);setForm({trade_name:f.trade_name,legal_name:f.legal_name,document:f.document||'',contact_name:f.contact_name||'',contact_email:f.contact_email||'',contact_phone:f.contact_phone||''});window.scrollTo({top:0,behavior:'smooth'})}
 async function toggle(f:Franchise){const update=f.active?{active:false,blocked_at:new Date().toISOString(),blocked_reason:'Bloqueio pelo Super Admin'}:{active:true,blocked_at:null,blocked_reason:null};const{error}=await supabase.from('franchises').update(update).eq('id',f.id);if(error)setMsg(error.message);else setMsg(f.active?'Franquia bloqueada.':'Franquia ativada.');load()}
 async function remove(id:string){if(!confirm('Excluir esta franquia da operação? O histórico será preservado.'))return;const{error}=await supabase.from('franchises').update({active:false,deleted_at:new Date().toISOString()}).eq('id',id);if(error)setMsg(error.message);else setMsg('Franquia excluída.');load()}
 async function assign(){if(!franchiseId||!cityId){setMsg('Selecione franquia e cidade.');return}const current=await supabase.from('franchise_cities').select('franchise_id').eq('city_id',cityId).maybeSingle();if(current.data?.franchise_id&&current.data.franchise_id!==franchiseId){if(!confirm('Esta cidade já possui outro franqueado. Deseja transferir?'))return;const del=await supabase.from('franchise_cities').delete().eq('city_id',cityId);if(del.error){setMsg(del.error.message);return}}const{error}=await supabase.from('franchise_cities').upsert({franchise_id:franchiseId,city_id:cityId});if(error){setMsg(error.message);return}setMsg('Cidade vinculada.');load()}
 async function reassignAdmin(admin:FranchiseAdmin){const target=adminTarget[admin.id];if(!target){setMsg('Escolha uma franquia ativa para este acesso.');return}if(!confirm(`Vincular o acesso ${admin.email||admin.full_name||admin.id} à franquia selecionada?`))return;setBusyAdmin(admin.id);const{error}=await supabase.rpc('super_admin_reassign_franchise_admin',{p_profile_id:admin.id,p_franchise_id:target});setBusyAdmin(null);setMsg(error?error.message:'Acesso do franqueado vinculado corretamente.');if(!error)load()}
 async function gerarSenha(f:Franchise){
  if(!f.active){setMsg('Ative a franquia antes de gerar o acesso.');return}
  const chosen=window.prompt('Digite uma senha temporária (mínimo 8 caracteres, com letras e números).\n\nSe deixar em branco, o sistema gera uma senha segura automaticamente.','')
  if(chosen===null)return
  const manual=chosen.trim()
  if(manual&&manual.length<8){setMsg('A senha temporária precisa ter pelo menos 8 caracteres.');return}
  if(manual&&(!/[A-Za-z]/.test(manual)||!/[0-9]/.test(manual))){setMsg('Use pelo menos uma letra e um número na senha temporária.');return}
  if(!confirm(`Criar nova senha temporária para ${f.trade_name}? A senha anterior deixará de funcionar.`))return
  setBusyTemp(f.id);setTemp(null);setMsg('Gerando senha temporária...')
  const body:any={action:'generate',franchise_id:f.id};if(manual)body.temporary_password=manual
  const{data,error}=await supabase.functions.invoke('franchise-temp-password',{body});setBusyTemp(null)
  if(error||data?.error){setMsg(data?.error||error?.message||'Falha ao gerar senha temporária.');return}
  setTemp({franchise:f.trade_name,email:data.email,password:data.temporary_password,created:!!data.created_access});setMsg('Senha temporária criada. Use exatamente o e-mail exibido abaixo para entrar.')
 }
 async function copy(v:string,label:string){try{await navigator.clipboard.writeText(v);setMsg(label+' copiado.')}catch{setMsg('Copie manualmente: '+v)}}
 function cityNames(id:string){return(links[id]||[]).map(cid=>{const c=cities.find(x=>x.id===cid);return c?`${c.name}/${c.state}`:cid}).join(', ')||'—'}
 const activeRows=rows.filter(f=>f.active)
 const franchiseName=(id:string|null)=>{if(!id)return 'Sem vínculo';const f=rows.find(x=>x.id===id);return f?f.trade_name:'Franquia excluída/inválida'}
 return <>
 <div className="card"><form onSubmit={save}><div className="form-grid"><div className="field"><label>Nome fantasia</label><input className="input" value={form.trade_name} onChange={e=>setForm({...form,trade_name:e.target.value})} required/></div><div className="field"><label>Razão social</label><input className="input" value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})} required/></div><div className="field"><label>CPF/CNPJ</label><input className="input" value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></div><div className="field"><label>Responsável</label><input className="input" value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></div><div className="field"><label>E-mail</label><input className="input" type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></div><div className="field"><label>Telefone</label><input className="input" value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button">{editingId?'Salvar alterações':'Salvar franquia'}</button>{editingId&&<button type="button" className="button secondary" onClick={()=>{setEditingId(null);setForm(empty)}}>Cancelar edição</button>}</div></form></div>
 {temp&&<div className="card" style={{marginTop:16,border:'2px solid #ffd400'}}><div className="eyebrow">SENHA TEMPORÁRIA — MOSTRADA UMA ÚNICA VEZ</div><h2>{temp.franchise}</h2><p className="empty">{temp.created?'O acesso do franqueado foi criado agora.':'A senha anterior foi substituída.'} No primeiro login será obrigatório criar uma nova senha. Entre com o e-mail abaixo, que é o e-mail real da conta de acesso.</p><div className="form-grid"><div className="field"><label>E-mail de acesso</label><input className="input" readOnly value={temp.email}/><button className="button secondary" style={{marginTop:8}} onClick={()=>copy(temp.email,'E-mail')}>Copiar e-mail</button></div><div className="field"><label>Senha temporária</label><input className="input" readOnly value={temp.password}/><button className="button" style={{marginTop:8}} onClick={()=>copy(temp.password,'Senha')}>Copiar senha</button></div></div><button className="button secondary" style={{marginTop:12}} onClick={()=>setTemp(null)}>Ocultar senha</button></div>}
 <div className="section"><h2>Atribuir cidade</h2><div className="card"><div className="form-grid"><div className="field"><label>Franquia</label><select className="input" value={franchiseId} onChange={e=>setFranchiseId(e.target.value)}><option value="">Selecione</option>{rows.map(f=><option value={f.id} key={f.id}>{f.trade_name}{!f.active?' (bloqueada)':''}</option>)}</select></div><div className="field"><label>Cidade</label><select className="input" value={cityId} onChange={e=>setCityId(e.target.value)}><option value="">Selecione</option>{cities.map(c=><option value={c.id} key={c.id}>{c.name}/{c.state}</option>)}</select></div></div><div className="toolbar" style={{marginTop:14}}><button className="button" onClick={assign}>Vincular / transferir cidade</button></div></div></div>
 <div className="section"><h2>Acessos dos franqueados</h2><p className="subtitle">Corrija aqui contas que ficaram vinculadas a uma franquia antiga, bloqueada ou excluída.</p><div className="table-wrap"><table className="table"><thead><tr><th>Acesso</th><th>Vínculo atual</th><th>Nova franquia</th><th>Ação</th></tr></thead><tbody>{admins.length===0?<tr><td colSpan={4} className="empty">Nenhum acesso de franqueado.</td></tr>:admins.map(a=><tr key={a.id}><td><b>{a.full_name||'Franqueado'}</b><br/><span className="empty">{a.email||a.id}</span></td><td>{franchiseName(a.franchise_id)}</td><td><select className="input" value={adminTarget[a.id]||''} onChange={e=>setAdminTarget({...adminTarget,[a.id]:e.target.value})}><option value="">Escolha uma franquia ativa</option>{activeRows.map(f=><option key={f.id} value={f.id}>{f.trade_name}</option>)}</select></td><td><button className="button" disabled={busyAdmin===a.id||!adminTarget[a.id]} onClick={()=>reassignAdmin(a)}>{busyAdmin===a.id?'Salvando...':'Corrigir vínculo'}</button></td></tr>)}</tbody></table></div></div>
 {msg&&<p className="empty">{msg}</p>}
 <div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Franquia</th><th>Responsável</th><th>Cidades</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Nenhuma franquia cadastrada.</td></tr>:rows.map(f=><tr key={f.id}><td><strong>{f.trade_name}</strong><br/><span className="empty">{f.legal_name}</span></td><td>{f.contact_name||'—'}<br/><span className="empty">{f.contact_email||''}</span></td><td>{cityNames(f.id)}</td><td><span className={'pill '+(f.active?'green':'red')}>{f.active?'Ativa':'Bloqueada'}</span></td><td><div className="toolbar"><button className="button" disabled={busyTemp===f.id} onClick={()=>gerarSenha(f)}>{busyTemp===f.id?'Gerando...':'Criar senha temporária'}</button><button className="button secondary" onClick={()=>edit(f)}>Editar</button><button className="button secondary" onClick={()=>toggle(f)}>{f.active?'Bloquear':'Ativar'}</button><button className="button danger" onClick={()=>remove(f.id)}>Excluir</button></div></td></tr>)}</tbody></table></div></div>
 </>
}
