'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Franchise={id:string;trade_name:string;legal_name:string;document:string|null;active:boolean;contact_name:string|null;contact_email:string|null;contact_phone:string|null}
type City={id:string;name:string;state:string}
const empty={trade_name:'',legal_name:'',document:'',contact_name:'',contact_email:'',contact_phone:''}
export default function FranchiseManager(){
 const [rows,setRows]=useState<Franchise[]>([]);const [cities,setCities]=useState<City[]>([]);const [links,setLinks]=useState<Record<string,string[]>>({});const [msg,setMsg]=useState('');const [editingId,setEditingId]=useState<string|null>(null)
 const [form,setForm]=useState(empty);const [franchiseId,setFranchiseId]=useState('');const [cityId,setCityId]=useState('')
 async function load(){const f=await supabase.from('franchises').select('id,trade_name,legal_name,document,active,contact_name,contact_email,contact_phone').is('deleted_at',null).order('created_at',{ascending:false});if(f.error)setMsg(f.error.message);else setRows(f.data||[]);const c=await supabase.from('cities').select('id,name,state').eq('active',true).order('name');setCities(c.data||[]);const l=await supabase.from('franchise_cities').select('franchise_id,city_id');const map:Record<string,string[]>={};(l.data||[]).forEach((x:any)=>{map[x.franchise_id]=[...(map[x.franchise_id]||[]),x.city_id]});setLinks(map)}
 useEffect(()=>{load()},[])
 async function save(e:React.FormEvent){e.preventDefault();const payload={...form,document:form.document||null};const q=editingId?supabase.from('franchises').update(payload).eq('id',editingId):supabase.from('franchises').insert({...payload,active:true});const {error}=await q;if(error){setMsg(error.message);return}setForm(empty);setEditingId(null);setMsg(editingId?'Franquia atualizada.':'Franquia cadastrada.');load()}
 function edit(f:Franchise){setEditingId(f.id);setForm({trade_name:f.trade_name,legal_name:f.legal_name,document:f.document||'',contact_name:f.contact_name||'',contact_email:f.contact_email||'',contact_phone:f.contact_phone||''});window.scrollTo({top:0,behavior:'smooth'})}
 async function toggle(f:Franchise){const update=f.active?{active:false,blocked_at:new Date().toISOString(),blocked_reason:'Bloqueio pelo Super Admin'}:{active:true,blocked_at:null,blocked_reason:null};const {error}=await supabase.from('franchises').update(update).eq('id',f.id);if(error)setMsg(error.message);load()}
 async function remove(id:string){if(!confirm('Excluir esta franquia da operação? O histórico será preservado.'))return;const {error}=await supabase.from('franchises').update({active:false,deleted_at:new Date().toISOString()}).eq('id',id);if(error)setMsg(error.message);load()}
 async function assign(){if(!franchiseId||!cityId){setMsg('Selecione franquia e cidade.');return}const {error}=await supabase.from('franchise_cities').upsert({franchise_id:franchiseId,city_id:cityId});if(error){setMsg(error.message);return}setMsg('Cidade atribuída.');load()}
 function cityNames(id:string){return (links[id]||[]).map(cid=>{const c=cities.find(x=>x.id===cid);return c?`${c.name}/${c.state}`:cid}).join(', ')||'—'}
 return <>
 <div className="card"><form onSubmit={save}><div className="form-grid"><div className="field"><label>Nome fantasia</label><input className="input" value={form.trade_name} onChange={e=>setForm({...form,trade_name:e.target.value})} required/></div><div className="field"><label>Razão social</label><input className="input" value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})} required/></div><div className="field"><label>CPF/CNPJ</label><input className="input" value={form.document} onChange={e=>setForm({...form,document:e.target.value})}/></div><div className="field"><label>Responsável</label><input className="input" value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></div><div className="field"><label>E-mail</label><input className="input" type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></div><div className="field"><label>Telefone</label><input className="input" value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button">{editingId?'Salvar alterações':'Salvar franquia'}</button>{editingId&&<button type="button" className="button secondary" onClick={()=>{setEditingId(null);setForm(empty)}}>Cancelar edição</button>}</div></form></div>
 <div className="section"><h2>Atribuir cidade</h2><div className="card"><div className="form-grid"><div className="field"><label>Franquia</label><select className="input" value={franchiseId} onChange={e=>setFranchiseId(e.target.value)}><option value="">Selecione</option>{rows.map(f=><option value={f.id} key={f.id}>{f.trade_name}</option>)}</select></div><div className="field"><label>Cidade</label><select className="input" value={cityId} onChange={e=>setCityId(e.target.value)}><option value="">Selecione</option>{cities.map(c=><option value={c.id} key={c.id}>{c.name}/{c.state}</option>)}</select></div></div><div className="toolbar" style={{marginTop:14}}><button className="button" onClick={assign}>Vincular cidade</button></div></div></div>
 {msg&&<p className="empty">{msg}</p>}
 <div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Franquia</th><th>Responsável</th><th>Cidades</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="empty">Nenhuma franquia cadastrada.</td></tr>:rows.map(f=><tr key={f.id}><td><strong>{f.trade_name}</strong><br/><span className="empty">{f.legal_name}</span></td><td>{f.contact_name||'—'}<br/><span className="empty">{f.contact_email||''}</span></td><td>{cityNames(f.id)}</td><td><span className={'pill '+(f.active?'green':'red')}>{f.active?'Ativa':'Bloqueada'}</span></td><td><div className="toolbar"><button className="button secondary" onClick={()=>edit(f)}>Editar</button><button className="button secondary" onClick={()=>toggle(f)}>{f.active?'Bloquear':'Ativar'}</button><button className="button danger" onClick={()=>remove(f.id)}>Excluir</button></div></td></tr>)}</tbody></table></div></div>
 </>
}
