'use client'
import { useState } from 'react'
import { supabase } from '@/lib/supabase'

export default function LoginForm(){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg('Entrando...');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setMsg(error.message);setBusy(false);return}const role=data.user.app_metadata?.role;if(role!=='super_admin'){await supabase.auth.signOut();setMsg('Este acesso não é de Super Admin.');setBusy(false);return}window.location.href='/dashboard'}
 async function recover(){if(!email.trim()){setMsg('Digite primeiro o e-mail da conta Super Admin.');return}setBusy(true);setMsg('Enviando recuperação...');const redirectTo=`${window.location.origin}/redefinir-senha`;const{error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo});setBusy(false);setMsg(error?error.message:'E-mail de recuperação enviado. Abra sua caixa de entrada e clique no link para criar uma nova senha.')}
 return <div className="card" style={{maxWidth:460,margin:'10vh auto'}}><div className="eyebrow">CLICK-GO</div><h1 className="title">Super Admin</h1><p className="subtitle">Entre com a conta administrativa da matriz.</p><form onSubmit={login} className="module-list" style={{marginTop:22}}><div className="field"><label>E-mail</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Senha</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="button" type="submit" disabled={busy}>{busy?'Aguarde...':'Entrar'}</button><button className="button secondary" type="button" disabled={busy} onClick={recover}>Esqueci minha senha</button>{msg&&<p className="empty">{msg}</p>}</form></div>
}
