'use client'
import {useEffect,useRef,useState} from 'react'
import {supabase} from '@/lib/supabase'
import 'leaflet/dist/leaflet.css'

type P={lat:number;lng:number}
type City={id:string;name:string;state:string}
type Area={id:string;name:string;city_id:string;franchise_id:string;polygon:P[];active:boolean;locked_by_matrix:boolean}
export default function MatrixAreaManager(){
 const[cities,setCities]=useState<City[]>([]);const[links,setLinks]=useState<Record<string,string>>({});const[areas,setAreas]=useState<Area[]>([]);const[name,setName]=useState('');const[cityId,setCityId]=useState('');const[selected,setSelected]=useState('');const[points,setPoints]=useState<P[]>([]);const[msg,setMsg]=useState('')
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),layerRef=useRef<any>(null),selectedRef=useRef('')
 async function load(){const[c,fc,a]=await Promise.all([supabase.from('cities').select('id,name,state').eq('active',true).order('name'),supabase.from('franchise_cities').select('city_id,franchise_id'),supabase.from('service_areas').select('id,name,city_id,franchise_id,polygon,active,locked_by_matrix').order('created_at',{ascending:false})]);setCities(c.data||[]);const m:Record<string,string>={};(fc.data||[]).forEach((x:any)=>m[x.city_id]=x.franchise_id);setLinks(m);setAreas((a.data||[]) as Area[])}
 useEffect(()=>{load()},[]);useEffect(()=>{selectedRef.current=selected;const a=areas.find(x=>x.id===selected);setPoints(Array.isArray(a?.polygon)?a!.polygon:[])},[selected,areas])
 useEffect(()=>{let alive=true;(async()=>{if(!mapEl.current)return;const L=await import('leaflet');if(!alive)return;if(!mapRef.current){mapRef.current=L.map(mapEl.current).setView([-14.235,-51.9253],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(mapRef.current);layerRef.current=L.layerGroup().addTo(mapRef.current);mapRef.current.on('click',(e:any)=>{if(!selectedRef.current)return;setPoints(p=>[...p,{lat:e.latlng.lat,lng:e.latlng.lng}])})}layerRef.current.clearLayers();const latLngs:[number,number][]=points.map(p=>[p.lat,p.lng]);for(const p of points)L.circleMarker([p.lat,p.lng],{radius:5}).addTo(layerRef.current);if(points.length>=2)L.polyline(latLngs).addTo(layerRef.current);if(points.length>=3)L.polygon(latLngs,{fillOpacity:.15}).addTo(layerRef.current);if(points.length)mapRef.current.fitBounds(latLngs,{padding:[25,25]})})();return()=>{alive=false}},[points]);useEffect(()=>()=>{if(mapRef.current){mapRef.current.remove();mapRef.current=null}},[])
 async function create(){if(!name.trim()||!cityId){setMsg('Informe nome e cidade.');return}const fid=links[cityId];if(!fid){setMsg('Vincule primeiro esta cidade a um franqueado.');return}const{data,error}=await supabase.rpc('create_service_area',{p_area:{name:name.trim(),city_id:cityId,franchise_id:fid,polygon:[],locked_by_matrix:true}});if(error){setMsg(error.message);return}setName('');setMsg('Região criada. Agora selecione-a e desenhe no mapa.');await load();if(data)setSelected(String(data))}
 async function savePolygon(){if(!selected){setMsg('Selecione uma região.');return}if(points.length<3){setMsg('Marque pelo menos 3 pontos no mapa.');return}const{error}=await supabase.rpc('save_service_area_polygon',{p_area_id:selected,p_polygon:points});setMsg(error?error.message:'Região salva e travada pela matriz.');load()}
 async function toggle(a:Area){const{error}=await supabase.rpc('set_service_area_active',{p_area_id:a.id,p_active:!a.active});if(error)setMsg(error.message);await load()}
 async function remove(a:Area){if(!confirm(`Excluir a região ${a.name}?`))return;const{error}=await supabase.rpc('delete_service_area',{p_area_id:a.id});setMsg(error?error.message:'Região excluída.');if(!error&&selected===a.id)setSelected('');load()}
 const city=(id:string)=>{const c=cities.find(x=>x.id===id);return c?`${c.name}/${c.state}`:id}
 return <><div className="card"><h2>Criar região</h2><div className="form-grid"><div className="field"><label>Nome da região</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Centro, Aeroporto, Zona Rural"/></div><div className="field"><label>Cidade</label><select className="input" value={cityId} onChange={e=>setCityId(e.target.value)}><option value="">Selecione</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></div></div><button className="button" style={{marginTop:14}} onClick={create}>Criar região</button></div>
 <div className="card" style={{marginTop:16}}><h2>Desenhar região no mapa</h2><p className="subtitle">Selecione uma região e clique no mapa contornando a área. Use pelo menos 3 pontos.</p><div className="toolbar"><select className="input" style={{maxWidth:380}} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name} · {city(a.city_id)}</option>)}</select><button className="button secondary" onClick={()=>setPoints([])}>Limpar pontos</button><button className="button" onClick={savePolygon}>Salvar desenho</button></div><div ref={mapEl} style={{height:430,borderRadius:16,overflow:'hidden',border:'1px solid #292929',marginTop:12}}/>{msg&&<p className="empty">{msg}</p>}</div>
 <div className="section"><h2>Regiões cadastradas</h2><div className="table-wrap"><table className="table"><thead><tr><th>Região</th><th>Cidade</th><th>Pontos</th><th>Controle</th><th>Status</th><th>Ações</th></tr></thead><tbody>{areas.length?areas.map(a=><tr key={a.id}><td>{a.name}</td><td>{city(a.city_id)}</td><td>{Array.isArray(a.polygon)?a.polygon.length:0}</td><td>{a.locked_by_matrix?'Matriz':'Franqueado'}</td><td>{a.active?'Ativa':'Inativa'}</td><td><div className="toolbar"><button className="button secondary" onClick={()=>setSelected(a.id)}>Editar mapa</button><button className="button secondary" onClick={()=>toggle(a)}>{a.active?'Desativar':'Ativar'}</button><button className="button danger" onClick={()=>remove(a)}>Excluir</button></div></td></tr>):<tr><td colSpan={6} className="empty">Nenhuma região cadastrada.</td></tr>}</tbody></table></div></div></>
}
