'use client'
import {useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {supabase} from '@/lib/supabase'

type City={id:string;name:string;state:string}
type Franchise={id:string;trade_name:string}
type Profile={id:string;full_name:string|null;phone:string|null;email:string|null;role:string;city_id:string|null;franchise_id:string|null;active:boolean}
type Driver={id:string;status:string;city_id:string|null;franchise_id:string|null;commission_percent:number|null;rating:number}
type Ride={id:string;passenger_id:string;driver_id:string|null;city_id:string;franchise_id:string|null;status:string;origin_label:string;destination_label:string;estimated_fare:number|null;final_fare:number|null;requested_at:string}
type Ticket={id:string;requester_id:string|null;city_id:string|null;franchise_id:string|null;subject:string;status:string;priority:string;created_at:string}
type Tx={id:string;ride_id:string|null;payer_id:string|null;driver_id:string|null;city_id:string|null;valor_total:number;valor_motorista:number;valor_franqueado:number;valor_plataforma:number;status_pagamento:string;data_criacao:string}
type Notice={id:string;title:string;body:string|null;driver_id:string|null;city_id:string|null;read_at:string|null;created_at:string}
type Banner={id:string;title:string;image_url:string;target_url:string|null;advertiser_name:string|null;active:boolean;sort_order:number}
type Dynamic={id:string;name:string;city_id:string;category_id:string|null;service_area_id:string|null;start_time:string;end_time:string;multiplier:number;active:boolean}
type Category={id:string;name:string;city_id:string;franchise_id:string|null}
type Area={id:string;name:string;city_id:string;franchise_id:string}

const money=(v:number|null|undefined)=>`R$ ${Number(v||0).toFixed(2).replace('.',',')}`
const monthKey=(d:string)=>new Date(d).toLocaleDateString('pt-BR',{month:'short',year:'2-digit'})

export default function OperationsControlCenter(){
 const[cities,setCities]=useState<City[]>([]);const[franchises,setFranchises]=useState<Franchise[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[drivers,setDrivers]=useState<Driver[]>([]);const[rides,setRides]=useState<Ride[]>([]);const[tickets,setTickets]=useState<Ticket[]>([]);const[txs,setTxs]=useState<Tx[]>([]);const[notices,setNotices]=useState<Notice[]>([]);const[banners,setBanners]=useState<Banner[]>([]);const[dynamics,setDynamics]=useState<Dynamic[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[areas,setAreas]=useState<Area[]>([])
 const[cityFilter,setCityFilter]=useState('');const[msg,setMsg]=useState('')
 const[globalSettings,setGlobalSettings]=useState({auto_cancel_unaccepted_minutes:'10',taximeter_refresh_seconds:'10',max_pickup_radius_km:'25',taximeter_enabled:true})
 const[bannerForm,setBannerForm]=useState({title:'',image_url:'',target_url:'',advertiser_name:'',city_id:'',sort_order:'100'})
 const[dynamicForm,setDynamicForm]=useState({name:'Horário de pico',city_id:'',category_id:'',service_area_id:'',start_time:'17:00',end_time:'20:00',multiplier:'1.30'})
 const[accessForm,setAccessForm]=useState({profile_id:'',city_id:''})
 const[manual,setManual]=useState({passenger_id:'',city_id:'',category_id:'',origin_label:'',origin_lat:'',origin_lng:'',destination_label:'',destination_lat:'',destination_lng:''})

 async function load(){
  const [c,f,p,d,r,t,x,n,b,dy,cat,a,s]=await Promise.all([
   supabase.from('cities').select('id,name,state').eq('active',true).order('name'),
   supabase.from('franchises').select('id,trade_name').eq('active',true).is('deleted_at',null).order('trade_name'),
   supabase.from('profiles').select('id,full_name,phone,email,role,city_id,franchise_id,active').order('created_at',{ascending:false}),
   supabase.from('drivers').select('id,status,city_id,franchise_id,commission_percent,rating').order('created_at',{ascending:false}),
   supabase.from('rides').select('id,passenger_id,driver_id,city_id,franchise_id,status,origin_label,destination_label,estimated_fare,final_fare,requested_at').order('requested_at',{ascending:false}).limit(100),
   supabase.from('support_tickets').select('id,requester_id,city_id,franchise_id,subject,status,priority,created_at').order('created_at',{ascending:false}).limit(100),
   supabase.from('financial_transactions').select('id,ride_id,payer_id,driver_id,city_id,valor_total,valor_motorista,valor_franqueado,valor_plataforma,status_pagamento,data_criacao').order('data_criacao',{ascending:false}).limit(100),
   supabase.from('admin_notifications').select('id,title,body,driver_id,city_id,read_at,created_at').order('created_at',{ascending:false}).limit(50),
   supabase.from('advertising_banners').select('id,title,image_url,target_url,advertiser_name,active,sort_order').order('sort_order'),
   supabase.from('dynamic_pricing_rules').select('id,name,city_id,category_id,service_area_id,start_time,end_time,multiplier,active').order('created_at',{ascending:false}),
   supabase.from('ride_categories').select('id,name,city_id,franchise_id').eq('active',true).order('name'),
   supabase.from('service_areas').select('id,name,city_id,franchise_id').eq('active',true).order('name'),
   supabase.from('remote_app_settings').select('auto_cancel_unaccepted_minutes,taximeter_refresh_seconds,max_pickup_radius_km,taximeter_enabled').eq('scope','global').limit(1).maybeSingle(),
  ])
  setCities(c.data||[]);setFranchises(f.data||[]);setProfiles((p.data||[]) as Profile[]);setDrivers((d.data||[]) as Driver[]);setRides((r.data||[]) as Ride[]);setTickets((t.data||[]) as Ticket[]);setTxs((x.data||[]) as Tx[]);setNotices((n.data||[]) as Notice[]);setBanners((b.data||[]) as Banner[]);setDynamics((dy.data||[]) as Dynamic[]);setCategories((cat.data||[]) as Category[]);setAreas((a.data||[]) as Area[])
  if(s.data)setGlobalSettings({auto_cancel_unaccepted_minutes:String(s.data.auto_cancel_unaccepted_minutes),taximeter_refresh_seconds:String(s.data.taximeter_refresh_seconds),max_pickup_radius_km:String(s.data.max_pickup_radius_km),taximeter_enabled:Boolean(s.data.taximeter_enabled)})
 }
 useEffect(()=>{load();const ch=supabase.channel('super-admin-live').on('postgres_changes',{event:'*',schema:'public',table:'rides'},load).on('postgres_changes',{event:'*',schema:'public',table:'drivers'},load).on('postgres_changes',{event:'*',schema:'public',table:'support_tickets'},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'admin_notifications'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[])

 const profileById=(id:string|null)=>profiles.find(p=>p.id===id)
 const cityName=(id:string|null)=>{const c=cities.find(x=>x.id===id);return c?`${c.name}/${c.state}`:'—'}
 const visibleRides=cityFilter?rides.filter(r=>r.city_id===cityFilter):rides
 const visibleDrivers=cityFilter?drivers.filter(d=>d.city_id===cityFilter):drivers
 const passengers=profiles.filter(p=>p.role==='passenger')
 const pending=visibleDrivers.filter(d=>d.status==='pending')
 const monthly=useMemo(()=>{const map=new Map<string,number>();txs.forEach(t=>map.set(monthKey(t.data_criacao),(map.get(monthKey(t.data_criacao))||0)+Number(t.valor_total||0)));return [...map.entries()].slice(0,6).reverse()},[txs])
 const maxMonth=Math.max(1,...monthly.map(x=>x[1]))

 async function approve(id:string,ok:boolean){const percent=drivers.find(d=>d.id===id)?.commission_percent;const{error}=await supabase.rpc('approve_driver_registration',{p_driver_id:id,p_approve:ok,p_reason:ok?null:'Reprovado pelo painel',p_commission_percent:percent});setMsg(error?error.message:(ok?'Motorista aprovado.':'Motorista reprovado.'));load()}
 async function setCommission(id:string,value:string){const n=value===''?null:Number(value);const{error}=await supabase.from('drivers').update({commission_percent:n}).eq('id',id);setMsg(error?error.message:'Comissão individual atualizada.');load()}
 async function toggleUser(p:Profile){const active=!p.active;const{error}=await supabase.from('profiles').update({active}).eq('id',p.id);if(p.role==='driver')await supabase.from('drivers').update({status:active?'pending':'blocked',online:false}).eq('id',p.id);setMsg(error?error.message:(active?'Usuário ativado.':'Usuário bloqueado.'));load()}
 async function saveSettings(){const{error}=await supabase.from('remote_app_settings').update({auto_cancel_unaccepted_minutes:Number(globalSettings.auto_cancel_unaccepted_minutes),taximeter_refresh_seconds:Number(globalSettings.taximeter_refresh_seconds),max_pickup_radius_km:Number(globalSettings.max_pickup_radius_km),taximeter_enabled:globalSettings.taximeter_enabled,updated_at:new Date().toISOString()}).eq('scope','global');setMsg(error?error.message:'Configurações remotas salvas.');load()}
 async function addBanner(){const{error}=await supabase.from('advertising_banners').insert({title:bannerForm.title,image_url:bannerForm.image_url,target_url:bannerForm.target_url||null,advertiser_name:bannerForm.advertiser_name||null,city_id:bannerForm.city_id||null,sort_order:Number(bannerForm.sort_order)||100,active:true});setMsg(error?error.message:'Banner cadastrado.');if(!error)setBannerForm({title:'',image_url:'',target_url:'',advertiser_name:'',city_id:'',sort_order:'100'});load()}
 async function toggleBanner(b:Banner){await supabase.from('advertising_banners').update({active:!b.active,updated_at:new Date().toISOString()}).eq('id',b.id);load()}
 async function addDynamic(){const city=dynamicForm.city_id;if(!city){setMsg('Selecione a cidade.');return}const{error}=await supabase.from('dynamic_pricing_rules').insert({name:dynamicForm.name,city_id:city,category_id:dynamicForm.category_id||null,service_area_id:dynamicForm.service_area_id||null,start_time:dynamicForm.start_time,end_time:dynamicForm.end_time,multiplier:Number(dynamicForm.multiplier),active:true});setMsg(error?error.message:'Regra dinâmica cadastrada.');load()}
 async function toggleDynamic(d:Dynamic){await supabase.from('dynamic_pricing_rules').update({active:!d.active,updated_at:new Date().toISOString()}).eq('id',d.id);load()}
 async function grantCityAccess(){if(!accessForm.profile_id||!accessForm.city_id){setMsg('Selecione usuário e cidade.');return}const{error}=await supabase.from('profile_city_access').upsert(accessForm);setMsg(error?error.message:'Acesso à cidade liberado.');}
 async function markNotice(id:string){await supabase.from('admin_notifications').update({read_at:new Date().toISOString()}).eq('id',id);load()}
 async function sendManualRide(){const cat=categories.find(c=>c.id===manual.category_id);if(!manual.passenger_id||!manual.city_id||!cat){setMsg('Selecione passageiro, cidade e categoria.');return}const{error}=await supabase.from('rides').insert({passenger_id:manual.passenger_id,city_id:manual.city_id,franchise_id:cat.franchise_id,category_id:cat.id,status:'requested',dispatch_mode:'manual',origin_label:manual.origin_label,origin_lat:Number(manual.origin_lat),origin_lng:Number(manual.origin_lng),destination_label:manual.destination_label,destination_lat:Number(manual.destination_lat),destination_lng:Number(manual.destination_lng),estimated_distance_km:0,estimated_duration_min:0});setMsg(error?error.message:'Chamado/corrida enviado para despacho.');if(!error)setManual({...manual,origin_label:'',destination_label:''});load()}

 return <>
  <div className="topbar"><div><div className="eyebrow">Operação central</div><h1 className="title">Controle total CLICK-GO</h1><p className="subtitle">Motoristas, passageiros, chamados, ganhos, taxas, dinâmico, taxímetro remoto e publicidade.</p></div><div className="field"><label>Filtrar cidade</label><select className="input" value={cityFilter} onChange={e=>setCityFilter(e.target.value)}><option value="">Todas</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></div></div>
  {msg&&<div className="card" style={{marginBottom:16}}>{msg}</div>}

  <div className="stats"><div className="stat"><strong>{visibleRides.length}</strong><span>Chamados recentes</span></div><div className="stat"><strong>{visibleDrivers.length}</strong><span>Motoristas</span></div><div className="stat"><strong>{passengers.length}</strong><span>Clientes</span></div><div className="stat"><strong>{pending.length}</strong><span>Aguardando aprovação</span></div></div>

  <div className="section"><h2>Alertas de novos cadastros</h2><div className="card">{notices.filter(n=>!n.read_at).slice(0,8).map(n=><div className="toolbar" key={n.id} style={{justifyContent:'space-between',padding:'8px 0'}}><div><strong>{n.title}</strong><div className="empty">{n.body} • {cityName(n.city_id)}</div></div><button className="button secondary" onClick={()=>markNotice(n.id)}>Marcar lido</button></div>)}{!notices.some(n=>!n.read_at)&&<div className="empty">Nenhum alerta pendente.</div>}</div></div>

  <div className="section"><h2>Aprovação e comissão individual de motoristas</h2><div className="table-wrap"><table className="table"><thead><tr><th>Motorista</th><th>Cidade</th><th>Status</th><th>Comissão %</th><th>Contato</th><th>Ações</th></tr></thead><tbody>{visibleDrivers.map(d=>{const p=profileById(d.id);return <tr key={d.id}><td>{p?.full_name||d.id}</td><td>{cityName(d.city_id)}</td><td><span className={'pill '+(d.status==='approved'?'green':d.status==='blocked'?'red':'yellow')}>{d.status}</span></td><td><input className="input" style={{width:90}} defaultValue={d.commission_percent??''} onBlur={e=>setCommission(d.id,e.target.value)} placeholder="ex. 20"/></td><td>{p?.phone?<a href={`tel:${p.phone}`}>{p.phone}</a>:'—'}</td><td><div className="toolbar"><button className="button" onClick={()=>approve(d.id,true)}>Aprovar</button><button className="button secondary" onClick={()=>approve(d.id,false)}>Reprovar</button>{p&&<button className="button danger" onClick={()=>toggleUser(p)}>{p.active?'Bloquear':'Ativar'}</button>}</div></td></tr>})}</tbody></table></div></div>

  <div className="section"><h2>Chamados/corridas em tempo real</h2><div className="table-wrap"><table className="table"><thead><tr><th>Passageiro</th><th>Motorista</th><th>Rota</th><th>Status</th><th>Valor</th><th>Contato</th></tr></thead><tbody>{visibleRides.slice(0,30).map(r=>{const pp=profileById(r.passenger_id);const dp=profileById(r.driver_id);return <tr key={r.id}><td>{pp?.full_name||'Passageiro'}</td><td>{dp?.full_name||'Aguardando'}</td><td>{r.origin_label} → {r.destination_label}</td><td>{r.status}</td><td>{money(r.final_fare||r.estimated_fare)}</td><td>{pp?.phone&&<a href={`tel:${pp.phone}`}>Cliente</a>} {dp?.phone&&<> • <a href={`tel:${dp.phone}`}>Motorista</a></>}</td></tr>})}</tbody></table></div></div>

  <div className="section"><h2>Enviar chamado/corrida pelo painel</h2><div className="card"><div className="form-grid"><div className="field"><label>Passageiro</label><select className="input" value={manual.passenger_id} onChange={e=>setManual({...manual,passenger_id:e.target.value})}><option value="">Selecione</option>{passengers.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email}</option>)}</select></div><div className="field"><label>Cidade</label><select className="input" value={manual.city_id} onChange={e=>setManual({...manual,city_id:e.target.value,category_id:''})}><option value="">Selecione</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></div><div className="field"><label>Categoria</label><select className="input" value={manual.category_id} onChange={e=>setManual({...manual,category_id:e.target.value})}><option value="">Selecione</option>{categories.filter(c=>!manual.city_id||c.city_id===manual.city_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Origem</label><input className="input" value={manual.origin_label} onChange={e=>setManual({...manual,origin_label:e.target.value})}/></div><div className="field"><label>Latitude origem</label><input className="input" value={manual.origin_lat} onChange={e=>setManual({...manual,origin_lat:e.target.value})}/></div><div className="field"><label>Longitude origem</label><input className="input" value={manual.origin_lng} onChange={e=>setManual({...manual,origin_lng:e.target.value})}/></div><div className="field"><label>Destino</label><input className="input" value={manual.destination_label} onChange={e=>setManual({...manual,destination_label:e.target.value})}/></div><div className="field"><label>Latitude destino</label><input className="input" value={manual.destination_lat} onChange={e=>setManual({...manual,destination_lat:e.target.value})}/></div><div className="field"><label>Longitude destino</label><input className="input" value={manual.destination_lng} onChange={e=>setManual({...manual,destination_lng:e.target.value})}/></div></div><button className="button" style={{marginTop:14}} onClick={sendManualRide}>Enviar chamado</button></div></div>

  <div className="section"><h2>Ganhos mensais</h2><div className="card">{monthly.map(([m,v])=><div key={m} style={{marginBottom:12}}><div className="toolbar" style={{justifyContent:'space-between'}}><strong>{m}</strong><span>{money(v)}</span></div><div style={{height:12,background:'#202020',borderRadius:99,overflow:'hidden',marginTop:6}}><div style={{height:'100%',width:`${Math.max(4,(v/maxMonth)*100)}%`,background:'#FFD400'}}/></div></div>)}{!monthly.length&&<div className="empty">Sem transações para o gráfico.</div>}</div></div>

  <div className="section"><h2>Histórico de transações de clientes e motoristas</h2><div className="table-wrap"><table className="table"><thead><tr><th>Data</th><th>Cliente</th><th>Motorista</th><th>Total</th><th>Motorista</th><th>Franqueado</th><th>Matriz</th><th>Status</th></tr></thead><tbody>{txs.slice(0,30).map(t=><tr key={t.id}><td>{new Date(t.data_criacao).toLocaleString('pt-BR')}</td><td>{profileById(t.payer_id)?.full_name||'—'}</td><td>{profileById(t.driver_id)?.full_name||'—'}</td><td>{money(t.valor_total)}</td><td>{money(t.valor_motorista)}</td><td>{money(t.valor_franqueado)}</td><td>{money(t.valor_plataforma)}</td><td>{t.status_pagamento}</td></tr>)}</tbody></table></div></div>

  <div className="section"><h2>Configuração remota do taxímetro e cancelamento automático</h2><div className="card"><div className="form-grid"><div className="field"><label>Cancelar sem aceite após (min)</label><input className="input" type="number" value={globalSettings.auto_cancel_unaccepted_minutes} onChange={e=>setGlobalSettings({...globalSettings,auto_cancel_unaccepted_minutes:e.target.value})}/></div><div className="field"><label>Atualização do taxímetro (seg)</label><input className="input" type="number" value={globalSettings.taximeter_refresh_seconds} onChange={e=>setGlobalSettings({...globalSettings,taximeter_refresh_seconds:e.target.value})}/></div><div className="field"><label>Raio máximo de busca (km)</label><input className="input" type="number" value={globalSettings.max_pickup_radius_km} onChange={e=>setGlobalSettings({...globalSettings,max_pickup_radius_km:e.target.value})}/></div><div className="field"><label>Taxímetro remoto</label><select className="input" value={globalSettings.taximeter_enabled?'on':'off'} onChange={e=>setGlobalSettings({...globalSettings,taximeter_enabled:e.target.value==='on'})}><option value="on">Ativado</option><option value="off">Desativado</option></select></div></div><button className="button" style={{marginTop:14}} onClick={saveSettings}>Salvar configurações</button></div></div>

  <div className="section"><h2>Dinâmico por horário e região</h2><div className="card"><div className="form-grid"><div className="field"><label>Nome</label><input className="input" value={dynamicForm.name} onChange={e=>setDynamicForm({...dynamicForm,name:e.target.value})}/></div><div className="field"><label>Cidade</label><select className="input" value={dynamicForm.city_id} onChange={e=>setDynamicForm({...dynamicForm,city_id:e.target.value,category_id:'',service_area_id:''})}><option value="">Selecione</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></div><div className="field"><label>Categoria (opcional)</label><select className="input" value={dynamicForm.category_id} onChange={e=>setDynamicForm({...dynamicForm,category_id:e.target.value})}><option value="">Todas</option>{categories.filter(c=>!dynamicForm.city_id||c.city_id===dynamicForm.city_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Região (opcional)</label><select className="input" value={dynamicForm.service_area_id} onChange={e=>setDynamicForm({...dynamicForm,service_area_id:e.target.value})}><option value="">Toda cidade</option>{areas.filter(a=>!dynamicForm.city_id||a.city_id===dynamicForm.city_id).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="field"><label>Início</label><input className="input" type="time" value={dynamicForm.start_time} onChange={e=>setDynamicForm({...dynamicForm,start_time:e.target.value})}/></div><div className="field"><label>Fim</label><input className="input" type="time" value={dynamicForm.end_time} onChange={e=>setDynamicForm({...dynamicForm,end_time:e.target.value})}/></div><div className="field"><label>Multiplicador</label><input className="input" type="number" step="0.05" min="1" value={dynamicForm.multiplier} onChange={e=>setDynamicForm({...dynamicForm,multiplier:e.target.value})}/></div></div><button className="button" style={{marginTop:14}} onClick={addDynamic}>Cadastrar dinâmico</button></div><div className="table-wrap" style={{marginTop:12}}><table className="table"><thead><tr><th>Regra</th><th>Cidade</th><th>Horário</th><th>Multiplicador</th><th>Status</th><th>Ação</th></tr></thead><tbody>{dynamics.map(d=><tr key={d.id}><td>{d.name}</td><td>{cityName(d.city_id)}</td><td>{d.start_time}–{d.end_time}</td><td>{d.multiplier}x</td><td>{d.active?'Ativo':'Inativo'}</td><td><button className="button secondary" onClick={()=>toggleDynamic(d)}>{d.active?'Desativar':'Ativar'}</button></td></tr>)}</tbody></table></div></div>

  <div className="section"><h2>Banners com link para anunciantes</h2><div className="card"><div className="form-grid"><div className="field"><label>Título</label><input className="input" value={bannerForm.title} onChange={e=>setBannerForm({...bannerForm,title:e.target.value})}/></div><div className="field"><label>Anunciante</label><input className="input" value={bannerForm.advertiser_name} onChange={e=>setBannerForm({...bannerForm,advertiser_name:e.target.value})}/></div><div className="field"><label>URL da imagem</label><input className="input" value={bannerForm.image_url} onChange={e=>setBannerForm({...bannerForm,image_url:e.target.value})}/></div><div className="field"><label>Link do anúncio</label><input className="input" value={bannerForm.target_url} onChange={e=>setBannerForm({...bannerForm,target_url:e.target.value})}/></div><div className="field"><label>Cidade (opcional)</label><select className="input" value={bannerForm.city_id} onChange={e=>setBannerForm({...bannerForm,city_id:e.target.value})}><option value="">Todas</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></div><div className="field"><label>Ordem</label><input className="input" type="number" value={bannerForm.sort_order} onChange={e=>setBannerForm({...bannerForm,sort_order:e.target.value})}/></div></div><button className="button" style={{marginTop:14}} onClick={addBanner}>Cadastrar banner</button></div><div className="table-wrap" style={{marginTop:12}}><table className="table"><thead><tr><th>Banner</th><th>Anunciante</th><th>Link</th><th>Status</th><th>Ação</th></tr></thead><tbody>{banners.map(b=><tr key={b.id}><td>{b.title}</td><td>{b.advertiser_name||'—'}</td><td>{b.target_url?<a href={b.target_url} target="_blank">Abrir</a>:'—'}</td><td>{b.active?'Ativo':'Inativo'}</td><td><button className="button secondary" onClick={()=>toggleBanner(b)}>{b.active?'Desativar':'Ativar'}</button></td></tr>)}</tbody></table></div></div>

  <div className="section"><h2>Acesso de usuário por cidade</h2><div className="card"><div className="form-grid"><div className="field"><label>Usuário administrativo</label><select className="input" value={accessForm.profile_id} onChange={e=>setAccessForm({...accessForm,profile_id:e.target.value})}><option value="">Selecione</option>{profiles.filter(p=>['operator','franchise_admin'].includes(p.role)).map(p=><option key={p.id} value={p.id}>{p.full_name||p.email} ({p.role})</option>)}</select></div><div className="field"><label>Cidade</label><select className="input" value={accessForm.city_id} onChange={e=>setAccessForm({...accessForm,city_id:e.target.value})}><option value="">Selecione</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></div></div><button className="button" style={{marginTop:14}} onClick={grantCityAccess}>Liberar acesso</button></div></div>

  <div className="section"><h2>Atalhos de gestão</h2><div className="toolbar"><Link className="button secondary" href="/tarifas">Taxas e categorias</Link><Link className="button secondary" href="/passageiros">Lista de clientes</Link><Link className="button secondary" href="/motoristas">Cadastro ilimitado de motoristas</Link><Link className="button secondary" href="/suporte">Atendimento e relatórios</Link><Link className="button secondary" href="/financeiro">Financeiro completo</Link></div></div>
 </>
}
