'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

export default function OperationsManager({kind}:{kind:'drivers'|'rides'}){
 const [rows,setRows]=useState<any[]>([]);const [msg,setMsg]=useState('')
 async function load(){const q=kind==='drivers'?supabase.from('drivers').select('id,status,city_id,franchise_id,online,rating,created_at').order('created_at',{ascending:false}).limit(200):supabase.from('rides').select('id,passenger_id,driver_id,franchise_id,city_id,status,estimated_fare,final_fare,requested_at').order('requested_at',{ascending:false}).limit(200);const {data,error}=await q;if(error)setMsg(error.message);else{setRows(data||[]);setMsg('')}}
 useEffect(()=>{load();const table=kind==='drivers'?'drivers':'rides';const ch=supabase.channel(`admin-${table}`).on('postgres_changes',{event:'*',schema:'public',table},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[kind])
 async function driverStatus(id:string,status:string){await supabase.from('drivers').update({status}).eq('id',id);load()}
 const brl=(v:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0))
 if(kind==='drivers')return <><p className="empty">{msg}</p><div className="table-wrap"><table className="table"><thead><tr><th>Motorista</th><th>Cidade</th><th>Franquia</th><th>Status</th><th>Online</th><th>Avaliação</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={7} className="empty">Nenhum motorista cadastrado.</td></tr>:rows.map(r=><tr key={r.id}><td>{r.id.slice(0,8)}…</td><td>{r.city_id||'—'}</td><td>{r.franchise_id||'—'}</td><td>{r.status}</td><td><span className={'pill '+(r.online?'green':'')}>{r.online?'Online':'Offline'}</span></td><td>{r.rating}</td><td><select className="input" value={r.status} onChange={e=>driverStatus(r.id,e.target.value)}><option value="pending">Pendente</option><option value="approved">Aprovado</option><option value="rejected">Rejeitado</option><option value="blocked">Bloqueado</option></select></td></tr>)}</tbody></table></div></>
 return <><p className="empty">{msg}</p><div className="table-wrap"><table className="table"><thead><tr><th>Corrida</th><th>Cidade</th><th>Franquia</th><th>Passageiro</th><th>Motorista</th><th>Status</th><th>Valor</th><th>Solicitada</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={8} className="empty">Nenhuma corrida registrada.</td></tr>:rows.map(r=><tr key={r.id}><td>{r.id.slice(0,8)}…</td><td>{r.city_id||'—'}</td><td>{r.franchise_id||'—'}</td><td>{r.passenger_id.slice(0,8)}…</td><td>{r.driver_id?r.driver_id.slice(0,8)+'…':'—'}</td><td>{r.status}</td><td>{brl(r.final_fare??r.estimated_fare)}</td><td>{new Date(r.requested_at).toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div></>
}
