'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Plan={id:string;name:string;monthly_fee:number;billing_model:string;percentage_rate:number;fixed_fee_per_ride:number;included_rides:number;overage_fee_per_ride:number;active:boolean}
export default function PlanManager(){
 const [rows,setRows]=useState<Plan[]>([]);const [msg,setMsg]=useState('');const [form,setForm]=useState({name:'',monthly_fee:'0',billing_model:'fixed_per_ride',percentage_rate:'0',fixed_fee_per_ride:'0',included_rides:'0',overage_fee_per_ride:'0'})
 async function load(){const {data,error}=await supabase.from('franchise_plans').select('*').order('created_at',{ascending:false});if(error)setMsg(error.message);else setRows((data||[]) as Plan[])}
 useEffect(()=>{load()},[])
 async function add(e:React.FormEvent){e.preventDefault();const payload={name:form.name,monthly_fee:Number(form.monthly_fee),billing_model:form.billing_model,percentage_rate:Number(form.percentage_rate),fixed_fee_per_ride:Number(form.fixed_fee_per_ride),included_rides:Number(form.included_rides),overage_fee_per_ride:Number(form.overage_fee_per_ride),active:true};const {error}=await supabase.from('franchise_plans').insert(payload);if(error){setMsg(error.message);return}setMsg('Plano criado.');setForm({name:'',monthly_fee:'0',billing_model:'fixed_per_ride',percentage_rate:'0',fixed_fee_per_ride:'0',included_rides:'0',overage_fee_per_ride:'0'});load()}
 async function toggle(p:Plan){await supabase.from('franchise_plans').update({active:!p.active,updated_at:new Date().toISOString()}).eq('id',p.id);load()}
 async function remove(id:string){if(!confirm('Excluir este plano?'))return;const {error}=await supabase.from('franchise_plans').delete().eq('id',id);if(error)setMsg(error.message);load()}
 const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)
 return <>
 <div className="card"><form onSubmit={add}><div className="form-grid"><div className="field"><label>Nome do plano</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div className="field"><label>Mensalidade</label><input className="input" type="number" step="0.01" value={form.monthly_fee} onChange={e=>setForm({...form,monthly_fee:e.target.value})}/></div><div className="field"><label>Modelo de cobrança</label><select className="input" value={form.billing_model} onChange={e=>setForm({...form,billing_model:e.target.value})}><option value="fixed_per_ride">Valor fixo por corrida</option><option value="percentage">Percentual por corrida</option><option value="hybrid">Híbrido</option><option value="unlimited">Livre</option></select></div><div className="field"><label>Percentual por corrida (%)</label><input className="input" type="number" step="0.01" value={form.percentage_rate} onChange={e=>setForm({...form,percentage_rate:e.target.value})}/></div><div className="field"><label>Valor fixo por corrida</label><input className="input" type="number" step="0.01" value={form.fixed_fee_per_ride} onChange={e=>setForm({...form,fixed_fee_per_ride:e.target.value})}/></div><div className="field"><label>Corridas incluídas</label><input className="input" type="number" value={form.included_rides} onChange={e=>setForm({...form,included_rides:e.target.value})}/></div><div className="field"><label>Excedente por corrida</label><input className="input" type="number" step="0.01" value={form.overage_fee_per_ride} onChange={e=>setForm({...form,overage_fee_per_ride:e.target.value})}/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button">Salvar plano</button></div>{msg&&<p className="empty">{msg}</p>}</form></div>
 <div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Plano</th><th>Mensalidade</th><th>Modelo</th><th>%</th><th>Fixo/corrida</th><th>Limite</th><th>Excedente</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={9} className="empty">Nenhum plano cadastrado.</td></tr>:rows.map(p=><tr key={p.id}><td>{p.name}</td><td>{brl(p.monthly_fee)}</td><td>{p.billing_model}</td><td>{p.percentage_rate}%</td><td>{brl(p.fixed_fee_per_ride)}</td><td>{p.included_rides}</td><td>{brl(p.overage_fee_per_ride)}</td><td><span className={'pill '+(p.active?'green':'red')}>{p.active?'Ativo':'Inativo'}</span></td><td><div className="toolbar"><button className="button secondary" onClick={()=>toggle(p)}>{p.active?'Desativar':'Ativar'}</button><button className="button danger" onClick={()=>remove(p.id)}>Excluir</button></div></td></tr>)}</tbody></table></div></div>
 </>
}
