'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Promotion={id:string;title:string;promotion_type:string;value:number;active:boolean;starts_at:string|null;ends_at:string|null}
export default function PromotionManager(){
 const [rows,setRows]=useState<Promotion[]>([]);const [msg,setMsg]=useState('');const [form,setForm]=useState({title:'',description:'',promotion_type:'discount',value:'0',starts_at:'',ends_at:''})
 async function load(){const {data,error}=await supabase.from('promotions').select('id,title,promotion_type,value,active,starts_at,ends_at').order('created_at',{ascending:false});if(error)setMsg(error.message);else setRows((data||[]) as Promotion[])}
 useEffect(()=>{load()},[])
 async function add(e:React.FormEvent){e.preventDefault();const {error}=await supabase.from('promotions').insert({title:form.title,description:form.description,promotion_type:form.promotion_type,value:Number(form.value),starts_at:form.starts_at||null,ends_at:form.ends_at||null,active:true});if(error){setMsg(error.message);return}setForm({title:'',description:'',promotion_type:'discount',value:'0',starts_at:'',ends_at:''});setMsg('Promoção criada.');load()}
 async function toggle(p:Promotion){await supabase.from('promotions').update({active:!p.active}).eq('id',p.id);load()}
 return <><div className="card"><form onSubmit={add}><div className="form-grid"><div className="field"><label>Título</label><input className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></div><div className="field"><label>Tipo</label><select className="input" value={form.promotion_type} onChange={e=>setForm({...form,promotion_type:e.target.value})}><option value="discount">Desconto</option><option value="cashback">Cashback</option><option value="bonus">Bônus</option><option value="campaign">Campanha</option></select></div><div className="field"><label>Valor</label><input className="input" type="number" step="0.01" value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></div><div className="field"><label>Início</label><input className="input" type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></div><div className="field"><label>Fim</label><input className="input" type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></div><div className="field"><label>Descrição</label><input className="input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button">Salvar promoção</button></div>{msg&&<p className="empty">{msg}</p>}</form></div><div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Promoção</th><th>Tipo</th><th>Valor</th><th>Período</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={6} className="empty">Nenhuma promoção cadastrada.</td></tr>:rows.map(p=><tr key={p.id}><td>{p.title}</td><td>{p.promotion_type}</td><td>{p.value}</td><td>{p.starts_at?new Date(p.starts_at).toLocaleDateString('pt-BR'):'—'} → {p.ends_at?new Date(p.ends_at).toLocaleDateString('pt-BR'):'—'}</td><td><span className={'pill '+(p.active?'green':'red')}>{p.active?'Ativa':'Pausada'}</span></td><td><button className="button secondary" onClick={()=>toggle(p)}>{p.active?'Pausar':'Ativar'}</button></td></tr>)}</tbody></table></div></div></>
}
