'use client'

import { useEffect,useRef,useState } from 'react'
import { supabase } from '@/lib/supabase'
import 'leaflet/dist/leaflet.css'

type Snap={ok:boolean;reason?:string;status?:string;origin?:{label:string;lat:number;lng:number};destination?:{label:string;lat:number;lng:number};category?:{name:string|null;marker_url:string|null};passenger_location?:{lat:number;lng:number;accuracy_m:number;updated_at:string}|null;driver_location?:{lat:number;lng:number;heading:number|null;speed_kmh:number|null;updated_at:string}|null;accepted?:boolean;expires_at?:string}
function label(s:string|undefined){return s==='requested'||s==='searching'?'Procurando motorista':s==='accepted'?'Motorista a caminho':s==='driver_arriving'?'Motorista chegando':s==='in_progress'?'Corrida em andamento':s==='completed'?'Corrida concluída':s==='cancelled'?'Corrida cancelada':s||''}

export default function PublicRideShareTracker({token}:{token:string}){
 const[snap,setSnap]=useState<Snap|null>(null),[route,setRoute]=useState<[number,number][]>([]),[provider,setProvider]=useState(''),[error,setError]=useState('')
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),layerRef=useRef<any>(null)
 useEffect(()=>{let alive=true;async function load(){const{data,error}=await supabase.rpc('get_public_ride_share',{p_token:token});if(!alive)return;if(error){setError('Este compartilhamento não está disponível.');return}const s=(data||{}) as Snap;setSnap(s);if(!s.ok)setError('Link inválido, encerrado ou expirado.')}void load();const t=window.setInterval(load,4000);return()=>{alive=false;window.clearInterval(t)}},[token])
 useEffect(()=>{if(!snap?.ok||!snap.origin||!snap.destination)return;const c=new AbortController();(async()=>{try{const q=new URLSearchParams({origin_lat:String(snap.origin!.lat),origin_lng:String(snap.origin!.lng),destination_lat:String(snap.destination!.lat),destination_lng:String(snap.destination!.lng)});const r=await fetch(`/api/route?${q}`,{signal:c.signal});const b=await r.json();if(r.ok&&Array.isArray(b.coordinates)){setRoute(b.coordinates);setProvider(b.provider||'')}}catch{}})();return()=>c.abort()},[snap?.origin?.lat,snap?.origin?.lng,snap?.destination?.lat,snap?.destination?.lng])
 useEffect(()=>{let alive=true;(async()=>{if(!mapEl.current||!snap?.ok||!snap.origin||!snap.destination)return;const L=await import('leaflet');if(!alive)return;if(!mapRef.current){mapRef.current=L.map(mapEl.current,{zoomControl:false}).setView([snap.origin.lat,snap.origin.lng],14);const mb=process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN;if(mb)L.tileLayer(`https://api.mapbox.com/styles/v1/mapbox/streets-v12/tiles/256/{z}/{x}/{y}@2x?access_token=${mb}`,{attribution:'© Mapbox © OpenStreetMap',maxZoom:19}).addTo(mapRef.current);else L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(mapRef.current);layerRef.current=L.layerGroup().addTo(mapRef.current)}layerRef.current.clearLayers();const pts:[number,number][]=[];L.circleMarker([snap.origin.lat,snap.origin.lng],{radius:7,color:'#111',fillColor:'#19c7a3',fillOpacity:1}).bindTooltip('Embarque').addTo(layerRef.current);L.circleMarker([snap.destination.lat,snap.destination.lng],{radius:7,color:'#111',fillColor:'#ff8a3d',fillOpacity:1}).bindTooltip('Destino').addTo(layerRef.current);if(route.length>1)L.polyline(route,{weight:6,opacity:.7}).addTo(layerRef.current);if(snap.passenger_location){L.marker([snap.passenger_location.lat,snap.passenger_location.lng],{icon:L.divIcon({html:'<div style="width:38px;height:38px;border-radius:50%;background:#ffd400;border:3px solid #111;display:grid;place-items:center;font-size:20px">📍</div>',className:'',iconSize:[38,38],iconAnchor:[19,19]})}).bindTooltip('Passageiro').addTo(layerRef.current);pts.push([snap.passenger_location.lat,snap.passenger_location.lng])}if(snap.driver_location){const u=snap.category?.marker_url;const icon=u?L.icon({iconUrl:u,iconSize:[42,42],iconAnchor:[21,21]}):L.divIcon({html:'<div style="width:42px;height:42px;border-radius:50%;background:#111;border:3px solid #ffd400;display:grid;place-items:center;font-size:22px">🚗</div>',className:'',iconSize:[42,42],iconAnchor:[21,21]});L.marker([snap.driver_location.lat,snap.driver_location.lng],{icon}).bindTooltip('Motorista').addTo(layerRef.current);pts.push([snap.driver_location.lat,snap.driver_location.lng])}pts.push([snap.origin.lat,snap.origin.lng],[snap.destination.lat,snap.destination.lng]);mapRef.current.fitBounds(pts,{padding:[35,35]})})();return()=>{alive=false}},[snap,route])
 useEffect(()=>()=>{if(mapRef.current){mapRef.current.remove();mapRef.current=null}},[])
 if(error)return <main style={{minHeight:'100vh',background:'#090909',color:'#fff',display:'grid',placeItems:'center',padding:24}}><div style={{maxWidth:520,textAlign:'center'}}><div style={{color:'#ffd400',fontWeight:950}}>CLICK-GO</div><h1>Acompanhamento encerrado</h1><p style={{color:'#aaa'}}>{error}</p></div></main>
 if(!snap)return <main style={{minHeight:'100vh',background:'#090909',color:'#fff',display:'grid',placeItems:'center'}}>Carregando acompanhamento...</main>
 return <main style={{minHeight:'100vh',background:'#090909',color:'#fff',padding:16}}><div style={{maxWidth:780,margin:'0 auto',display:'grid',gap:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><div style={{color:'#ffd400',fontWeight:950}}>CLICK-GO · acompanhamento seguro</div><h1 style={{margin:'4px 0'}}>{label(snap.status)}</h1></div><div style={{fontSize:12,color:'#aaa'}}>Somente leitura</div></div><div ref={mapEl} style={{height:'min(62vh,520px)',borderRadius:22,overflow:'hidden',border:'1px solid #292929'}}/><div style={{background:'#151515',border:'1px solid #292929',borderRadius:18,padding:16}}><div><b>Origem:</b> {snap.origin?.label}</div><div style={{marginTop:6}}><b>Destino:</b> {snap.destination?.label}</div><div style={{marginTop:10,fontSize:12,color:'#999'}}>Atualização automática a cada 4 segundos · rota {provider==='mapbox'?'Mapbox':provider==='google'?'Google Maps':'modo de continuidade'} · este link não permite acessar conta, carteira ou alterar a corrida.</div></div></div></main>
}
