'use client'
import { useEffect,useRef,useState } from 'react'
import { supabase } from '@/lib/supabase'
import { getMyFranchise } from '@/lib/myFranchise'
import 'leaflet/dist/leaflet.css'

type Loc={driver_id:string;lat:number;lng:number;heading:number|null;speed_kmh:number|null;updated_at:string;name?:string;status?:string;online?:boolean}
export default function RealtimeMapData(){
 const [rows,setRows]=useState<Loc[]>([]);const [msg,setMsg]=useState('Conectando ao Realtime...');const [filter,setFilter]=useState<'all'|'online'|'offline'>('all');const mapEl=useRef<HTMLDivElement|null>(null);const mapRef=useRef<any>(null);const layerRef=useRef<any>(null)
 async function load(){try{const me=await getMyFranchise();const d=await supabase.from('drivers').select('id,status,online,profiles(full_name)').eq('franchise_id',me.franchiseId);if(d.error)throw d.error;const driverMap=new Map((d.data||[]).map((x:any)=>[x.id,x]));const ids=(d.data||[]).map((x:any)=>x.id);if(!ids.length){setRows([]);setMsg('');return}const {data,error}=await supabase.from('driver_locations').select('driver_id,lat,lng,heading,speed_kmh,updated_at').in('driver_id',ids).order('updated_at',{ascending:false});if(error)throw error;setRows((data||[]).map((r:any)=>{const driver:any=driverMap.get(r.driver_id);return {...r,name:driver?.profiles?.full_name||`Motorista ${r.driver_id.slice(0,8)}`,status:driver?.status,online:!!driver?.online}}));setMsg('')}catch(e:any){setMsg(e.message||'Erro ao carregar mapa')}}
 useEffect(()=>{load();const ch=supabase.channel('driver-locations-franchise').on('postgres_changes',{event:'*',schema:'public',table:'driver_locations'},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[])
 const visible=rows.filter(r=>filter==='all'||(filter==='online'?r.online:!r.online))
 useEffect(()=>{let alive=true;(async()=>{if(!mapEl.current)return;const L=await import('leaflet');if(!alive)return;if(!mapRef.current){mapRef.current=L.map(mapEl.current,{zoomControl:true}).setView([-14.235,-51.9253],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(mapRef.current);layerRef.current=L.layerGroup().addTo(mapRef.current)}layerRef.current.clearLayers();const points:any[]=[];visible.forEach(r=>{const marker=L.circleMarker([r.lat,r.lng],{radius:9,weight:2,fillOpacity:.85});marker.bindPopup(`<strong>${r.name}</strong><br/>Status: ${r.online?'Online':'Offline'}<br/>Conta: ${r.status||'—'}<br/>Velocidade: ${r.speed_kmh??0} km/h<br/>Atualizado: ${new Date(r.updated_at).toLocaleString('pt-BR')}`);marker.addTo(layerRef.current);points.push([r.lat,r.lng])});if(points.length===1)mapRef.current.setView(points[0],15);if(points.length>1)mapRef.current.fitBounds(points,{padding:[30,30]})})();return()=>{alive=false}},[visible])
 useEffect(()=>()=>{if(mapRef.current){mapRef.current.remove();mapRef.current=null}},[])
 const online=rows.filter(r=>r.online).length
 return <><div className="grid-3"><div className="card"><div className="label">Motoristas no mapa</div><div className="metric kpi-good">{rows.length}</div></div><div className="card"><div className="label">Online agora</div><div className="metric kpi-good">{online}</div></div><div className="card"><div className="label">Realtime</div><div className="metric" style={{fontSize:18}}>{msg||'Ativo'}</div></div></div><div className="toolbar" style={{marginTop:16}}><button className={`button ${filter==='all'?'':'secondary'}`} onClick={()=>setFilter('all')}>Todos</button><button className={`button ${filter==='online'?'':'secondary'}`} onClick={()=>setFilter('online')}>Online</button><button className={`button ${filter==='offline'?'':'secondary'}`} onClick={()=>setFilter('offline')}>Offline</button></div><div className="section"><div ref={mapEl} style={{height:480,borderRadius:16,overflow:'hidden',border:'1px solid #292929'}}/></div><div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Motorista</th><th>Status</th><th>Velocidade</th><th>Latitude</th><th>Longitude</th><th>Atualizado</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan={6} className="empty">Nenhuma localização recebida.</td></tr>:visible.map(r=><tr key={r.driver_id}><td>{r.name}</td><td>{r.online?'Online':'Offline'} / {r.status||'—'}</td><td>{r.speed_kmh??0} km/h</td><td>{r.lat.toFixed(6)}</td><td>{r.lng.toFixed(6)}</td><td>{new Date(r.updated_at).toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div></div></>
}
