'use client'

import {useEffect,useRef,useState} from 'react'
import type {CircleMarker,Map as LeafletMap} from 'leaflet'
import {supabase} from '@/lib/supabase'
import {cityDriverLocationsTopic,parseDriverLocationBroadcast,type DriverLocationBroadcast} from '@/lib/realtime-gps'
import 'leaflet/dist/leaflet.css'

type Loc=DriverLocationBroadcast
type City={id:string;name:string;state:string;center_lat:number|null;center_lng:number|null}
type ProfileScope={role:string;franchise_id:string|null}
type CityAccess={city_id:string}
type FranchiseCity={city_id:string;cities:City[]}
type DriverIdRow={id:string}
type SupportSession={franchise_id:string;franchise_name:string}|null

export default function RealtimeMapData({compact=false}:{compact?:boolean}){
 const[rows,setRows]=useState<Loc[]>([]),[cities,setCities]=useState<City[]>([]),[selectedCity,setSelectedCity]=useState(''),[msg,setMsg]=useState('Conectando ao mapa...'),[mapReady,setMapReady]=useState(false),[supportName,setSupportName]=useState('')
 const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<LeafletMap|null>(null),leafletRef=useRef<typeof import('leaflet')|null>(null),markersRef=useRef<Map<string,CircleMarker>>(new Map()),locationsRef=useRef<Map<string,Loc>>(new Map())
 const syncRows=()=>setRows(Array.from(locationsRef.current.values()).sort((a,b)=>Date.parse(b.updated_at)-Date.parse(a.updated_at)))
 function clearLocations(){markersRef.current.forEach(m=>m.remove());markersRef.current.clear();locationsRef.current.clear();setRows([])}
 function renderLocation(location:Loc){const L=leafletRef.current,map=mapRef.current;if(!L||!map)return;const current=markersRef.current.get(location.driver_id);const popup=`<strong>Motorista ${location.driver_id.slice(0,8)}</strong><br/>Velocidade: ${Math.round(location.speed_kmh??0)} km/h<br/>Atualizado: ${new Date(location.updated_at).toLocaleString('pt-BR')}`;if(current){current.setLatLng([location.lat,location.lng]).setPopupContent(popup);return}const marker=L.circleMarker([location.lat,location.lng],{radius:8,weight:2,color:'#111827',fillColor:'#22c55e',fillOpacity:.9});marker.bindPopup(popup).addTo(map);markersRef.current.set(location.driver_id,marker)}
 function applyLocation(location:Loc){locationsRef.current.set(location.driver_id,location);renderLocation(location);syncRows()}
 async function loadScope(){const{data:{user}}=await supabase.auth.getUser();if(!user){setMsg('Faça login para acompanhar a operação.');return}const{data:profile,error}=await supabase.from('profiles').select('role,franchise_id').eq('id',user.id).single();if(error){setMsg(error.message);return}const scope=profile as ProfileScope;let allowed:City[]=[]
  if(scope.role==='super_admin'){const supportRes=await supabase.rpc('matrix_active_support_session');const support=(supportRes.data||null) as SupportSession;setSupportName(String(support?.franchise_name||''));if(support?.franchise_id){const r=await supabase.from('franchise_cities').select('city_id,cities(id,name,state,center_lat,center_lng)').eq('franchise_id',support.franchise_id);if(r.error){setMsg(r.error.message);return}allowed=((r.data||[]) as unknown as FranchiseCity[]).map(x=>x.cities?.[0]).filter((x):x is City=>Boolean(x)).sort((a,b)=>a.name.localeCompare(b.name))}else{const r=await supabase.from('cities').select('id,name,state,center_lat,center_lng').eq('active',true).order('name');if(r.error){setMsg(r.error.message);return}allowed=(r.data||[]) as City[]}}
  else if(scope.franchise_id){setSupportName('');const r=await supabase.from('franchise_cities').select('city_id,cities(id,name,state,center_lat,center_lng)').eq('franchise_id',scope.franchise_id);if(r.error){setMsg(r.error.message);return}allowed=((r.data||[]) as unknown as FranchiseCity[]).map(x=>x.cities?.[0]).filter((x):x is City=>Boolean(x)).sort((a,b)=>a.name.localeCompare(b.name))}
  else{setSupportName('');const a=await supabase.from('profile_city_access').select('city_id').eq('profile_id',user.id);if(a.error){setMsg(a.error.message);return}const ids=((a.data||[]) as CityAccess[]).map(x=>x.city_id);if(ids.length){const r=await supabase.from('cities').select('id,name,state,center_lat,center_lng').in('id',ids).order('name');if(r.error){setMsg(r.error.message);return}allowed=(r.data||[]) as City[]}}
  clearLocations();setCities(allowed);setSelectedCity(current=>allowed.some(c=>c.id===current)?current:(allowed[0]?.id||''));if(!allowed[0])setMsg('Nenhuma cidade autorizada para este acesso.')}
 async function loadSnapshot(cityId:string){setMsg('Atualizando posições...');clearLocations();const selected=cities.find(c=>c.id===cityId);const d=await supabase.from('drivers').select('id').eq('city_id',cityId).eq('online',true);if(d.error){setMsg(d.error.message);return}const ids=((d.data||[]) as DriverIdRow[]).map(x=>x.id);if(!ids.length){if(selected&&mapRef.current&&Number.isFinite(Number(selected.center_lat))&&Number.isFinite(Number(selected.center_lng)))mapRef.current.setView([Number(selected.center_lat),Number(selected.center_lng)],13);setMsg('Mapa ao vivo · nenhum motorista online nesta cidade.');return}const l=await supabase.from('driver_locations').select('driver_id,lat,lng,heading,speed_kmh,updated_at').in('driver_id',ids).order('updated_at',{ascending:false});if(l.error){setMsg(l.error.message);return}for(const location of(l.data||[]) as Loc[]){locationsRef.current.set(location.driver_id,location);renderLocation(location)}syncRows();const map=mapRef.current,L=leafletRef.current;if(map&&L&&locationsRef.current.size){const bounds=L.latLngBounds(Array.from(locationsRef.current.values()).map(x=>[x.lat,x.lng] as[number,number]));map.fitBounds(bounds,{padding:[30,30],maxZoom:16})}setMsg('Mapa ao vivo atualizado.')}
 useEffect(()=>{void loadScope();const onSupport=()=>void loadScope();window.addEventListener('clickgo-support-session-changed',onSupport);return()=>window.removeEventListener('clickgo-support-session-changed',onSupport)},[])
 useEffect(()=>{let alive=true;(async()=>{if(!mapEl.current)return;const L=await import('leaflet');if(!alive||!mapEl.current)return;leafletRef.current=L;mapRef.current=L.map(mapEl.current,{zoomControl:true,attributionControl:true}).setView([-14.52472,-49.14083],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(mapRef.current);setMapReady(true)})();return()=>{alive=false;mapRef.current?.remove();mapRef.current=null;leafletRef.current=null;markersRef.current.clear()}},[])
 useEffect(()=>{if(!mapReady||!selectedCity)return;let cancelled=false;let channel:ReturnType<typeof supabase.channel>|null=null;(async()=>{await loadSnapshot(selectedCity);if(cancelled)return;await supabase.realtime.setAuth();channel=supabase.channel(cityDriverLocationsTopic(selectedCity),{config:{private:true}}).on('broadcast',{event:'location'},event=>{const location=parseDriverLocationBroadcast(event.payload);if(location)applyLocation(location)}).subscribe(status=>{if(status==='SUBSCRIBED')setMsg('Mapa ao vivo conectado.');else if(status==='CHANNEL_ERROR')setMsg('Falha temporária no mapa ao vivo.')})})();return()=>{cancelled=true;if(channel)void supabase.removeChannel(channel);clearLocations()}},[mapReady,selectedCity,cities])
 const selected=cities.find(c=>c.id===selectedCity)
 return <div className={compact?'live-map-card compact':'live-map-card'}>
  {supportName&&<div className="regional-alert"><strong>Matriz (Suporte) · {supportName}</strong><br/>O mapa está limitado ao território da franquia atendida.</div>}
  <div className="live-map-head"><div><div className="eyebrow">Mapa operacional</div><h2>Motoristas em tempo real</h2><p className="subtitle">Acompanhe a operação sem sair do dashboard.</p></div><label><span className="label">Cidade</span><select className="input" value={selectedCity} onChange={e=>setSelectedCity(e.target.value)}>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></label></div>
  <div className="live-map-summary"><span><b>{rows.length}</b> motorista(s) localizado(s)</span><span>{selected?`${selected.name}/${selected.state}`:'—'}</span><span>{msg}</span></div>
  <div ref={mapEl} className="live-map-canvas" style={{height:compact?330:460}}/>
  {!compact&&<div className="table-wrap" style={{marginTop:14}}><table className="table"><thead><tr><th>Motorista</th><th>Velocidade</th><th>Atualizado</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={3} className="empty">Nenhuma localização recebida.</td></tr>:rows.map(row=><tr key={row.driver_id}><td>{row.driver_id.slice(0,8)}…</td><td>{Math.round(row.speed_kmh??0)} km/h</td><td>{new Date(row.updated_at).toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div>}
 </div>
}
