'use client'
import {useEffect,useRef,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {getMyFranchise} from '@/lib/myFranchise'
import 'leaflet/dist/leaflet.css'

type Cell={lat:number;lng:number;count:number}
export default function RideHeatMap(){const[rows,setRows]=useState<Cell[]>([]),[total,setTotal]=useState(0),[days,setDays]=useState(30),[msg,setMsg]=useState('');const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),layerRef=useRef<any>(null)
 async function load(){try{const me=await getMyFranchise();const since=new Date(Date.now()-days*86400000).toISOString();const {data,error}=await supabase.from('rides').select('origin_lat,origin_lng,requested_at').eq('franchise_id',me.franchiseId).gte('requested_at',since).not('origin_lat','is',null).not('origin_lng','is',null).limit(5000);if(error)throw error;const m=new Map<string,Cell>();for(const r of data||[]){const lat=Number(r.origin_lat),lng=Number(r.origin_lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))continue;const a=Math.round(lat*1000)/1000,b=Math.round(lng*1000)/1000,k=`${a}|${b}`,old=m.get(k);if(old)old.count++;else m.set(k,{lat:a,lng:b,count:1})}const list=[...m.values()].sort((a,b)=>b.count-a.count);setRows(list);setTotal((data||[]).length);setMsg('')}catch(e:any){setMsg(e.message||'Erro ao carregar mapa de calor')}}
 useEffect(()=>{load()},[days])
 useEffect(()=>{let alive=true;(async()=>{if(!mapEl.current)return;const L=await import('leaflet');if(!alive)return;if(!mapRef.current){mapRef.current=L.map(mapEl.current).setView([-14.235,-51.9253],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(mapRef.current);layerRef.current=L.layerGroup().addTo(mapRef.current)}layerRef.current.clearLayers();const max=Math.max(1,...rows.map(r=>r.count)),points:any[]=[];for(const r of rows){const ratio=r.count/max;const color=ratio>=.75?'#ef4444':ratio>=.45?'#f97316':ratio>=.2?'#eab308':'#22c55e';L.circle([r.lat,r.lng],{radius:Math.max(120,260+ratio*900),color,fillColor:color,fillOpacity:.28+.42*ratio,weight:1}).bindPopup(`<strong>${r.count} chamado${r.count===1?'':'s'}</strong><br/>Concentração de solicitações`).addTo(layerRef.current);points.push([r.lat,r.lng])}if(points.length===1)mapRef.current.setView(points[0],14);if(points.length>1)mapRef.current.fitBounds(points,{padding:[30,30]})})();return()=>{alive=false}},[rows])
 useEffect(()=>()=>{if(mapRef.current){mapRef.current.remove();mapRef.current=null}},[])
 return <><div className="grid-3"><div className="card"><div className="label">Chamados no período</div><div className="metric kpi-good">{total}</div></div><div className="card"><div className="label">Zonas com demanda</div><div className="metric">{rows.length}</div></div><div className="card"><div className="label">Período</div><select className="input" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>Hoje</option><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option></select></div></div>{msg&&<p className="empty">{msg}</p>}<div className="section"><div ref={mapEl} style={{height:520,borderRadius:16,overflow:'hidden',border:'1px solid #292929'}}/></div><div className="card"><strong>Legenda:</strong> verde = baixa procura · amarelo = moderada · laranja = alta · vermelho = maior concentração de chamados.</div></>}
