'use client'

import {useEffect,useState} from 'react'
import {CalendarClock, CheckCircle2, CreditCard, RefreshCw} from 'lucide-react'
import {supabase} from '@/lib/supabase'

type Franchise={id:string;trade_name:string;license_status:string;due_day:number}
type Plan={id:string;name:string;monthly_fee:number;setup_fee:number;matrix_commission_percentage:number;included_rides:number;overage_fee_per_ride:number}
type Sub={id:string;franchise_id:string;plan_id:string;status:string;license_status:string;matrix_commission_percentage:number;starts_at:string;next_due_date:string|null;due_day:number|null}
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0))

export default function SubscriptionManager(){
 const[franchises,setFranchises]=useState<Franchise[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[subs,setSubs]=useState<Sub[]>([]);const[msg,setMsg]=useState('');const[franchiseId,setFranchiseId]=useState('');const[planId,setPlanId]=useState('');const[commission,setCommission]=useState('');const[dueDay,setDueDay]=useState('10');const[busy,setBusy]=useState(false)
 async function load(){const[f,p,s]=await Promise.all([supabase.from('franchises').select('id,trade_name,license_status,due_day').is('deleted_at',null).order('trade_name'),supabase.from('franchise_plans').select('id,name,monthly_fee,setup_fee,matrix_commission_percentage,included_rides,overage_fee_per_ride').eq('active',true).order('name'),supabase.from('franchise_subscriptions').select('id,franchise_id,plan_id,status,license_status,matrix_commission_percentage,starts_at,next_due_date,due_day').order('created_at',{ascending:false})]);setFranchises((f.data||[]) as Franchise[]);setPlans((p.data||[]) as Plan[]);setSubs((s.data||[]) as Sub[]);if(f.error||p.error||s.error)setMsg(f.error?.message||p.error?.message||s.error?.message||'Erro ao carregar licenças.')}
 useEffect(()=>{void load()},[])
 function chooseFranchise(id:string){setFranchiseId(id);const f=franchises.find(x=>x.id===id);setDueDay(String(f?.due_day||10))}
 async function assign(){if(!franchiseId||!planId){setMsg('Selecione a operação e o plano.');return}setBusy(true);const plan=plans.find(p=>p.id===planId);const pct=commission===''?Number(plan?.matrix_commission_percentage||0):Number(commission);const day=Math.min(28,Math.max(1,Number(dueDay)||10));const next=new Date();next.setDate(day);if(next<new Date())next.setMonth(next.getMonth()+1);await supabase.from('franchise_subscriptions').update({status:'cancelled',license_status:'cancelled',ends_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('franchise_id',franchiseId).eq('status','active');const{error}=await supabase.from('franchise_subscriptions').insert({franchise_id:franchiseId,plan_id:planId,matrix_commission_percentage:pct,status:'active',license_status:'active',activated_at:new Date().toISOString(),due_day:day,next_due_date:next.toISOString().slice(0,10)});if(!error)await supabase.from('franchises').update({active:true,license_status:'active',activation_date:new Date().toISOString().slice(0,10),due_day:day,next_due_date:next.toISOString().slice(0,10),updated_at:new Date().toISOString()}).eq('id',franchiseId);setBusy(false);setMsg(error?error.message:'Licença ativada e plano aplicado.');if(!error){setCommission('');void load()}}
 const fname=(id:string)=>franchises.find(f=>f.id===id)?.trade_name||'Operação';const pname=(id:string)=>plans.find(p=>p.id===id)?.name||'Plano';const active=subs.filter(s=>s.status==='active')
 return <>
  <div className="section"><div className="section-heading"><div><h2>Ativação comercial</h2><p className="subtitle">Vincule um plano à operação e defina o ciclo de cobrança.</p></div><CreditCard size={20}/></div><div className="card subscription-command"><div className="form-grid"><div className="field"><label>Operação / franquia</label><select className="input" value={franchiseId} onChange={e=>chooseFranchise(e.target.value)}><option value="">Selecione</option>{franchises.map(f=><option key={f.id} value={f.id}>{f.trade_name} · {f.license_status}</option>)}</select></div><div className="field"><label>Plano contratado</label><select className="input" value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Selecione</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.monthly_fee)}/mês</option>)}</select></div><div className="field"><label>Dia do vencimento</label><input className="input" type="number" min="1" max="28" value={dueDay} onChange={e=>setDueDay(e.target.value)}/></div><div className="field"><label>Comissão personalizada da Matriz (%)</label><input className="input" type="number" min="0" max="100" step="0.01" value={commission} onChange={e=>setCommission(e.target.value)} placeholder="Vazio = padrão do plano"/></div></div>{planId&&(()=>{const p=plans.find(x=>x.id===planId);return p?<div className="subscription-preview"><span><b>{money(p.setup_fee)}</b> implantação</span><span><b>{money(p.monthly_fee)}</b> mensalidade</span><span><b>{p.included_rides}</b> corridas incluídas</span><span><b>{money(p.overage_fee_per_ride)}</b> excedente</span></div>:null})()}<div className="toolbar" style={{marginTop:14}}><button className="button" disabled={busy||!franchiseId||!planId} onClick={()=>void assign()}><CheckCircle2 size={16}/>{busy?'Ativando...':'Ativar licença'}</button><button className="button secondary" onClick={()=>void load()}><RefreshCw size={15}/>Atualizar</button></div>{msg&&<p className="empty">{msg}</p>}</div></div>
  <div className="section"><div className="section-heading"><div><h2>Licenças ativas</h2><p className="subtitle">Situação comercial atual das operações.</p></div><CalendarClock size={20}/></div><div className="subscription-grid">{active.length===0?<div className="card empty">Nenhuma licença com plano ativo.</div>:active.map(s=><div className="card subscription-card" key={s.id}><div><span className="eyebrow">{pname(s.plan_id)}</span><h3>{fname(s.franchise_id)}</h3></div><span className={'pill '+(s.license_status==='active'?'green':s.license_status==='past_due'?'yellow':'red')}>{s.license_status}</span><dl><div><dt>Comissão Matriz</dt><dd>{s.matrix_commission_percentage}%</dd></div><div><dt>Início</dt><dd>{new Date(s.starts_at).toLocaleDateString('pt-BR')}</dd></div><div><dt>Próximo vencimento</dt><dd>{s.next_due_date?new Date(s.next_due_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</dd></div></dl></div>)}</div></div>
 </>
}
