'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Franchise={id:string;trade_name:string};type Plan={id:string;name:string;monthly_fee:number;matrix_commission_percentage:number};type Sub={id:string;franchise_id:string;plan_id:string;status:string;matrix_commission_percentage:number;starts_at:string}
export default function SubscriptionManager(){
 const [franchises,setFranchises]=useState<Franchise[]>([]);const [plans,setPlans]=useState<Plan[]>([]);const [subs,setSubs]=useState<Sub[]>([]);const [msg,setMsg]=useState('');const [franchiseId,setFranchiseId]=useState('');const [planId,setPlanId]=useState('');const [commission,setCommission]=useState('')
 async function load(){const [f,p,s]=await Promise.all([supabase.from('franchises').select('id,trade_name').is('deleted_at',null).eq('active',true).order('trade_name'),supabase.from('franchise_plans').select('id,name,monthly_fee,matrix_commission_percentage').eq('active',true).order('name'),supabase.from('franchise_subscriptions').select('id,franchise_id,plan_id,status,matrix_commission_percentage,starts_at').order('created_at',{ascending:false})]);setFranchises(f.data||[]);setPlans((p.data||[]) as Plan[]);setSubs((s.data||[]) as Sub[]);if(f.error||p.error||s.error)setMsg(f.error?.message||p.error?.message||s.error?.message||'Erro')}
 useEffect(()=>{load()},[])
 async function assign(){if(!franchiseId||!planId){setMsg('Selecione franquia e plano.');return}const plan=plans.find(p=>p.id===planId);const pct=commission===''?Number(plan?.matrix_commission_percentage||0):Number(commission);await supabase.from('franchise_subscriptions').update({status:'cancelled',ends_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('franchise_id',franchiseId).eq('status','active');const {error}=await supabase.from('franchise_subscriptions').insert({franchise_id:franchiseId,plan_id:planId,matrix_commission_percentage:pct,status:'active'});if(error){setMsg(error.message);return}setMsg('Plano atribuído à franquia.');setCommission('');load()}
 const fname=(id:string)=>franchises.find(f=>f.id===id)?.trade_name||id;const pname=(id:string)=>plans.find(p=>p.id===id)?.name||id
 return <><div className="section"><h2>Atribuir plano à franquia</h2><div className="card"><div className="form-grid"><div className="field"><label>Franquia</label><select className="input" value={franchiseId} onChange={e=>setFranchiseId(e.target.value)}><option value="">Selecione</option>{franchises.map(f=><option key={f.id} value={f.id}>{f.trade_name}</option>)}</select></div><div className="field"><label>Plano</label><select className="input" value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Selecione</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Comissão da matriz personalizada (%)</label><input className="input" type="number" min="0" max="100" step="0.01" value={commission} onChange={e=>setCommission(e.target.value)} placeholder="Vazio = usar padrão do plano"/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button" onClick={assign}>Aplicar plano</button></div>{msg&&<p className="empty">{msg}</p>}</div></div><div className="section"><h2>Planos por franquia</h2><div className="table-wrap"><table className="table"><thead><tr><th>Franquia</th><th>Plano</th><th>Comissão matriz</th><th>Status</th><th>Início</th></tr></thead><tbody>{subs.length===0?<tr><td colSpan={5} className="empty">Nenhum plano atribuído.</td></tr>:subs.map(s=><tr key={s.id}><td>{fname(s.franchise_id)}</td><td>{pname(s.plan_id)}</td><td>{s.matrix_commission_percentage}%</td><td>{s.status}</td><td>{new Date(s.starts_at).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div></div></>
}
