'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Ticket={id:string;requester_id:string|null;subject:string;priority:string;status:string;description:string;created_at:string;franchise_id:string|null;city_id:string|null}
type Profile={id:string;full_name:string|null;phone:string|null;email:string|null;role:string}
export default function SupportManager(){
 const[rows,setRows]=useState<Ticket[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[msg,setMsg]=useState('');const[form,setForm]=useState({subject:'',category:'geral',priority:'normal',description:''})
 async function load(){const[t,p]=await Promise.all([supabase.from('support_tickets').select('id,requester_id,subject,priority,status,description,created_at,franchise_id,city_id').order('created_at',{ascending:false}),supabase.from('profiles').select('id,full_name,phone,email,role')]);if(t.error)setMsg(t.error.message);else setRows((t.data||[]) as Ticket[]);setProfiles((p.data||[]) as Profile[])}
 useEffect(()=>{load();const ch=supabase.channel('super-admin-support-live').on('postgres_changes',{event:'*',schema:'public',table:'support_tickets'},load).subscribe();return()=>{supabase.removeChannel(ch)}},[])
 async function add(e:React.FormEvent){e.preventDefault();const{data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('support_tickets').insert({requester_id:user?.id||null,subject:form.subject,category:form.category,priority:form.priority,description:form.description,status:'open'});if(error){setMsg(error.message);return}setForm({subject:'',category:'geral',priority:'normal',description:''});setMsg('Chamado criado.');load()}
 async function status(id:string,value:string){await supabase.from('support_tickets').update({status:value,updated_at:new Date().toISOString(),closed_at:value==='closed'?new Date().toISOString():null}).eq('id',id);load()}
 const who=(id:string|null)=>profiles.find(p=>p.id===id)
 return <><div className="card"><form onSubmit={add}><div className="form-grid"><div className="field"><label>Assunto</label><input className="input" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} required/></div><div className="field"><label>Prioridade</label><select className="input" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div><div className="field"><label>Categoria</label><input className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div><div className="field"><label>Descrição</label><textarea className="input" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button">Abrir chamado</button></div>{msg&&<p className="empty">{msg}</p>}</form></div><div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Assunto</th><th>Solicitante</th><th>Contato</th><th>Prioridade</th><th>Status</th><th>Aberto em</th><th>Ações</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={7} className="empty">Nenhum chamado.</td></tr>:rows.map(t=>{const p=who(t.requester_id);return <tr key={t.id}><td><strong>{t.subject}</strong><br/><span className="empty">{t.description}</span></td><td>{p?.full_name||'Sistema'}<br/><span className="empty">{p?.role||''}</span></td><td>{p?.phone?<a href={`tel:${p.phone}`}>{p.phone}</a>:'—'}<br/><span className="empty">{p?.email||''}</span></td><td><span className={'pill '+(t.priority==='urgent'?'red':t.priority==='high'?'yellow':'')}>{t.priority}</span></td><td>{t.status}</td><td>{new Date(t.created_at).toLocaleString('pt-BR')}</td><td><select className="input" value={t.status} onChange={e=>status(t.id,e.target.value)}><option value="open">Aberto</option><option value="in_progress">Em andamento</option><option value="waiting">Aguardando</option><option value="resolved">Resolvido</option><option value="closed">Fechado</option></select></td></tr>})}</tbody></table></div></div></>
}
