'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'

type City={id:string;name:string;state:string};type Rule={id:string;city_id:string;base_fare:number;price_per_km:number;price_per_minute:number;minimum_fare:number;cancellation_fee:number;dynamic_multiplier:number;active:boolean}
export default function TariffManager(){
 const [cities,setCities]=useState<City[]>([]);const [rows,setRows]=useState<Rule[]>([]);const [msg,setMsg]=useState('');const [form,setForm]=useState({city_id:'',base_fare:'0',price_per_km:'0',price_per_minute:'0',minimum_fare:'0',cancellation_fee:'0',dynamic_multiplier:'1'})
 async function load(){const c=await supabase.from('cities').select('id,name,state').eq('active',true).order('name');setCities(c.data||[]);const r=await supabase.from('city_pricing_rules').select('id,city_id,base_fare,price_per_km,price_per_minute,minimum_fare,cancellation_fee,dynamic_multiplier,active').order('created_at',{ascending:false});if(r.error)setMsg(r.error.message);else setRows((r.data||[]) as Rule[])}
 useEffect(()=>{load()},[])
 async function save(e:React.FormEvent){e.preventDefault();const payload={city_id:form.city_id,category_id:null,base_fare:Number(form.base_fare),price_per_km:Number(form.price_per_km),price_per_minute:Number(form.price_per_minute),minimum_fare:Number(form.minimum_fare),cancellation_fee:Number(form.cancellation_fee),dynamic_multiplier:Number(form.dynamic_multiplier),active:true,updated_at:new Date().toISOString()};const {error}=await supabase.from('city_pricing_rules').upsert(payload,{onConflict:'city_id,category_id'});if(error){setMsg(error.message);return}setMsg('Tarifa salva.');load()}
 async function toggle(r:Rule){await supabase.from('city_pricing_rules').update({active:!r.active,updated_at:new Date().toISOString()}).eq('id',r.id);load()}
 const cityName=(id:string)=>{const c=cities.find(x=>x.id===id);return c?`${c.name}/${c.state}`:id};const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)
 return <><div className="card"><form onSubmit={save}><div className="form-grid"><div className="field"><label>Cidade</label><select className="input" value={form.city_id} onChange={e=>setForm({...form,city_id:e.target.value})} required><option value="">Selecione</option>{cities.map(c=><option value={c.id} key={c.id}>{c.name}/{c.state}</option>)}</select></div><div className="field"><label>Tarifa base</label><input className="input" type="number" step="0.01" value={form.base_fare} onChange={e=>setForm({...form,base_fare:e.target.value})}/></div><div className="field"><label>Preço por km</label><input className="input" type="number" step="0.01" value={form.price_per_km} onChange={e=>setForm({...form,price_per_km:e.target.value})}/></div><div className="field"><label>Preço por minuto</label><input className="input" type="number" step="0.01" value={form.price_per_minute} onChange={e=>setForm({...form,price_per_minute:e.target.value})}/></div><div className="field"><label>Tarifa mínima</label><input className="input" type="number" step="0.01" value={form.minimum_fare} onChange={e=>setForm({...form,minimum_fare:e.target.value})}/></div><div className="field"><label>Cancelamento</label><input className="input" type="number" step="0.01" value={form.cancellation_fee} onChange={e=>setForm({...form,cancellation_fee:e.target.value})}/></div><div className="field"><label>Multiplicador dinâmico</label><input className="input" type="number" step="0.01" value={form.dynamic_multiplier} onChange={e=>setForm({...form,dynamic_multiplier:e.target.value})}/></div></div><div className="toolbar" style={{marginTop:14}}><button className="button">Salvar tarifa</button></div>{msg&&<p className="empty">{msg}</p>}</form></div><div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Cidade</th><th>Base</th><th>/km</th><th>/min</th><th>Mínima</th><th>Cancelamento</th><th>Dinâmica</th><th>Status</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={8} className="empty">Nenhuma tarifa configurada.</td></tr>:rows.map(r=><tr key={r.id}><td>{cityName(r.city_id)}</td><td>{brl(r.base_fare)}</td><td>{brl(r.price_per_km)}</td><td>{brl(r.price_per_minute)}</td><td>{brl(r.minimum_fare)}</td><td>{brl(r.cancellation_fee)}</td><td>{r.dynamic_multiplier}x</td><td><button className="button secondary" onClick={()=>toggle(r)}>{r.active?'Ativa':'Inativa'}</button></td></tr>)}</tbody></table></div></div></>
}
