'use client'

import { useEffect,useMemo,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Row={session_id:string;driver_id:string;driver_name:string|null;franchise_id:string;franchise_name:string|null;city_id:string;city_name:string|null;status:string;started_at:string;ended_at:string|null;distance_m:number|string;elapsed_seconds:number;final_amount:number|string|null;current_amount:number|string;payment_method:string|null;multiplier:number|string}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:16}
const input:React.CSSProperties={background:'#0b0b0b',color:'#fff',border:'1px solid #333',borderRadius:9,padding:'10px 11px'}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',border:0,borderRadius:9,padding:'10px 12px',fontWeight:900,cursor:'pointer'}
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const clock=(s:number)=>`${Math.floor((s||0)/3600).toString().padStart(2,'0')}:${Math.floor(((s||0)%3600)/60).toString().padStart(2,'0')}:${Math.floor((s||0)%60).toString().padStart(2,'0')}`
const isoDate=(d:Date)=>d.toISOString().slice(0,10)
const pay=(v:string|null)=>v==='cash'?'Dinheiro':v==='pix_external'?'PIX':v==='card_machine'?'Maquininha':v||'—'

export default function TaximeterOperationsReport({network=false}:{network?:boolean}){
 const today=new Date(),before=new Date(Date.now()-29*86400000)
 const[from,setFrom]=useState(isoDate(before)),[to,setTo]=useState(isoDate(today)),[rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>{void load()},[])
 async function load(){setBusy(true);setMsg('');const pFrom=new Date(`${from}T00:00:00`).toISOString(),pTo=new Date(`${to}T23:59:59.999`).toISOString();const{data,error}=await supabase.rpc('get_taximeter_operations_report',{p_from:pFrom,p_to:pTo,p_limit:5000});setBusy(false);if(error){setMsg(error.message);return}setRows((data||[]) as Row[])}
 const filtered=useMemo(()=>rows.filter(r=>{const hay=`${r.driver_name||''} ${r.franchise_name||''} ${r.city_name||''}`.toLowerCase();return(status==='all'||r.status===status)&&(!q||hay.includes(q.toLowerCase()))}),[rows,q,status])
 const finished=filtered.filter(r=>r.status==='finished'),revenue=finished.reduce((a,r)=>a+Number(r.final_amount||0),0),km=filtered.reduce((a,r)=>a+Number(r.distance_m||0)/1000,0),seconds=filtered.reduce((a,r)=>a+Number(r.elapsed_seconds||0),0)
 function exportCsv(){const head=['Data','Motorista','Franquia','Cidade','Status','Km','Tempo','Valor','Pagamento','Bandeira'];const body=filtered.map(r=>[new Date(r.started_at).toLocaleString('pt-BR'),r.driver_name||'',r.franchise_name||'',r.city_name||'',r.status,(Number(r.distance_m||0)/1000).toFixed(2),clock(r.elapsed_seconds),Number(r.final_amount||0).toFixed(2),pay(r.payment_method),Number(r.multiplier||1).toFixed(2)]);const csv=[head,...body].map(x=>x.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`clickgo-taximetro-${from}-${to}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div>
  <div className="topbar"><div><div className="eyebrow">Operação</div><h1 className="title">Relatório de Taxímetros</h1><p className="subtitle">{network?'Visão da matriz sobre corridas livres de toda a rede.':'Corridas livres registradas pelos motoristas da sua franquia.'}</p></div></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10,marginBottom:14}}><div style={box}><small style={{color:'#9ca3af'}}>SESSÕES</small><div style={{fontSize:30,fontWeight:950}}>{filtered.length}</div></div><div style={box}><small style={{color:'#9ca3af'}}>FINALIZADAS</small><div style={{fontSize:30,fontWeight:950,color:'#4ade80'}}>{finished.length}</div></div><div style={box}><small style={{color:'#9ca3af'}}>KM RODADOS</small><div style={{fontSize:30,fontWeight:950}}>{km.toFixed(1)}</div></div><div style={box}><small style={{color:'#9ca3af'}}>VALOR REGISTRADO</small><div style={{fontSize:30,fontWeight:950,color:'#ffd400'}}>{money(revenue)}</div></div></div>
  <div style={{...box,display:'flex',gap:8,flexWrap:'wrap',alignItems:'end',marginBottom:14}}><label style={{display:'grid',gap:4,fontSize:12,color:'#9ca3af'}}>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)} style={input}/></label><label style={{display:'grid',gap:4,fontSize:12,color:'#9ca3af'}}>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)} style={input}/></label><label style={{display:'grid',gap:4,fontSize:12,color:'#9ca3af',minWidth:230,flex:1}}>Buscar motorista/cidade{network?'/franquia':''}<input value={q} onChange={e=>setQ(e.target.value)} style={input} placeholder="Digite para filtrar"/></label><label style={{display:'grid',gap:4,fontSize:12,color:'#9ca3af'}}>Status<select value={status} onChange={e=>setStatus(e.target.value)} style={input}><option value="all">Todos</option><option value="running">Em andamento</option><option value="finished">Finalizados</option><option value="cancelled">Cancelados</option></select></label><button disabled={busy} onClick={load} style={btn}>{busy?'Carregando…':'Aplicar período'}</button><button onClick={exportCsv} style={{...btn,background:'#222',color:'#fff'}}>Exportar CSV</button></div>
  {msg&&<div style={{...box,borderColor:'#7c2d12',color:'#fca5a5',marginBottom:12}}>{msg}</div>}
  <div style={{...box,padding:0,overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1000}}><thead><tr>{['Data','Motorista',network?'Franquia':'Cidade','Status','Distância','Tempo','Valor','Pagamento','Bandeira'].map(h=><th key={h} style={{textAlign:'left',padding:12,borderBottom:'1px solid #333',fontSize:12,color:'#9ca3af'}}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.session_id}><td style={{padding:12,borderBottom:'1px solid #222'}}>{new Date(r.started_at).toLocaleString('pt-BR')}</td><td style={{padding:12,borderBottom:'1px solid #222'}}><b>{r.driver_name||r.driver_id.slice(0,8)}</b><div style={{fontSize:11,color:'#9ca3af'}}>{r.city_name||'—'}</div></td><td style={{padding:12,borderBottom:'1px solid #222'}}>{network?(r.franchise_name||'—'):(r.city_name||'—')}</td><td style={{padding:12,borderBottom:'1px solid #222'}}><span style={{fontWeight:900,color:r.status==='finished'?'#4ade80':r.status==='running'?'#fbbf24':'#9ca3af'}}>{r.status==='finished'?'Finalizada':r.status==='running'?'Em andamento':'Cancelada'}</span></td><td style={{padding:12,borderBottom:'1px solid #222'}}>{(Number(r.distance_m||0)/1000).toFixed(2)} km</td><td style={{padding:12,borderBottom:'1px solid #222'}}>{clock(r.elapsed_seconds)}</td><td style={{padding:12,borderBottom:'1px solid #222',fontWeight:900,color:'#ffd400'}}>{money(r.status==='finished'?r.final_amount:r.current_amount)}</td><td style={{padding:12,borderBottom:'1px solid #222'}}>{pay(r.payment_method)}</td><td style={{padding:12,borderBottom:'1px solid #222'}}>x{Number(r.multiplier||1).toFixed(2)}</td></tr>)}{!filtered.length&&<tr><td colSpan={9} style={{padding:28,textAlign:'center',color:'#9ca3af'}}>Nenhum taxímetro encontrado no período.</td></tr>}</tbody></table></div>
  <div style={{fontSize:12,color:'#9ca3af',marginTop:9}}>Tempo somado: {clock(seconds)}. Os valores são registros operacionais do taxímetro; conciliação financeira pode ser tratada separadamente.</div>
 </div>
}
