'use client'

import {FormEvent,useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'

export default function TempPasswordPage(){
 const[p1,setP1]=useState('');const[p2,setP2]=useState('');const[show,setShow]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[ready,setReady]=useState(false)
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{const u=data.user;if(!u){window.location.href='/franqueado/login';return}if(u.app_metadata?.role!=='franchise_admin'){window.location.href='/';return}if(u.app_metadata?.must_change_password!==true){window.location.href='/franqueado';return}setReady(true)})},[])
 async function submit(e:FormEvent){e.preventDefault();if(p1.length<8){setMsg('A nova senha deve ter pelo menos 8 caracteres.');return}if(p1!==p2){setMsg('As senhas não conferem.');return}setBusy(true);setMsg('Salvando nova senha...');const{data,error}=await supabase.functions.invoke('franchise-temp-password',{body:{action:'complete_change',new_password:p1}});if(error||data?.error){setBusy(false);setMsg(data?.error||error?.message||'Não foi possível alterar a senha.');return}await supabase.auth.refreshSession();window.location.href='/franqueado'}
 if(!ready)return <div className="card" style={{maxWidth:520,margin:'12vh auto',textAlign:'center'}}><div className="eyebrow">CLICK-GO</div><h2>Verificando acesso...</h2></div>
 return <div className="card" style={{maxWidth:520,margin:'10vh auto'}}><div className="eyebrow">PRIMEIRO ACESSO</div><h1 className="title">Crie sua nova senha</h1><p className="subtitle">A senha enviada pela matriz é temporária. Para continuar no Painel do Franqueado, defina uma senha pessoal agora.</p><form onSubmit={submit} className="module-list" style={{marginTop:22}}><div className="field"><label>Nova senha</label><input className="input" type={show?'text':'password'} value={p1} onChange={e=>setP1(e.target.value)} minLength={8} required/></div><div className="field"><label>Confirmar nova senha</label><input className="input" type={show?'text':'password'} value={p2} onChange={e=>setP2(e.target.value)} minLength={8} required/></div><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Mostrar senha</label><button className="button" disabled={busy}>{busy?'Salvando...':'Salvar nova senha e entrar'}</button>{msg&&<p className="empty">{msg}</p>}</form></div>
}
