'use client'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import {getMyFranchise} from '@/lib/myFranchise'

type City={id:string;name:string;state:string}
const empty={full_name:'',email:'',phone:'',password:'',city_id:''}
export default function Page(){
 const[rows,setRows]=useState<any[]>([]);const[cities,setCities]=useState<City[]>([]);const[form,setForm]=useState(empty);const[msg,setMsg]=useState('');const[saving,setSaving]=useState(false)
 async function load(){try{const c=await getMyFranchise();const fc=await supabase.from('franchise_cities').select('city_id,cities(id,name,state)').eq('franchise_id',c.franchiseId);setCities((fc.data||[]).map((x:any)=>x.cities).filter(Boolean));const {data,error}=await supabase.from('profiles').select('id,full_name,phone,active,city_id,created_at,cities(name,state)').eq('franchise_id',c.franchiseId).eq('role','passenger').order('created_at',{ascending:false});if(error)throw error;setRows(data||[])}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load()},[])
 async function createPassenger(e:React.FormEvent){e.preventDefault();setSaving(true);setMsg('');try{const {data,error}=await supabase.functions.invoke('admin-users',{body:{action:'create_operational_user',user_role:'passenger',full_name:form.full_name,email:form.email,phone:form.phone,password:form.password,city_id:form.city_id}});if(error)throw error;if(data?.error)throw new Error(data.error);setForm(empty);setMsg('Passageiro cadastrado com sucesso.');await load()}catch(e:any){setMsg(e.message||'Não foi possível cadastrar o passageiro.')}finally{setSaving(false)}}
 return <><div className="topbar"><div><div className="eyebrow">Operação</div><h1 className="title">Passageiros</h1><p className="subtitle">Cadastre e visualize os passageiros vinculados à sua operação.</p></div></div>
 <div className="card"><h2>Cadastrar passageiro</h2><form onSubmit={createPassenger}><div className="form-grid"><div className="field"><label>Nome completo</label><input className="input" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></div><div className="field"><label>E-mail</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div className="field"><label>Telefone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></div><div className="field"><label>Senha temporária</label><input className="input" type="password" minLength={6} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></div><div className="field"><label>Cidade</label><select className="input" value={form.city_id} onChange={e=>setForm({...form,city_id:e.target.value})} required><option value="">Selecione</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}/{c.state}</option>)}</select></div></div><button className="button" disabled={saving} style={{marginTop:14}}>{saving?'Cadastrando...':'Cadastrar passageiro'}</button></form></div>
 {msg&&<p className="empty">{msg}</p>}<div className="section"><div className="table-wrap"><table className="table"><thead><tr><th>Passageiro</th><th>Telefone</th><th>Cidade</th><th>Status</th><th>Cadastro</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.full_name||'Sem nome'}</td><td>{r.phone||'—'}</td><td>{r.cities?`${r.cities.name}/${r.cities.state}`:'—'}</td><td>{r.active?'Ativo':'Bloqueado'}</td><td>{new Date(r.created_at).toLocaleDateString('pt-BR')}</td></tr>):<tr><td colSpan={5} className="empty">Nenhum passageiro.</td></tr>}</tbody></table></div></div></>}
