'use client'

import { useEffect,useMemo,useState } from 'react'
import { supabase } from '@/lib/supabase'

type Pay={scope:string;cash_enabled:boolean;pix_enabled:boolean;card_app_enabled:boolean;card_machine_enabled:boolean;card_credit_enabled:boolean;card_debit_enabled:boolean;app_card_gateway:string|null;card_surcharge_percentage:number|string;card_fee_bearer:string;installments_enabled:boolean;max_installments:number;franchise_can_manage:boolean}
type Wallet={scope:string;enabled:boolean;minimum_balance_to_receive:number|string;low_balance_threshold:number|string;default_ride_fee:number|string;franchise_can_set_ride_fee:boolean;franchise_manual_credit_enabled:boolean;franchise_manual_credit_limit:number|string|null}
type Pair={franchise_id:string;city_id:string}
type Franchise={id:string;trade_name:string}
type City={id:string;name:string;state:string}
type LocalPay={franchise_id:string;city_id:string;cash_enabled:boolean|null;pix_enabled:boolean|null;card_app_enabled:boolean|null;card_machine_enabled:boolean|null;locked_by_matrix:boolean}
type LocalWallet={franchise_id:string;ride_fee:number|string|null;minimum_balance_to_receive:number|string|null;low_balance_threshold:number|string|null;locked_by_matrix:boolean}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:18}
const input:React.CSSProperties={width:'100%',background:'#0d0d0d',color:'#fff',border:'1px solid #333',borderRadius:10,padding:'10px 11px'}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',border:0,borderRadius:9,padding:'10px 13px',fontWeight:800,cursor:'pointer'}

export default function MatrixPaymentSettingsPage(){
 const[pay,setPay]=useState<Pay|null>(null),[wallet,setWallet]=useState<Wallet|null>(null),[pairs,setPairs]=useState<Pair[]>([]),[franchises,setFranchises]=useState<Franchise[]>([]),[cities,setCities]=useState<City[]>([]),[localPays,setLocalPays]=useState<LocalPay[]>([]),[localWallets,setLocalWallets]=useState<LocalWallet[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const[override,setOverride]=useState({cash:true,pix:true,cardApp:false,cardMachine:false,lockPay:false,rideFee:'0',minimum:'0.01',low:'5',lockWallet:false})
 useEffect(()=>{load()},[])
 async function load(){setBusy(true);try{const[{data:p,error:pe},{data:w,error:we},{data:fc,error:fce},{data:f,error:fe},{data:c,error:ce},{data:lp,error:lpe},{data:lw,error:lwe}]=await Promise.all([supabase.from('platform_payment_settings').select('*').eq('scope','global').single(),supabase.from('platform_operational_wallet_settings').select('*').eq('scope','global').single(),supabase.from('franchise_cities').select('franchise_id,city_id'),supabase.from('franchises').select('id,trade_name').is('deleted_at',null),supabase.from('cities').select('id,name,state'),supabase.from('franchise_city_payment_settings').select('franchise_id,city_id,cash_enabled,pix_enabled,card_app_enabled,card_machine_enabled,locked_by_matrix'),supabase.from('franchise_operational_wallet_settings').select('franchise_id,ride_fee,minimum_balance_to_receive,low_balance_threshold,locked_by_matrix')]);if(pe)throw pe;if(we)throw we;if(fce)throw fce;if(fe)throw fe;if(ce)throw ce;if(lpe)throw lpe;if(lwe)throw lwe;setPay(p as Pay);setWallet(w as Wallet);setPairs((fc||[]) as Pair[]);setFranchises((f||[]) as Franchise[]);setCities((c||[]) as City[]);setLocalPays((lp||[]) as LocalPay[]);setLocalWallets((lw||[]) as LocalWallet[]);const key=selected||((fc||[])[0]?`${(fc||[])[0].franchise_id}|${(fc||[])[0].city_id}`:'');setSelected(key);applyOverride(key,(lp||[]) as LocalPay[],(lw||[]) as LocalWallet[],p as Pay,w as Wallet)}catch(e:any){setMsg(e.message||'Erro ao carregar configurações.')}finally{setBusy(false)}}
 function applyOverride(key:string,lps=localPays,lws=localWallets,p=pay,w=wallet){if(!key||!p||!w)return;const[fid,cid]=key.split('|');const lp=lps.find(x=>x.franchise_id===fid&&x.city_id===cid);const lw=lws.find(x=>x.franchise_id===fid);setOverride({cash:lp?.cash_enabled??p.cash_enabled,pix:lp?.pix_enabled??p.pix_enabled,cardApp:lp?.card_app_enabled??p.card_app_enabled,cardMachine:lp?.card_machine_enabled??p.card_machine_enabled,lockPay:!!lp?.locked_by_matrix,rideFee:String(lw?.ride_fee??w.default_ride_fee),minimum:String(lw?.minimum_balance_to_receive??w.minimum_balance_to_receive),low:String(lw?.low_balance_threshold??w.low_balance_threshold),lockWallet:!!lw?.locked_by_matrix})}
 const nameF=useMemo(()=>Object.fromEntries(franchises.map(x=>[x.id,x.trade_name])),[franchises]);const nameC=useMemo(()=>Object.fromEntries(cities.map(x=>[x.id,`${x.name}/${x.state}`])),[cities]);
 async function saveGlobal(){if(!pay||!wallet)return;setBusy(true);const[{error:pe},{error:we}]=await Promise.all([supabase.from('platform_payment_settings').update({...pay,updated_at:new Date().toISOString()}).eq('scope','global'),supabase.from('platform_operational_wallet_settings').update({...wallet,updated_at:new Date().toISOString()}).eq('scope','global')]);setBusy(false);if(pe||we){setMsg(pe?.message||we?.message||'Erro ao salvar.');return}setMsg('Configurações globais da Matriz salvas.');await load()}
 async function saveOverride(){if(!selected||!pay||!wallet)return;const[fid,cid]=selected.split('|');setBusy(true);const[{error:pe},{error:we}]=await Promise.all([supabase.from('franchise_city_payment_settings').upsert({franchise_id:fid,city_id:cid,cash_enabled:override.cash,pix_enabled:override.pix,card_app_enabled:override.cardApp,card_machine_enabled:override.cardMachine,locked_by_matrix:override.lockPay,updated_at:new Date().toISOString()},{onConflict:'franchise_id,city_id'}),supabase.from('franchise_operational_wallet_settings').upsert({franchise_id:fid,ride_fee:Number(override.rideFee||0),minimum_balance_to_receive:Number(override.minimum||0),low_balance_threshold:Number(override.low||0),locked_by_matrix:override.lockWallet,updated_at:new Date().toISOString()},{onConflict:'franchise_id'})]);setBusy(false);if(pe||we){setMsg(pe?.message||we?.message||'Erro ao salvar bloqueio.');return}setMsg('Regras específicas da franquia/cidade salvas pela Matriz.');await load()}
 const toggle=(obj:any,setter:any,key:string,label:string)=><label style={{...box,padding:11,display:'flex',justifyContent:'space-between',gap:10}}><span>{label}</span><input type="checkbox" checked={!!obj[key]} onChange={e=>setter({...obj,[key]:e.target.checked})}/></label>
 return <div style={{display:'grid',gap:14}}><div><div className="eyebrow">Super Admin</div><h1>Pagamentos & Carteira</h1><p className="subtitle">A Matriz define as regras máximas. Nenhuma franquia consegue habilitar uma modalidade bloqueada aqui.</p></div>
  {pay&&wallet&&<><section style={box}><h2>Meios de pagamento globais</h2><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9}}>{toggle(pay,setPay,'cash_enabled','Dinheiro')}{toggle(pay,setPay,'pix_enabled','PIX')}{toggle(pay,setPay,'card_app_enabled','Cartão pelo aplicativo')}{toggle(pay,setPay,'card_machine_enabled','Cartão na maquininha do motorista')}{toggle(pay,setPay,'card_credit_enabled','Cartão de crédito')}{toggle(pay,setPay,'card_debit_enabled','Cartão de débito')}{toggle(pay,setPay,'installments_enabled','Parcelamento')}{toggle(pay,setPay,'franchise_can_manage','Franqueado pode configurar pagamentos')}</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:9,marginTop:12}}><label>Gateway do cartão<input style={input} value={pay.app_card_gateway||''} onChange={e=>setPay({...pay,app_card_gateway:e.target.value||null})} placeholder="Mercado Pago, Pagar.me..."/></label><label>Acréscimo no cartão (%)<input type="number" step="0.01" style={input} value={pay.card_surcharge_percentage} onChange={e=>setPay({...pay,card_surcharge_percentage:e.target.value})}/></label><label>Responsável pela taxa<select style={input} value={pay.card_fee_bearer} onChange={e=>setPay({...pay,card_fee_bearer:e.target.value})}><option value="passenger">Passageiro</option><option value="driver">Motorista</option><option value="franchise">Franqueado</option><option value="platform">Matriz</option></select></label><label>Máximo de parcelas<input type="number" min={1} max={24} style={input} value={pay.max_installments} onChange={e=>setPay({...pay,max_installments:Number(e.target.value)})}/></label></div></section>
  <section style={box}><h2>Carteira operacional global</h2><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9}}>{toggle(wallet,setWallet,'enabled','Exigir saldo operacional para receber corridas')}{toggle(wallet,setWallet,'franchise_can_set_ride_fee','Franqueado pode definir taxa por corrida')}{toggle(wallet,setWallet,'franchise_manual_credit_enabled','Franqueado pode adicionar/retirar crédito')}</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:9,marginTop:12}}><label>Saldo mínimo<input type="number" step="0.01" style={input} value={wallet.minimum_balance_to_receive} onChange={e=>setWallet({...wallet,minimum_balance_to_receive:e.target.value})}/></label><label>Alerta de saldo baixo<input type="number" step="0.01" style={input} value={wallet.low_balance_threshold} onChange={e=>setWallet({...wallet,low_balance_threshold:e.target.value})}/></label><label>Taxa padrão por corrida<input type="number" step="0.01" style={input} value={wallet.default_ride_fee} onChange={e=>setWallet({...wallet,default_ride_fee:e.target.value})}/></label><label>Limite por crédito manual<input type="number" step="0.01" style={input} value={wallet.franchise_manual_credit_limit??''} onChange={e=>setWallet({...wallet,franchise_manual_credit_limit:e.target.value===''?null:e.target.value})} placeholder="Sem limite"/></label></div><button style={{...btn,marginTop:12}} onClick={saveGlobal} disabled={busy}>Salvar regras globais</button></section></>}
  <section style={box}><h2>Sobrescrever uma franquia/cidade</h2><p className="subtitle">Use quando a Matriz precisar bloquear ou impor uma regra específica.</p><select style={{...input,maxWidth:520}} value={selected} onChange={e=>{setSelected(e.target.value);applyOverride(e.target.value)}}>{pairs.map(p=><option key={`${p.franchise_id}|${p.city_id}`} value={`${p.franchise_id}|${p.city_id}`}>{nameF[p.franchise_id]||p.franchise_id.slice(0,8)} — {nameC[p.city_id]||p.city_id.slice(0,8)}</option>)}</select>{selected&&<div style={{display:'grid',gap:10,marginTop:14}}><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9}}>{toggle(override,setOverride,'cash','Permitir dinheiro')}{toggle(override,setOverride,'pix','Permitir PIX')}{toggle(override,setOverride,'cardApp','Permitir cartão no app')}{toggle(override,setOverride,'cardMachine','Permitir maquininha')}{toggle(override,setOverride,'lockPay','Bloquear edição de pagamentos pelo franqueado')}{toggle(override,setOverride,'lockWallet','Bloquear regras da carteira pelo franqueado')}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:9}}><label>Taxa por corrida<input type="number" step="0.01" style={input} value={override.rideFee} onChange={e=>setOverride({...override,rideFee:e.target.value})}/></label><label>Saldo mínimo<input type="number" step="0.01" style={input} value={override.minimum} onChange={e=>setOverride({...override,minimum:e.target.value})}/></label><label>Alerta saldo baixo<input type="number" step="0.01" style={input} value={override.low} onChange={e=>setOverride({...override,low:e.target.value})}/></label></div><button style={btn} disabled={busy} onClick={saveOverride}>Salvar sobrescrita da Matriz</button></div>}</section>
  {msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b'}}>{msg}</div>}
 </div>
}
