'use client'

import Link from 'next/link'
import {ArrowLeft,Home,MapPin,Navigation,Star,WalletCards,UserRound} from 'lucide-react'
import { useEffect,useRef,useState } from 'react'
import { supabase } from '@/lib/supabase'
import 'leaflet/dist/leaflet.css'

type Driver={id:string;status:string;online:boolean;rating:number|string;city_id:string|null;franchise_id:string|null}
type Profile={id:string;full_name:string|null;email:string|null;role:string}
type Offer={offer_id:string;ride_id:string;distance_to_pickup_km:number|string;eta_to_pickup_min:number;estimated_driver_earning:number|string;origin_label:string;origin_lat:number;origin_lng:number;destination_label:string;destination_lat:number;destination_lng:number;category_name:string|null}
type Ride={id:string;status:string;origin_label:string;origin_lat:number;origin_lng:number;destination_label:string;destination_lat:number;destination_lng:number;estimated_fare:number|string|null;final_fare:number|string|null;payment_method_preference:string|null;accepted_at:string|null;started_at:string|null}
type Location={lat:number;lng:number;heading:number|null;speed:number|null}
type WalletSummary={operational_balance:number|string;earnings_balance:number|string;minimum_balance:number|string;low_balance_threshold:number|string;ride_fee:number|string;ride_fee_mode?:'fixed'|'percentage';ride_fee_percentage?:number|string;operational_enabled:boolean;billing_mode:'wallet_per_ride'|'monthly';monthly_fee:number|string;monthly_due_day:number;monthly_paid_until:string|null}
type SettlementNotice={method:string;commission:number;rideFee:number;cancellationCollection:number;balance:number|null}
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export default function DriverOperationPage(){
 const[profile,setProfile]=useState<Profile|null>(null),[driver,setDriver]=useState<Driver|null>(null),[offers,setOffers]=useState<Offer[]>([]),[ride,setRide]=useState<Ride|null>(null),[location,setLocation]=useState<Location|null>(null),[wallet,setWallet]=useState<WalletSummary|null>(null),[machinePaid,setMachinePaid]=useState(false),[settlement,setSettlement]=useState<SettlementNotice|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const watchRef=useRef<number|null>(null),lastSentRef=useRef(0),mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),layerRef=useRef<any>(null)
 useEffect(()=>{load();return()=>{if(watchRef.current!==null&&navigator.geolocation)navigator.geolocation.clearWatch(watchRef.current)}},[])
 useEffect(()=>{if(!profile)return;const oc=supabase.channel(`driver-offers-${profile.id}`).on('postgres_changes',{event:'*',schema:'public',table:'ride_offers',filter:`driver_id=eq.${profile.id}`},()=>loadOffers()).subscribe();const rc=supabase.channel(`driver-rides-${profile.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rides',filter:`driver_id=eq.${profile.id}`},()=>loadCurrentRide()).subscribe();return()=>{supabase.removeChannel(oc);supabase.removeChannel(rc)}},[profile?.id])
 useEffect(()=>{let alive=true;(async()=>{if(!mapEl.current)return;const L=await import('leaflet');if(!alive)return;if(!mapRef.current){mapRef.current=L.map(mapEl.current).setView([-14.52472,-49.14083],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(mapRef.current);layerRef.current=L.layerGroup().addTo(mapRef.current)}layerRef.current.clearLayers();const pts:[number,number][]=[];if(location){L.circleMarker([location.lat,location.lng],{radius:8}).bindTooltip('Você').addTo(layerRef.current);pts.push([location.lat,location.lng])}const target=ride||offers[0];if(target){L.circleMarker([target.origin_lat,target.origin_lng],{radius:8}).bindTooltip('Passageiro / origem').addTo(layerRef.current);L.circleMarker([target.destination_lat,target.destination_lng],{radius:8}).bindTooltip('Destino').addTo(layerRef.current);L.polyline([[target.origin_lat,target.origin_lng],[target.destination_lat,target.destination_lng]]).addTo(layerRef.current);pts.push([target.origin_lat,target.origin_lng],[target.destination_lat,target.destination_lng])}if(pts.length>1)mapRef.current.fitBounds(pts,{padding:[35,35]});else if(pts.length===1)mapRef.current.setView(pts[0],15)})();return()=>{alive=false}},[location,ride,offers])
 useEffect(()=>()=>{if(mapRef.current){mapRef.current.remove();mapRef.current=null}},[])
 async function load(){setBusy(true);setMsg('');try{const{data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return}const{data:p,error:pe}=await supabase.from('profiles').select('id,full_name,email,role').eq('id',user.id).single();if(pe)throw pe;if(!p||p.role!=='driver')throw new Error('Esta área é exclusiva do motorista.');const{data:d,error:de}=await supabase.from('drivers').select('id,status,online,rating,city_id,franchise_id').eq('id',user.id).single();if(de)throw de;setProfile(p as Profile);setDriver(d as Driver);await Promise.all([loadOffers(),loadCurrentRide(),loadWallet()]);if(d.online)startLocationWatch(false)}catch(e:any){setMsg(e.message||'Erro ao carregar operação.')}finally{setBusy(false)}}
 async function loadOffers(){const{data,error}=await supabase.rpc('get_driver_pending_offers');if(!error)setOffers((data||[]) as Offer[])}
 async function loadCurrentRide(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data,error}=await supabase.from('rides').select('id,status,origin_label,origin_lat,origin_lng,destination_label,destination_lat,destination_lng,estimated_fare,final_fare,payment_method_preference,accepted_at,started_at').eq('driver_id',user.id).in('status',['accepted','driver_arriving','in_progress']).order('accepted_at',{ascending:false}).limit(1).maybeSingle();if(error)return;const r=(data||null) as Ride|null;setRide(r);if(r?.payment_method_preference==='card_machine'){const{data:p}=await supabase.from('payments').select('id').eq('ride_id',r.id).eq('method','card_machine').eq('status','paid').limit(1).maybeSingle();setMachinePaid(!!p)}else setMachinePaid(false)}
 async function loadWallet(){const{data,error}=await supabase.rpc('get_my_driver_wallet_summary');if(!error)setWallet((data?.[0]||null) as WalletSummary|null)}
 function getPosition():Promise<GeolocationPosition>{return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:5000}))}
 async function toggleOnline(){if(!driver)return;if(driver.status!=='approved'){setMsg('O franqueado precisa aprovar seu cadastro antes de você ficar online.');return}if(driver.online){setBusy(true);const{error}=await supabase.rpc('set_driver_online',{p_online:false,p_lat:null,p_lng:null});setBusy(false);if(error){setMsg(error.message);return}if(watchRef.current!==null){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null}setDriver({...driver,online:false});setOffers([]);setMsg('Você está offline.');return}if(!navigator.geolocation){setMsg('Seu aparelho não disponibiliza GPS.');return}setBusy(true);try{const pos=await getPosition();const loc={lat:pos.coords.latitude,lng:pos.coords.longitude,heading:pos.coords.heading,speed:pos.coords.speed};const{error}=await supabase.rpc('set_driver_online',{p_online:true,p_lat:loc.lat,p_lng:loc.lng});if(error)throw error;setLocation(loc);setDriver({...driver,online:true});startLocationWatch(true);setMsg('Você está online e pode receber chamadas.');await Promise.all([loadOffers(),loadWallet()])}catch(e:any){setMsg(wallet?.billing_mode==='monthly'?'Não foi possível ficar online. Verifique se sua mensalidade está paga e se seu cadastro está aprovado.':'Não foi possível ficar online. Verifique seu saldo operacional, GPS e aprovação do cadastro.')}finally{setBusy(false)}}
 function startLocationWatch(force:boolean){if(!navigator.geolocation||watchRef.current!==null)return;watchRef.current=navigator.geolocation.watchPosition(async pos=>{const loc={lat:pos.coords.latitude,lng:pos.coords.longitude,heading:pos.coords.heading,speed:pos.coords.speed};setLocation(loc);const now=Date.now();if(!force&&now-lastSentRef.current<5000)return;lastSentRef.current=now;await supabase.rpc('update_driver_location',{p_lat:loc.lat,p_lng:loc.lng,p_heading:loc.heading,p_speed_kmh:loc.speed==null?null:loc.speed*3.6})},()=>setMsg('Falha ao atualizar sua localização. Mantenha o GPS permitido.'),{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
 async function respond(offer:Offer,accept:boolean){setBusy(true);const{data,error}=await supabase.rpc('respond_to_ride_offer',{p_offer_id:offer.offer_id,p_accept:accept});setBusy(false);if(error){setMsg(error.message);await loadOffers();return}if(accept&&data?.accepted){setMsg('Corrida aceita. Siga até o passageiro.');setOffers([]);await loadCurrentRide()}else{setMsg(data?.reason==='wallet_or_driver_unavailable'?'Seu plano/saldo não permite aceitar esta chamada.':data?.reason==='card_machine_not_authorized'?'Sua maquininha ainda não está autorizada.':accept?'Esta chamada ficou indisponível.':'Chamada recusada.');await loadOffers()}}
 async function confirmMachine(){if(!ride)return;setBusy(true);const{error}=await supabase.rpc('confirm_driver_machine_payment',{p_ride_id:ride.id});setBusy(false);if(error){setMsg(error.message);return}setMachinePaid(true);setMsg('Pagamento na maquininha registrado. Agora você pode concluir a corrida.')}
 async function advance(action:'arrived'|'start'|'complete'){
  if(!ride)return
  setBusy(true)
  const method=ride.payment_method_preference||''
  const{data,error}=await supabase.rpc('advance_driver_ride',{p_ride_id:ride.id,p_action:action})
  setBusy(false)
  if(error){setMsg(error.message);return}
  if(action==='arrived')setMsg('Deslocamento iniciado.')
  else if(action==='start')setMsg('Corrida iniciada.')
  else if(method==='cash'||method==='card_machine'){
    const notice:SettlementNotice={method,commission:Number(data?.direct_collection_commission_debit||0),rideFee:Number(data?.per_ride_fee_debit||0),cancellationCollection:Number(data?.cancellation_collection_debit||0),balance:data?.operational_balance_after==null?null:Number(data.operational_balance_after)}
    setSettlement(notice)
    setMsg(method==='cash'?'Corrida concluída. O dinheiro foi recebido diretamente por você e os débitos correspondentes foram registrados na Carteira Operacional.':'Corrida concluída. O valor foi recebido na maquininha e os débitos correspondentes foram registrados na Carteira Operacional.')
  }else if(method==='pix')setMsg('Corrida concluída. No PIX pelo app, a divisão entre motorista, franqueado e matriz é automática após a confirmação do pagamento.')
  else setMsg(wallet?.billing_mode==='wallet_per_ride'?`Corrida concluída. Foi aplicado o desconto configurado de ${money(data?.per_ride_fee_debit||wallet?.ride_fee)}.`:'Corrida concluída.')
  await Promise.all([loadCurrentRide(),loadWallet()])
  if(data?.status==='completed')setRide(null)
  if(method==='card_machine')setMachinePaid(false)
 }
 if(!profile)return <main className="mobile-login"><div className="mobile-login-box"><div className="mobile-auth-card"><h2>Entre no App Motorista</h2><p className="mobile-muted">Faça login para ativar o GPS e receber corridas.</p><Link href="/motorista-app" className="mobile-primary" style={{display:'grid',placeItems:'center',textDecoration:'none',marginTop:14}}>Ir para o login</Link></div></div></main>
 const offer=offers[0],target=ride||offer,mapsUrl=target?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${target.origin_lat},${target.origin_lng}`)}`:''
 const monthlyOk=wallet?.billing_mode==='monthly'&&wallet.monthly_paid_until&&new Date(wallet.monthly_paid_until+'T12:00:00')>=new Date()
 const walletOk=wallet?.billing_mode!=='monthly'&&(!wallet?.operational_enabled||Number(wallet?.operational_balance)>=Number(wallet?.minimum_balance))
 const feeLabel=wallet?.ride_fee_mode==='percentage'?`${Number(wallet?.ride_fee_percentage||0).toLocaleString('pt-BR')}% por corrida`:`${money(wallet?.ride_fee)} por corrida`
 const rideStatus=ride?.status==='accepted'?'Corrida aceita':ride?.status==='driver_arriving'?'A caminho do passageiro':ride?.status==='in_progress'?'Corrida em andamento':''
 return <main className="mobile-app"><div className="mobile-app-frame" style={{maxWidth:900}}>
  <header className="mobile-app-top"><Link href="/motorista-app" className="mobile-round" aria-label="Voltar"><ArrowLeft size={19}/></Link><div className="mobile-brand"><div className="mobile-logo">CG</div><div><strong>Operação</strong><span>{profile.full_name?.split(' ')[0]||'Motorista'}</span></div></div><Link href="/motorista-app/carteira" className="mobile-round" aria-label="Carteira"><WalletCards size={18}/></Link></header>
  <div style={{position:'relative',background:'#ddd',height:'min(54vh,520px)'}}><div ref={mapEl} style={{position:'absolute',inset:0}}/><div style={{position:'absolute',left:14,right:14,top:14,display:'flex',justifyContent:'space-between',gap:8,pointerEvents:'none'}}><span className={`mobile-status ${driver?.online?'good':'warn'}`} style={{pointerEvents:'auto',boxShadow:'0 6px 20px rgba(0,0,0,.12)'}}>{driver?.online?'● Online':'○ Offline'}</span><span className="mobile-status" style={{pointerEvents:'auto',boxShadow:'0 6px 20px rgba(0,0,0,.12)'}}><Star size={14} fill="currentColor"/>{Number(driver?.rating||0).toFixed(1)}</span></div></div>
  <div className="mobile-body" style={{marginTop:-24,position:'relative',zIndex:2}}>
   <section className="mobile-content-panel" style={{borderRadius:26}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div className="caption" style={{fontWeight:800,textTransform:'uppercase',letterSpacing:'.08em'}}>Status</div><h2 style={{margin:'4px 0 0'}}>{ride?rideStatus:offer?'Nova chamada':driver?.online?'Aguardando chamadas':'Você está offline'}</h2></div><button onClick={toggleOnline} disabled={busy} className="mobile-primary" style={{background:driver?.online?'#111214':'#ffd400',color:driver?.online?'#fff':'#111',minWidth:150}}>{busy?'Aguarde...':driver?.online?'Ficar offline':'Ficar online'}</button></div>
    {wallet&&<div className="mobile-card" style={{marginTop:13,display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,background:'#f7f7f8'}}><div><div className="caption">{wallet.billing_mode==='monthly'?'Plano mensal':'Saldo operacional'}</div><b style={{fontSize:18}}>{wallet.billing_mode==='monthly'?money(wallet.monthly_fee):money(wallet.operational_balance)}</b><div className="caption" style={{marginTop:3}}>{wallet.billing_mode==='monthly'?(monthlyOk?'Mensalidade em dia':'Mensalidade pendente'):(walletOk?'Liberado para chamadas':'Saldo abaixo do mínimo')}</div></div><div><div className="caption">Cobrança</div><b style={{fontSize:16}}>{wallet.billing_mode==='monthly'?`Dia ${wallet.monthly_due_day}`:feeLabel}</b><div className="caption" style={{marginTop:3}}>{wallet.billing_mode==='monthly'?'Vencimento':'Por corrida concluída'}</div></div></div>}

    {!ride&&offer&&<div style={{marginTop:14,borderTop:'1px solid #e5e5e8',paddingTop:14}}><div className="mobile-status warn">Nova corrida</div><h2 style={{margin:'10px 0 5px'}}>{offer.category_name||'Corrida CLICK-GO'}</h2><div style={{display:'grid',gap:8}}><div style={{display:'flex',gap:9}}><MapPin size={18}/><div><b>Embarque</b><div className="mobile-muted">{offer.origin_label}</div></div></div><div style={{display:'flex',gap:9}}><Navigation size={18}/><div><b>Destino</b><div className="mobile-muted">{offer.destination_label}</div></div></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:13}}><div className="mobile-card"><div className="caption">Até o passageiro</div><b>{Number(offer.distance_to_pickup_km).toFixed(1)} km · {offer.eta_to_pickup_min} min</b></div><div className="mobile-card"><div className="caption">Ganho estimado</div><b style={{fontSize:20}}>{money(offer.estimated_driver_earning)}</b></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1.8fr',gap:8,marginTop:12}}><button className="mobile-secondary" onClick={()=>respond(offer,false)}>Recusar</button><button className="mobile-primary" onClick={()=>respond(offer,true)}>Aceitar corrida</button></div></div>}

    {!ride&&driver?.online&&!offer&&<div style={{textAlign:'center',padding:'24px 8px 8px'}}><Navigation size={28} style={{margin:'0 auto 9px'}}/><b style={{display:'block'}}>Procurando corridas próximas</b><div className="mobile-muted">Mantenha o GPS ligado. Uma nova chamada aparecerá aqui automaticamente.</div></div>}

    {ride&&<div style={{marginTop:14,borderTop:'1px solid #e5e5e8',paddingTop:14}}><div className="mobile-status good">{rideStatus}</div><h2 style={{margin:'10px 0 8px'}}>{ride.destination_label}</h2><div style={{display:'grid',gap:8}}><div style={{display:'flex',gap:9}}><MapPin size={18}/><div><b>Origem</b><div className="mobile-muted">{ride.origin_label}</div></div></div><div style={{display:'flex',gap:9}}><Navigation size={18}/><div><b>Destino</b><div className="mobile-muted">{ride.destination_label}</div></div></div></div><div className="mobile-card" style={{marginTop:12,display:'flex',justifyContent:'space-between',gap:10}}><span className="mobile-muted">Pagamento: {ride.payment_method_preference||'não informado'}</span><b>{money(ride.final_fare??ride.estimated_fare)}</b></div><div style={{display:'grid',gap:8,marginTop:11}}>{mapsUrl&&<a href={mapsUrl} target="_blank" rel="noreferrer" className="mobile-secondary" style={{display:'grid',placeItems:'center',textDecoration:'none'}}>Abrir navegação</a>}{ride.status==='accepted'&&<button className="mobile-primary" onClick={()=>advance('arrived')}>Estou indo buscar</button>}{ride.status==='driver_arriving'&&<button className="mobile-primary" onClick={()=>advance('start')}>Passageiro embarcou</button>}{ride.status==='in_progress'&&ride.payment_method_preference==='card_machine'&&!machinePaid&&<button className="mobile-primary" style={{background:'#166534',color:'#fff'}} onClick={confirmMachine}>Confirmar pagamento na maquininha</button>}{ride.status==='in_progress'&&<button className="mobile-primary" disabled={ride.payment_method_preference==='card_machine'&&!machinePaid} onClick={()=>advance('complete')}>Concluir corrida</button>}</div></div>}
   </section>
   {msg&&<div className="mobile-alert">{msg}</div>}
  </div>
  <nav className="mobile-bottom-nav"><Link className="mobile-nav-item" href="/motorista-app"><Home size={20}/><span>Início</span><i className="nav-dot"/></Link><button className="mobile-nav-item active"><Navigation size={20}/><span>Corridas</span><i className="nav-dot"/></button><Link className="mobile-nav-item" href="/motorista-app/carteira"><WalletCards size={20}/><span>Ganhos</span><i className="nav-dot"/></Link><Link className="mobile-nav-item" href="/motorista-app"><UserRound size={20}/><span>Perfil</span><i className="nav-dot"/></Link></nav>
  {settlement&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:10000,background:'rgba(0,0,0,.64)',display:'grid',placeItems:'center',padding:18}}><div className="mobile-content-panel" style={{maxWidth:520,width:'100%'}}><div className="mobile-status good">Corrida concluída</div><h2 style={{margin:'10px 0 5px'}}>Resumo da Carteira Operacional</h2><p className="mobile-muted">O passageiro pagou diretamente a você. A CLICK-GO descontou do saldo operacional somente as parcelas devidas e cobranças configuradas.</p><div style={{display:'grid',gap:8,marginTop:14}}>{settlement.commission>0&&<div className="mobile-card" style={{display:'flex',justifyContent:'space-between'}}><span>Comissões</span><b>- {money(settlement.commission)}</b></div>}{settlement.rideFee>0&&<div className="mobile-card" style={{display:'flex',justifyContent:'space-between'}}><span>Taxa do plano</span><b>- {money(settlement.rideFee)}</b></div>}{settlement.cancellationCollection>0&&<div className="mobile-card" style={{display:'flex',justifyContent:'space-between'}}><span>Taxa de cancelamento</span><b>- {money(settlement.cancellationCollection)}</b></div>}<div className="mobile-card" style={{display:'flex',justifyContent:'space-between',background:'#111214',color:'#fff'}}><span>Saldo após débitos</span><b style={{color:'#ffd400'}}>{settlement.balance==null?'—':money(settlement.balance)}</b></div></div><button className="mobile-primary" style={{width:'100%',marginTop:13}} onClick={()=>setSettlement(null)}>Entendi</button></div></div>}
 </div></main>
}
