'use client'

import {useEffect,useMemo,useState} from 'react'
import {CalendarDays, CreditCard, FileText, RefreshCw} from 'lucide-react'
import {supabase} from '@/lib/supabase'

type Adjustment={id:string;type:string;description:string;amount:number;created_at:string}
type Billing={franchise_id:string;franchise_name:string;reference_month:string;has_plan:boolean;plan_name:string;billing_model:string;rides_count:number;gross_ride_value:number;included_rides:number;overage_rides:number;monthly_fee:number;fixed_fee_per_ride:number;per_ride_amount:number;overage_fee_per_ride:number;overage_amount:number;percentage_rate:number;percentage_amount:number;adjustments_total:number;adjustments:Adjustment[];total_due:number;due_date:string;invoice_id:string|null;invoice_status:string;paid_at:string|null}
type Collection={overdue_days:number;open_overdue_amount:number;operation_suspended:boolean;allow_new_rides:boolean;allow_new_drivers:boolean;license_status:string}
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0))
const monthLabel=(iso:string)=>new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(`${iso.slice(0,7)}-15T12:00:00`)).toUpperCase()

export default function FranchiseInvoicePage(){
 const[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[bill,setBill]=useState<Billing|null>(null),[collection,setCollection]=useState<Collection|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);setMsg('');const{data:{user}}=await supabase.auth.getUser();if(!user){setMsg('Sessão não encontrada.');setBusy(false);return}const{data:p,error:pe}=await supabase.from('profiles').select('franchise_id').eq('id',user.id).single();const fid=String(p?.franchise_id||user.app_metadata?.franchise_id||'');if(pe||!fid){setMsg(pe?.message||'Franquia não vinculada.');setBusy(false);return}const ref=`${month}-01`;const[b,c]=await Promise.all([supabase.rpc('get_franchise_billing_summary',{p_franchise_id:fid,p_reference_month:ref}),supabase.rpc('get_franchise_collection_state',{p_franchise_id:fid})]);if(b.error||c.error){setMsg(b.error?.message||c.error?.message||'Não foi possível carregar a fatura.');setBusy(false);return}setBill(b.data as Billing);setCollection(c.data as Collection);setBusy(false)}
 useEffect(()=>{void load()},[month])
 const paid=Boolean(bill?.paid_at||bill?.invoice_status==='paid')
 const rows=useMemo(()=>{if(!bill||!bill.has_plan)return[];const out:{label:string;qty:string;unit:string;total:number;kind?:string}[]=[];out.push({label:`Mensalidade (Plano ${bill.plan_name})`,qty:'1',unit:brl(bill.monthly_fee),total:bill.monthly_fee});if(bill.included_rides>0)out.push({label:`Corridas incluídas (${bill.included_rides})`,qty:String(Math.min(bill.rides_count,bill.included_rides)),unit:brl(0),total:0});if(bill.overage_rides>0||bill.overage_fee_per_ride>0)out.push({label:'Corridas excedentes',qty:String(bill.overage_rides),unit:brl(bill.overage_fee_per_ride),total:bill.overage_amount});if(bill.fixed_fee_per_ride>0)out.push({label:'Taxa por corrida (Matriz)',qty:String(bill.rides_count),unit:brl(bill.fixed_fee_per_ride),total:bill.per_ride_amount});if(bill.percentage_rate>0)out.push({label:'Percentual sobre faturamento',qty:`${bill.percentage_rate}%`,unit:brl(bill.gross_ride_value),total:bill.percentage_amount});for(const a of bill.adjustments||[])out.push({label:a.description,qty:'—',unit:a.type==='fine'?'Multa':a.type==='credit'?'Crédito':a.type==='discount'?'Desconto':'Ajuste',total:Number(a.amount),kind:a.amount<0?'credit':'adjustment'});return out},[bill])
 return <div className="regional-home"><div className="regional-heading"><div><div className="eyebrow">Financeiro · CLICK-GO</div><h1>Fatura CLICK-GO</h1><p>Veja exatamente quanto sua franquia deve à Matriz e como o valor foi calculado.</p></div><div style={{display:'flex',gap:8,alignItems:'end'}}><div className="field"><label>Mês</label><input className="input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><button className="button secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/>Atualizar</button></div></div>{msg&&<div className="regional-alert">{msg}</div>}
 {collection?.operation_suspended&&<div style={{padding:14,border:'1px solid #d22',background:'#fff0f0',color:'#8b1111',borderRadius:12,marginBottom:16}}><strong>Sua licença está suspensa.</strong> Corridas estão bloqueadas. Regularize a situação financeira ou entre em contato com a Matriz.</div>}
 {bill&&!bill.has_plan?<div className="card empty">Nenhum plano contratado foi encontrado para este período.</div>:bill&&<>
  <div className="card"><div className="section-heading"><div><div className="eyebrow">Fatura do mês</div><h2>{monthLabel(bill.reference_month)}</h2><p className="subtitle">Franquia {bill.franchise_name} · Plano {bill.plan_name}</p></div><span className={'pill '+(paid?'green':collection?.overdue_days?'red':'yellow')}>{paid?'Pago':collection?.overdue_days?`${collection.overdue_days} dias em atraso`:'Aguardando pagamento'}</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Item</th><th>Qtde/Base</th><th>Valor unitário</th><th style={{textAlign:'right'}}>Total</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.label}-${i}`}><td>{r.kind==='credit'?'✅ ':''}{r.label}</td><td>{r.qty}</td><td>{r.unit}</td><td style={{textAlign:'right',fontWeight:700}}>{brl(r.total)}</td></tr>)}<tr><td colSpan={3}><strong>TOTAL DEVIDO À MATRIZ</strong></td><td style={{textAlign:'right',fontSize:22,fontWeight:900}}>{brl(bill.total_due)}</td></tr></tbody></table></div><div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap',marginTop:18}}><div><small>Vencimento</small><strong style={{display:'block',fontSize:18}}>{bill.due_date?new Date(bill.due_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</strong>{paid&&bill.paid_at&&<small>Pago em {new Date(bill.paid_at).toLocaleString('pt-BR')}</small>}</div><div className="toolbar"><button className="button secondary" disabled title="A emissão de boleto da Matriz será conectada ao gateway de cobrança"><FileText size={15}/>Gerar boleto</button><button className="button" disabled title="O Pix desta fatura será conectado à conta de cobrança da Matriz"><CreditCard size={15}/>Pagar com Pix</button></div></div><p className="subtitle" style={{marginTop:12}}>Boleto e Pix aparecem desabilitados enquanto a conta de cobrança da Matriz não estiver vinculada a este módulo. Nenhum pagamento fictício é gerado.</p></div>
  <div className="section"><div className="regional-kpis"><div className="regional-kpi"><span>Corridas concluídas</span><strong>{bill.rides_count.toLocaleString('pt-BR')}</strong><small>somente viagens finalizadas entram na cobrança</small></div><div className="regional-kpi"><span>Incluídas no plano</span><strong>{bill.included_rides.toLocaleString('pt-BR')}</strong><small>{bill.overage_rides.toLocaleString('pt-BR')} excedentes</small></div><div className="regional-kpi"><span>Faturamento em corridas</span><strong>{brl(bill.gross_ride_value)}</strong><small>base do período</small></div><div className="regional-kpi"><span>Ajustes</span><strong>{brl(bill.adjustments_total)}</strong><small>créditos, descontos ou multas da Matriz</small></div></div></div>
  <div className="section card"><div className="section-heading"><div><h3>Como esta cobrança funciona</h3><p className="subtitle">O Franqueado pode consultar e planejar, mas não altera as taxas definidas no plano pela Matriz.</p></div><CalendarDays size={20}/></div><p style={{margin:0,lineHeight:1.65}}>{bill.billing_model==='hybrid'?'Neste plano híbrido, o total é formado pela mensalidade, pela taxa da Matriz aplicada a cada corrida concluída e pelo valor adicional das corridas que ultrapassam a franquia mensal.':bill.billing_model==='fixed_per_ride'?'Neste plano, o total é formado pela mensalidade mais a taxa da Matriz por corrida concluída.':bill.billing_model==='percentage'?'Neste plano, o total é formado pela mensalidade mais o percentual contratado sobre o faturamento das corridas concluídas.':'Neste plano livre, a cobrança principal é a mensalidade contratada.'}</p></div>
 </>}</div>
}
