'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { supabase } from '@/lib/supabase'

type Payout={id:string;amount:number|string;destination_type:string;destination_key:string|null;status:string;requested_at:string;paid_at:string|null;notes:string|null}
type Tx={id:string;tipo_operacao:string;status_pagamento:string;valor_total:number|string;valor_motorista:number|string;valor_franqueado:number|string;valor_plataforma:number|string;data_criacao:string}
const input:React.CSSProperties={width:'100%',background:'#0b0b0b',color:'#fff',border:'1px solid #333',borderRadius:10,padding:'11px 12px'}
const btn:React.CSSProperties={background:'#ffd400',color:'#000',border:0,borderRadius:10,padding:'11px 14px',fontWeight:800,cursor:'pointer'}
const box:React.CSSProperties={background:'#141414',border:'1px solid #292929',borderRadius:16,padding:18}
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})

export default function RepassePage(){
 const [fid,setFid]=useState(''),[balance,setBalance]=useState(0),[payouts,setPayouts]=useState<Payout[]>([]),[txs,setTxs]=useState<Tx[]>([]),[amount,setAmount]=useState(''),[pix,setPix]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{load()},[])
 async function load(){setBusy(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Faça login.');const {data:p,error:pe}=await supabase.from('profiles').select('role,franchise_id').eq('id',user.id).single();if(pe)throw pe;if(!p||p.role!=='franchise_admin'||!p.franchise_id)throw new Error('Acesso exclusivo do franqueado.');setFid(p.franchise_id);const [w,po,t]=await Promise.all([supabase.from('franchise_wallets').select('available_balance').eq('franchise_id',p.franchise_id).maybeSingle(),supabase.from('payouts').select('*').eq('franchise_id',p.franchise_id).order('requested_at',{ascending:false}),supabase.from('financial_transactions').select('id,tipo_operacao,status_pagamento,valor_total,valor_motorista,valor_franqueado,valor_plataforma,data_criacao').eq('franchise_id',p.franchise_id).order('data_criacao',{ascending:false}).limit(500)]);setBalance(Number(w.data?.available_balance||0));setPayouts((po.data||[]) as Payout[]);setTxs((t.data||[]) as Tx[])}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function requestPayout(e:FormEvent){e.preventDefault();const value=Number(amount);if(value<=0)return setMsg('Informe um valor válido.');if(value>balance)return setMsg('O valor solicitado é maior que o saldo disponível.');if(!fid)return;setBusy(true);const {error}=await supabase.from('payouts').insert({franchise_id:fid,driver_id:null,amount:value,destination_type:'pix',destination_key:pix,status:'requested',notes:'Solicitado pelo painel do franqueado'});setMsg(error?error.message:'Repasse solicitado com sucesso.');if(!error){setAmount('');await load()}setBusy(false)}
 function exportCsv(){const header=['data','operacao','status','total','motorista','franqueado','matriz'];const rows=txs.map(t=>[new Date(t.data_criacao).toISOString(),t.tipo_operacao,t.status_pagamento,t.valor_total,t.valor_motorista,t.valor_franqueado,t.valor_plataforma]);const csv=[header,...rows].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`clickgo-extrato-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 return <main style={{minHeight:'100vh',background:'#080808',color:'#fff',padding:24}}><div style={{maxWidth:1200,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'}}><div><div style={{color:'#ffd400',fontWeight:900}}>CLICK-GO</div><h1>Repasses e extrato</h1></div><div style={{display:'flex',gap:8}}><Link href="/franqueado/operacao" style={{...btn,textDecoration:'none'}}>Central operacional</Link><button style={{...btn,background:'#222',color:'#fff'}} onClick={exportCsv}>Exportar CSV</button></div></div>{msg&&<div style={{...box,borderColor:'#665600',color:'#ffe66b',marginBottom:16}}>{msg}</div>}<div style={{display:'grid',gridTemplateColumns:'360px 1fr',gap:16}}><form onSubmit={requestPayout} style={box}><h2>Solicitar repasse</h2><div style={{fontSize:28,fontWeight:900,marginBottom:14}}>{money(balance)}</div><div style={{display:'grid',gap:10}}><input required type="number" min="0.01" step="0.01" placeholder="Valor do repasse" style={input} value={amount} onChange={e=>setAmount(e.target.value)}/><input required placeholder="Chave PIX" style={input} value={pix} onChange={e=>setPix(e.target.value)}/><button disabled={busy} style={btn}>{busy?'Processando...':'Solicitar repasse'}</button></div><p style={{color:'#9ca3af',fontSize:13}}>A solicitação entra como pendente para processamento/aprovação conforme as regras financeiras da matriz.</p></form><section style={box}><h2>Histórico de repasses</h2><table className="table"><thead><tr><th>Data</th><th>Valor</th><th>PIX</th><th>Status</th><th>Pagamento</th></tr></thead><tbody>{payouts.map(p=><tr key={p.id}><td>{new Date(p.requested_at).toLocaleString('pt-BR')}</td><td>{money(p.amount)}</td><td>{p.destination_key||'-'}</td><td>{p.status}</td><td>{p.paid_at?new Date(p.paid_at).toLocaleString('pt-BR'):'-'}</td></tr>)}{!payouts.length&&<tr><td colSpan={5}>Nenhuma solicitação.</td></tr>}</tbody></table></section></div><section style={{...box,marginTop:16}}><h2>Extrato</h2><table className="table"><thead><tr><th>Data</th><th>Operação</th><th>Status</th><th>Total</th><th>Franqueado</th><th>Matriz</th></tr></thead><tbody>{txs.slice(0,100).map(t=><tr key={t.id}><td>{new Date(t.data_criacao).toLocaleString('pt-BR')}</td><td>{t.tipo_operacao}</td><td>{t.status_pagamento}</td><td>{money(t.valor_total)}</td><td>{money(t.valor_franqueado)}</td><td>{money(t.valor_plataforma)}</td></tr>)}</tbody></table></section></div></main>
}
